### ISSUE TITLE
Some strings don't deobfuscated

### ISSUE THREAD

**Issue by Revocation** [java-deobfuscator/deobfuscator#104]
Today I have come across some obfuscate texts (Allatori) that have not been deobfuscated and others yes. Maybe can help to improve the strings deobfuscate.

- [] ;U\u0007Q\u0018H\u0006FF\u000fF
- [] ;U\tS\u001cH\u0006FF\u000fF
- [] K*T\034U\007OY

And many more, if you need the jar file just let me know.
Version used: http://rgho.st/6QFHZZhqJ
Best regards.

--
**Edited**
With previous (old/past year) version of deobfuscator this strings are deobfuscated completely... So, why with the new version don't? It's weird.

**Comment by FFY00** [comment]
I think @FireMasterK was the one to update the transformer, maybe he could help with that.

**Comment by Revocation** [comment]
Oh, I got it. Thanks @FFY00 I'll gonna wait the answer of @FireMasterK

**Comment by FireMasterK** [comment]
The jar which you are using uses the old allatori's obfuscation

**Comment by Revocation** [comment]
Yes @FireMasterK , the jar that I've used uses the old allatori's obfuscation. No errors with this new version of deob but several strings don't are deobfuscated. I guess that the new file (deobfuscator) should work with old and new code, but I don't know. If there's no way that the code can detect the type of obsfuscation and act, no problem, I'll save my old jar and I'll use it on old files, but in this case I think that should available to download too, for all people that have the same problem or need deobfucate old files.

Thanks for reply.
Best regards.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
