### ISSUE TITLE
[Suggestion] New Normalizers

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#108]
Some suggestions for new features:

A ParameterNormalizer that changes all the parameters to something like param1, param2, etc.
A LocalNormalizer that changes all the local variables to var1, var2, etc.

Some obfuscators like to use illegal characters, so its better to keep those generic.

**Comment by Janmm14** [comment]
Use a decompiler which ignores parameter and local variable names

**Comment by FFY00** [comment]
I think this is already done by normalizer.FieldNormalizer.

**Comment by netindev** [comment]
see #109
