### ISSUE TITLE
CI server 404ing

### ISSUE THREAD

**Issue by Stankye** [java-deobfuscator/deobfuscator#113]
Build server 404ing

**Comment by FireMasterK** [comment]
Build it urself

**Comment by Stankye** [comment]
Some people don't always have a build box / jdk with them.

The comment was not very constructive.

The CI link is in the Readme, if it is there, I would hope it would work. Link in question:

https://ci.samczsun.com/job/Deobfuscator/

**Comment by samczsun** [comment]
Closed as the CI is now active
