### ISSUE TITLE
 The code is not deobsfucate

### ISSUE THREAD

**Issue by risas299** [java-deobfuscator/deobfuscator#114]
My startup options
java -jar deobfuscator.jar -input easymaxCore.jar -output easymaxCore-deobf.jar -transformer general.SyntheticBridgeTransformer -path "%java_home%/jre/lib/rt.jar" -path C:\spigot-1.8-R0.1-SNAPSHOT.jar

Error code here
https://prnt.sc/g4ogt2

Please help in advance thanks!!

**Comment by FFY00** [comment]
That error isn't relevant, it's more of a warning than an actual error. The deobfuscated should work as expected. Do you even know what synthetic and bridge modifiers are? If that's a premium spigot plugin the only difference you should notice is that you are able to see the loadConfig0() method on JD-GUI

**Comment by risas299** [comment]
When I deobfuscate it does not decrypt I do not know what to do, do not tell me please

**Comment by risas299** [comment]
And I get the same code that was when I used allatori on this plugin
https://prnt.sc/g4ozw6

**Comment by Janmm14** [comment]
You are not using an allatori transformer in your command line. Then it won't deobfuscate allatori.

**Comment by risas299** [comment]
The code still remains with the inscriptions ALLATORIxDEMO what should I do in such cases? And can this be done without problems?


The fact that the code allatori is not lost can be seen here
https://prnt.sc/g4vsyt

**Comment by risas299** [comment]
It remains to solve the last problem and I can use it help please
https://prnt.sc/g4vwd4

**Comment by risas299** [comment]
Here is the last mistake I found

https://prnt.sc/g4vycr

Pls help

**Comment by LynxIsAWeirdo** [comment]
Deobfuscating "ALLATORIxDEMO" is not possible as the class, method, and field names are irreversible. String literal, synthetic bridge, and other features other than name obfuscation or reversible.

And as for https://prnt.sc/g4vycr : It looks like you are missing a jar that should be in the class path.

**Comment by risas299** [comment]
thanks you helped me all only one more problem failed one method to use who knows help

https://prnt.sc/g4wr37

help please

**Comment by risas299** [comment]
Please answer me

**Comment by FireMasterK** [comment]
JAR? No one here can help you without the jar!

**Comment by risas299** [comment]
I decided but in jd-gui the code still consists of allatorixdemo does not always correctly import!

**Comment by FireMasterK** [comment]
JAR?

**Comment by risas299** [comment]
How to do it in order not to give an error with the method ?

**Comment by FireMasterK** [comment]
Good Luck with getting help without providing the jar!
https://uploadfiles.io/

**Comment by risas299** [comment]
You all helped me thanks!

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
