### ISSUE TITLE
Can you tell me how to use java-deobfuscator?

### ISSUE THREAD

**Issue by Developer9999** [java-deobfuscator/deobfuscator#115]
Help Me Please

**Comment by Janmm14** [comment]
https://javadeobfuscator.com

**Comment by Developer9999** [comment]
But what command do I use to run it?

**Comment by Developer9999** [comment]
Help Janmm14

**Comment by Janmm14** [comment]
The page is showing an example command. Alternatuvely you can look in the source code how the command is parsed.

**Comment by samczsun** [comment]
Closing because this issue is stale. Also, I'm not trying to be elitist, but I don't intend on providing support for people who don't have some form of working knowledge about what they're trying to use this project for
