### ISSUE TITLE
[Suggestion] Generic invokedynamic deobfuscator

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#116]
Since RetroIndy manages to deobfuscate invokedynamic methods into INDY_(number), wouldn't it be possible to create a transformer to decrypt those methods and inject it back into the methods that called them?

This would solve all the problems we have with invokedynamic.

**Comment by FFY00** [comment]
Sorry for my ignorance. What is RetroIndy?

**Comment by ThisTestUser** [comment]
https://github.com/java-deobfuscator/Retroindy

**Comment by ThisTestUser** [comment]
So basically the INDY_<number> methods gets a value from the callsite cache, as shown below:
CALLSITE_CACHE.get(xx)
And then it runs getTarget, which returns MethodHandle.
The objective is to use the MethodHandle and replace the INDY method with this.

**Comment by Bonista** [comment]
@ThisTestUser I did this manually by hand (cancerous) and it worked, so a program is able to do it too. Problem is: who would know how to do it and push the changes.

**Comment by Janmm14** [comment]
retroindy is done to keep program logic as it was as good as possible.
