### ISSUE TITLE
"Enhanced" ZKM String Encryption Not Fully Supported

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#118]
The enhanced string encryption mode for Zelix is pretty much broken when trying to use string encryption transformer.
It does work for some strings, but is pretty much broken at decrypting double integers.
I could send you an obfuscated class (and the source) if you need it.

**Comment by ThisTestUser** [comment]
The zip containing the unobfuscated class and the obfuscated class: 
https://mega.nz/#!qQQlUD6T!ifWS4qcD29KYncg2Gs7KnMF1fTmJ8RrLSD4_1awY1p0

**Comment by Janmm14** [comment]
Buying ZKM to make it useless trough this project? Interesting.

**Comment by FFY00** [comment]
@Janmm14 there are cracked versions avaliable

**Comment by Meylama** [comment]
"Enhanced" ZKM String Encryption is anyways not supported, because it changed entirely in ZKM 9 now.

**Comment by ThisTestUser** [comment]
Do you have something obfuscated with ZKM 9? Maybe then someone will be able to deobfuscate it.
