### ISSUE TITLE
InvokeDynamic Issue

### ISSUE THREAD

**Issue by Bonista** [java-deobfuscator/deobfuscator#119]
Hi, when attempting to deobfuscate: https://ufile.io/cg08b the program is unable to do it, as it contains InvokeDynamic stuff.

I tried using Retroindy because I read that it may deal with that kind of stuff but it left a clusterfuck: https://pastebin.com/3WT6v4Kf

How would anybody here deobfuscate that properly?

**Comment by FireMasterK** [comment]
Deobfuscate it manually

**Comment by ThisTestUser** [comment]
Have you tried the invokedynamic transformer?

**Comment by Bonista** [comment]
@ThisTestUser How would I go about doing that? I'm not too sure how to deal with all these broken strings/characters.

**Comment by ThisTestUser** [comment]
You would need to change up the stringer invokedynamic transformer a bit. It currently only fits for stringer, but with a little modification you can change it to work. You would also need to insert a goto statement that jumps over the anti piracy code, because the anti releak also has tamper protections.

**Comment by ThisTestUser** [comment]
Here's the JAR deobfuscated after you've done that:
https://expirebox.com/download/43efe7fe0c573259e9f207c7a9288e5f.html

**Comment by Someone-NEW** [comment]
Can you launch some link for deobfuscator all in one? and possible has GUI? i am today see some Smoke obfuscation maybe you can add this too for deobfuscate?

**Comment by ThisTestUser** [comment]
Select this deobfuscator when you launch the GUI.
Also, if you want me to deobfuscate Smoke you need to send me the jar, but there's no guarantee I'll be able to deobfuscate it all.

**Comment by Janmm14** [comment]
As far as I know the smoke obfuscator project is currently stopped.

**Comment by Someone-NEW** [comment]
@ThisTestUser can you make some link with your GUI jar file? tnx 
btw ThisTestUser you are the best and friendly tnx for that.

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/deobfuscator-gui/releases
You have to select the deobfuscator.jar you downloaded.

**Comment by Someone-NEW** [comment]
Thank you

**Comment by ItzSomebody** [comment]
@ThisTestUser was that a BlackSpigot or DirectLeaks plugin?

Interesting, are you planning to release a transformer for that?

**Comment by ThisTestUser** [comment]
It would work for both, and thats one of the reasons I'm not releasing it, as well as the fact that they would just update the antireleak.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
