### ISSUE TITLE
Allatori problem

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#120]
If the String decryption methods is in a different Class (or a Different Package)
That String won't got decrypt.
Some Pictures:
http://prntscr.com/g9zos0    (The Class "mjd" has no package)
http://prntscr.com/g9zpp5
http://prntscr.com/g9zq8q

Allatori ver : 6.1demo

**Comment by FireMasterK** [comment]
Thats a method name!

**Comment by CrackFileso** [comment]
MIght the name cause this,But how to fix it

**Comment by Janmm14** [comment]
method names are not real strings and can't be renamed to the original method name

**Comment by CrackFileso** [comment]
I 'm no that mean,The method names got renamed to a Amazing new name.Then the String won't got decrypt.But some String will got decrypted successsfully.
http://prntscr.com/ga40cx

**Comment by ThisTestUser** [comment]
That seems to be a new trick to bypass deobfuscators.

**Comment by Meylama** [comment]
> The method names got renamed to a Amazing new name.

Allatori sometimes uses method and class names as decryption keys...

**Comment by ThisTestUser** [comment]
That's bypassed, because java-deobfuscator spoofs the stacktraces.

**Comment by CrackFileso** [comment]
I trid .But the obfu String doesn't remove.

**Comment by CrackFileso** [comment]
The deobfu method can be detected successfully

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved, preferably with a sample attached in some way
