### ISSUE TITLE
How to  filter classes need to be transformed?

### ISSUE THREAD

**Issue by Tan-Tshunglee** [java-deobfuscator/deobfuscator#122]
If i use a transformer, it apply to all classes in the jar. But I find some open public meaningful names get messed up. Is there some option I can specify to transform those deobfuscated classes. Such as Proguard filter syntax.

**Comment by Janmm14** [comment]
You could create your own transformer which does this, that would be the easiest way.

**Comment by Tan-Tshunglee** [comment]
So how i can start it quickly by some development document?

**Comment by Janmm14** [comment]
there is no such documentation

**Comment by samczsun** [comment]
I've [created](https://github.com/java-deobfuscator/deobfuscator/projects/1) a Kanban board for "documentation". However, I'm also going to close this because it's rather stale now
