### ISSUE TITLE
Deobfuscator.jar

### ISSUE THREAD

**Issue by Someone-NEW** [java-deobfuscator/deobfuscator#123]
Hello all i realy need to know how the heck i can use this with jar i know i only need a jar file but i dont know how to compile it. Will be realy nice to be possible download it here like some other jars on github can but deobfuscator i cant find any .jar for download thank you all for the help.

**Comment by Janmm14** [comment]
Clone the repository and use maven to build the jar (`mvn clean install`)

**Comment by Someone-NEW** [comment]
But wut? i told i cant downlod it enywhere and i dont know do this you say.

**Comment by ThisTestUser** [comment]
http://rgho.st/6QFHZZhqJ

**Comment by Someone-NEW** [comment]
Thank you very much for this, you are the best ;) Its worked thanks

**Comment by ThisTestUser** [comment]
You need to do the -transformer argument multiple times. And for the error above you should redownload the file.

**Comment by Someone-NEW** [comment]
Ok thank you for "redownload the file." you mean a .jar file that are obfuscated? hmm this is one what i need to be deobfuscated

**Comment by ThisTestUser** [comment]
No I mean redownload the deobfuscator.jar if you are seeing the error you posted.

**Comment by Someone-NEW** [comment]
Ow on the same link that you provided here before?

**Comment by ThisTestUser** [comment]
Yes.

**Comment by Someone-NEW** [comment]
Ok i am redownload and i do something more about start i hope this is correct
https://pastebin.com/9EvQQmhG

**Comment by ThisTestUser** [comment]
Then the deobfuscator is outdated. Open a new ticket on github.

**Comment by Someone-NEW** [comment]
Ok thank you you mean New Issue?

**Comment by Someone-NEW** [comment]
Ok i am already open new Issue hope this will be Ok and this go to be Closed thank you.
