### ISSUE TITLE
Deobfuscator.jar Error, outdated!

### ISSUE THREAD

**Issue by Someone-NEW** [java-deobfuscator/deobfuscator#124]
Here is what i use for my test deobfuscate my plugin and i give this Error. Maybe this is Outdated hope you can fix this JAR file
Start https://xxxxxxxxxx
And result: http:xxxxxxxxxx

**Comment by ThisTestUser** [comment]
You probably will need to send the jar file. If allatori has been updated then we need to Jar to identify the problem.

**Comment by Someone-NEW** [comment]
Now i delete this Alatori transformer and run again and result https://pastebin.com/B4ds3eDT

**Comment by ThisTestUser** [comment]
There is no allatori string encryption in the file. The file is already unobfuscated.

**Comment by Someone-NEW** [comment]
Are you sure ok than i will test another one ;)

**Comment by Someone-NEW** [comment]
Yes i am edit it above jar file and all looks that this is obfuscated 1 and the second link above are obfuscated.

**Comment by ThisTestUser** [comment]
Its the BlackSpigot anti-releak.

**Comment by Someone-NEW** [comment]
I think thats right but how to remove this? i think there are some obfuscation too? You can PM me but will be cool to solve this here thanks

**Comment by Someone-NEW** [comment]
Can you add this on Deobfuscation that can be detect this and removed? ow is nor readable. Ijust want to have my files to be clean, i dont like this infected files and when im banne or whatever i can use this free again. I just need by my self to be clean without any unnecesarys like this obfuscation/anti-bla.. ;D thank you i hope you can help.

**Comment by FireMasterK** [comment]
Where is the obfuscation? I only see invoke dynamic obfuscation left

**Comment by FireMasterK** [comment]
I am gonna modify retroindy to remove invoke dyns
I won't be releasing it but if you want me to remove invoke dyns, send me the jar

**Comment by ThisTestUser** [comment]
http://www.mediafire.com/file/8w1nmbmjokm7cr2/YouTubeBridge-1.5.3_3.jar
http://www.mediafire.com/file/tx1cv5o4z0ocx0o/AuctionGUIPlus-1.2.12.jar

**Comment by Someone-NEW** [comment]
Hm your the best can you somehow release for this? This will be so help me i need it for my self to be more free to use etc you can PM me somehow.
PS: this links you pasted have removed this tricky problem?

**Comment by Someone-NEW** [comment]
Hey is there something new?
PS: you have ZKM 9.0.2? i have one but is not cracked when you need it i can send you.

**Comment by ThisTestUser** [comment]
Would you be able to send that to me? I could crack it for you but if someone else downloads it they might report it to the authors.

**Comment by Someone-NEW** [comment]
Yes i will send, no problem, i hope you can crack it and i hope you can help me about this anti-releak etc.
Here is the link https://www.dropbox.com/s/8u2jim8eh7lk2wg/ZKM%209.0.2.zip?dl=0
We can delete after process is complete.

**Comment by ThisTestUser** [comment]
You can delete it now if you don't want anyone else to download it.

**Comment by Someone-NEW** [comment]
I am deleted but you can publish it cracked when you want.

**Comment by Someone-NEW** [comment]
Hey how is with your ZKM and deobfuscator now?

**Comment by Janmm14** [comment]
I can fully understand the usage of this deobfuscator to see what certaib plugins are doing.

**But I think nobody should use this deobfuscator to remove antireleak/antipiracy stuff!**

Some people do need the money they get of their plugins.
Many server owners are getting more than enough money through their shop, so they can spend a little bit of that money to purcharse plugins to enhance their server.
Other people might not have that money, they can use the wide range of free plugins out there or even use Skript or Java to create their own stuff.

So please do not publish any (modified) plugin you purcharsed on spigotmc.

**Comment by ThisTestUser** [comment]
@Someone-NEW I don't have much time to try to crack it, it looks like you have to try something else.
And for the piracy thing you're right, deobfuscator is made so you can reverse engineer software, not redistribute.

**Comment by Someone-NEW** [comment]
Ok cool i will just wait no problem. i aggre with you about "not redistribute." all i need for my home hobby things and my server i have just free to use and having no problem about all for me just like that i like to do something by my self in that case i need this not for redistribute etc. thanky i will wait.

**Comment by Someone-NEW** [comment]
@Janmm14 I have my own purchased plugins and all what i doo is for my hobby server its not a public is currently only a Hobba and Private.
"So please do not publish any (modified) plugin you purcharsed on spigotmc.!" lol I understand this i know.

I dont use only their plugins, but DirecLeaks and BlackSpigot leaked plugins, all this sites uses Official plugins from Spigot but what i will is only for me to have clean plugins just like that for HOBBY i hope you can understand this thank you.

**Comment by ThisTestUser** [comment]
Download the plugins again, BS no longer has those invokedynamic calls.

**Comment by Janmm14** [comment]
Probably they removed the stuff because BS is bs.

Hmm yeah, I want to play football as hobby and I do not earn any money with that, so I am allowed to steal this football from the shop? @Someone-NEW

**Comment by Someone-NEW** [comment]
@Janmm14 Actualy i have conversation with ThisTestUser so.
All links i push here i am deleted than.

**Comment by Janmm14** [comment]
@Someone-NEW All the links you published here are atill working. Stop lying.

Additionally you seem to have nothing to answer about my comparision. Better stop this then please.

**Comment by Someone-NEW** [comment]
@Janmm14 please no one ask you for anything so stfu.. I just comunicate with person i am say before. Here i am delete link but now i will check this by me too.

**Comment by Janmm14** [comment]
@Someone-NEW: "Uh oh I do not have any valid argument left why I am using leaks except I do not care about others"


And I won't stfu.

**Comment by Someone-NEW** [comment]
Why you than answer everywhere when i see that you everywhere dont want help other peoples? than better stfu

**Comment by Someone-NEW** [comment]
This comes out from theme. and Janman14 14 year old kid that answers while dont want help other peoples.
So Close this threat or delete.

**Comment by Janmm14** [comment]
I am not 14, but 20 and you are the kid who believes that the money of others is growing on trees.

**Comment by Someone-NEW** [comment]
Yeah anyway KID sorry

**Comment by Janmm14** [comment]
You are not answering to my statement.

Even if I would not help out a little without recieving any money at AAC, I would argue the same.

**Comment by Someone-NEW** [comment]
Out of theme

**Comment by Someone-NEW** [comment]
i say again out of theme
