### ISSUE TITLE
Possible Deobfuscator-GUI Intergration?

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#125]
So I'm pretty much done with the GUI I created with deobfuscator.jar, as you can see here:
https://github.com/ThisTestUser/deobfuscator-gui
The problem it is that you currently have to select the deobfuscator.jar, and I think that integrating it into the main jar would be much better.
Any suggestions for this?

**Comment by FFY00** [comment]
As the code is licensed under  Apache License 2.0, you can distribute the jar with your program, so there's no need for manually selecting deobfuscator.jar.

**Comment by samczsun** [comment]
@ThisTestUser If you would like, I can add you as a member of this organization, where you can maintain the GUI as a separate repository

**Comment by ThisTestUser** [comment]
Yeah, I'm okay with that.

**Comment by samczsun** [comment]
Invitation sent
