### ISSUE TITLE
Possible to integrate Class SourceFile Renamer for classes which source file names aren't obfuscated?

### ISSUE THREAD

**Issue by lvsth** [java-deobfuscator/deobfuscator#126]
For example a jar obfuscated with ProGuard but SourceFile attribute is still there and you could easily read and deobfuscate it.

**Comment by FireMasterK** [comment]
https://github.com/FireMasterK/deobfuscator

**Comment by FireMasterK** [comment]
Jar available at : https://github.com/FireMasterK/deobfuscator/releases/tag/1.0.6
https://github.com/FireMasterK/deobfuscator/releases/tag/1.0.6

**Comment by FireMasterK** [comment]
@lvsth close?
