### ISSUE TITLE
Renaming capabilities

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#13]
It might be really useful if some basic renaming capabilities could be implemented. Then it should also output what has been renamed exactly.

Method renaming - rename ambiguous methods by for example appending the return type to the method name
Class renaming - rename classes so they don't collide with member names by adding a prefix.

**Comment by Fireflies** [comment]
Somebody could whip up an SRG patch applicator for this, might be possible to use existing tools such as SpecialSource.

**Comment by Janmm14** [comment]
SpecialSource requires manual input of rules as far as I am aware of, so I'd like to have this automated. I think this project is a possible aim of this automation.

**Comment by Fireflies** [comment]
You simply give it a file which tells it what to rename things to. I would say this feature is better for a Helios plugin that utilises this deobfuscator though, a deobfuscator should simply deobfuscate and there's nothing hugely obscure about this. Just my thoughts though.

Perhaps put together a PR if it's worth it?
