### ISSUE TITLE
ZKM 9 (Link fixed)

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#131]
http://www.mediafire.com/file/48o478udhs7rg4g/ZKMEval.zip
leak by me
(But it's a Eval version)
Fixed:
https://mega.nz/#!uUgliZKL!T-WSPggociu5nUgjh3ROcPTHW19OQF_Lzx8YoTXL6Zo

**Comment by koxu1996** [comment]
"File Removed for Violation". Could you upload it http://mega.nz?

**Comment by Janmm14** [comment]
Better do not upload it at all since you are stealing.

**Comment by CrackFileso** [comment]
https://mega.nz/#!uUgliZKL!T-WSPggociu5nUgjh3ROcPTHW19OQF_Lzx8YoTXL6Zo
ReUploaded

**Comment by ThisTestUser** [comment]
Well, it looks like the Zelix authors check this regularly.

**Comment by ItzSomebody** [comment]
@CrackFileso instead of leaking it, just obfuscate a reasonably sized open-sourced Java project and post it with the ZKM 9

**Comment by ThisTestUser** [comment]
ZKM 9's string encryption is just as good as ZKM 8's, so there's no need for that.

**Comment by FireMasterK** [comment]
[https://files.fm/f/8gqqqqp3](url)
The filename is `!     §4Cheat§8Breaker §7[128x] §rPack.zip`
Password: `ThisIsNotZkm`

**Comment by ThisTestUser** [comment]
Obfuscate something with Zelix 9 and then Zelix 8, and you will find no difference.

**Comment by ItzSomebody** [comment]
I don't have Zelix 9 though rip

**Comment by ThisTestUser** [comment]
But still, it doesn't matter. Just use cracked Zelix 8 to get a demo of zelix.

**Comment by FireMasterK** [comment]
Oh ok

**Comment by ThisTestUser** [comment]
And besides, leaking Zelix 9 is useless anyways, because it only supports the pro-obfuscation community.
If you really want someone to decrypt Zelix, just post the obfuscated JAR.

**Comment by ItzSomebody** [comment]
[Zelix.zip](https://github.com/java-deobfuscator/deobfuscator/files/1342659/Zelix.zip)

Here is one of my Spigot plugins with various obfuscations by Zelix, have fun with it.

**Comment by FireMasterK** [comment]
Wow string obfuscation is that simple? I think the flow obfuscation really confused me.... Ima make a deobfuscator later this week

**Comment by ThisTestUser** [comment]
The flow obfuscation is simply fake methods/fields injected to add a bunch of illegal jumps.

**Comment by Janmm14** [comment]
I have seen the fake field stuff for "illegal" jumps already in the obfuscation of the ZKM 5 leak, however the ZKM 5 leak itself did not added that as far as I recall (its probably > 1 year ago)

**Comment by LynxKik** [comment]
Can someone hmu with the zelix link I am late this is my discord Rab
#4758

**Comment by THEREALWWEFAN231** [comment]
any new links?

**Comment by fikawka** [comment]
Give new link

**Comment by Janmm14** [comment]
do you really expect the zkm devs not watching and instantly dmca'ing this repository anymore?

**Comment by awesomennguy** [comment]
reupload please

**Comment by Janmm14** [comment]
@awesomennguy you don't want to understand that it will not happen. i will personally write to zkm just because of you if i see a leak here

**Comment by koxu1996** [comment]
I will not give you link, but I can provide obfuscated samples.

**Comment by iuczony** [comment]
go reupload

**Comment by ItzSomebody** [comment]
_GitHub: the leak site. /s_

**Comment by Janmm14** [comment]
voting for lock
