### ISSUE TITLE
Obfuscating a Client

### ISSUE THREAD

**Issue by Michael1954** [java-deobfuscator/deobfuscator#136]
Am trying to deobfuscate a client for Minecraft that uses ALLATORIxDEMO and am getting this error 
https://hastebin.com/ihojomasay.vbs

from reading other's issues, I believe am missing a "Classpath"/Jar file. I have already added the rt.jar
this is my command line - 
https://hastebin.com/anogulohez.tex

I also tried using the GUI version of this, and I get the same error.

Thank you <3

**Comment by ItzSomebody** [comment]
Add the needed libraries to the path

**Comment by Michael1954** [comment]
Which libraries? 
Thanks.

**Comment by Michael1954** [comment]
Alright, I figured out which libraries I needed, but now I get this error -
https://hastebin.com/emiruyuzeb.pl

**Comment by ItzSomebody** [comment]
Try @ThisTestUser's fork

**Comment by Michael1954** [comment]
Do you think you can compile it for me :P <3

**Comment by ThisTestUser** [comment]
https://github.com/FireMasterK/deobfuscator/releases

**Comment by Michael1954** [comment]
@ThisTestUser Thats the one I been using :/ https://prnt.sc/grqr7q
You think you can compile yours and upload it to the Releases?

**Comment by ThisTestUser** [comment]
That JAR has the updated Allatori transformer already, so you need to send the JAR for me to help you.

**Comment by Michael1954** [comment]
Do you have discord or something I can send you the file through?

**Comment by ThisTestUser** [comment]
https://discord.gg/FxmTcM

**Comment by Michael1954** [comment]
Joined it

**Comment by ThisTestUser** [comment]
Since the latest Allatori deobfuscator by me fixes this, you can close this now.
