### ISSUE TITLE
CI link not working

### ISSUE THREAD

**Issue by FireMasterK** [java-deobfuscator/deobfuscator#140]
EDIT: Its only in the build status link at README.MD#L1
Maybe you had set the link by accident to : 
`https://ci.samczsun.com/job/java-deobfuscator/Deobfuscator` 
instead of 
`https://ci.samczsun.com/job/java-deobfuscator/job/Deobfuscator/`

**Comment by samczsun** [comment]
Oh, looks like the build tag plugin doesn't handle folders nicely
