### ISSUE TITLE
Javari Obfuscator 

### ISSUE THREAD

**Issue by helloxdd** [java-deobfuscator/deobfuscator#153]
there is an obfuscator opensource named javari, this cant obfuscate javari stringencryption
sourcecode: https://www.youtube.com/watch?v=9U2CepBmM0w

**Comment by ItzSomebody** [comment]
Seems like a not-so-well known obfuscator. Additionally, since you have source code making transformers should be easy.

**Comment by FireMasterK** [comment]
Dude its legit skidsuite 2....

**Comment by FireMasterK** [comment]
It's a skidded obfuscator

**Comment by ItzSomebody** [comment]
LOL

**Comment by helloxdd** [comment]
i dont care if its skidded/or other things, i said only that this javadeobfuscator dont obfuscate it

**Comment by samczsun** [comment]
If you absolutely need to deobfuscate it, use the skidsuite2 transformers. I'm not copy/pasting the entire thing or renaming it just for this
