### ISSUE TITLE
Failed Please Check

### ISSUE THREAD

**Issue by xiaonian233** [java-deobfuscator/deobfuscator#163]
![image](https://user-images.githubusercontent.com/21072615/31858064-1047d99e-b721-11e7-92d9-02a587bfb3a3.png)

**Comment by ItzSomebody** [comment]
Is this with deobfuscator-gui?

**Comment by samczsun** [comment]
This just needs a change to jvmprovider. Will address later

**Comment by samczsun** [comment]
And one month later it's been addressed! Just need to work on the timing a bit...
