### ISSUE TITLE
Won't deobfuscate

### ISSUE THREAD

**Issue by OujiaBoard** [java-deobfuscator/deobfuscator#164]
So I run the bat to deobfuscate it then it said input isn't a option

**Comment by ItzSomebody** [comment]
An exact error would be nice.

**Comment by FireMasterK** [comment]
The CLI was removed, use a config file and use the command
`java -jar deobf.jar -c config.yml`

**Comment by samczsun** [comment]
Yes, config files are the way to to now. Take a look at the readme for an example
