### ISSUE TITLE
Dummy classes can be used to prevent deobfuscation

### ISSUE THREAD

**Issue by konsolas** [java-deobfuscator/deobfuscator#17]
Since the deobfuscator tries to deobfuscate every single class regardless of whether it is loaded by the application, one can insert a dummy class that implements "some/random/Thing", and the deobfuscator will fail on the class and not deobfuscate the rest of the jar.

**Comment by Janmm14** [comment]
you could manually remove any classes where you get such issues

**Comment by konsolas** [comment]
This was the result of a 5 minute test. One could easily make it more elaborate and unclear which classes were dummies. There are probably also other vulnerabilities with random classes that I haven't tested.

"You could remove the classes manually"
Therefore:
"You could remove the string encryption manually"
"You could normalize the names manually"
"You could undo flow obfuscation manually"
...?

**Comment by Janmm14** [comment]
Well I see your point and I did not want to decline your issue. I just wanted to show up a practical way of circumventing the issue as I think that its easy in this case.
