### ISSUE TITLE
deobfuscation failed

### ISSUE THREAD

**Issue by Kiwis2451** [java-deobfuscator/deobfuscator#170]
[Image](https://imgur.com/wWD0UAf)

`java -jar deob.jar -input NeedDEOB.jar -output doneDEOB.jar -transformer smoke.StringEncryptionTransformer -path "C:\Users\Bao\Desktop\New folder\rt.jar" -path "C:\Users\Bao\Desktop\New folder\jce.jar" -path "C:\Users\Bao\Desktop\New folder\jfxrt.jar" -path "C:\Users\Bao\Desktop\New folder\spigot.jar"
`

pls help me , I did something wrong ???

**Comment by Janmm14** [comment]
Usage changed. You now need to create a config file.

**Comment by FireMasterK** [comment]
The CLI was removed, use a config file and use the command
`java -jar deobf.jar -c config.yml`
