### ISSUE TITLE
NPE with Zelix String Encryption Tarnsformer

### ISSUE THREAD

**Issue by SebastianAgius** [java-deobfuscator/deobfuscator#173]
I have this error/stacktrace here https://hastebin.com/kuworirimu.rb.
The transformer I used was `zelix.StringEncryptionTransformer` 
The jar I'm trying to deobfuscate is https://www.spigotmc.org/resources/phoenix-anti-cheat.6207/download?version=189445 
It has a few dependencies so not sure if you'll get class not found errors.

**Comment by ThisTestUser** [comment]
[PACDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1464734/PACDeob.zip)

**Comment by Janmm14** [comment]
useless to deobfuscate that plugin

**Comment by FireMasterK** [comment]
Only 1 good check lol

**Comment by samczsun** [comment]
Seems like this is resolved
