### ISSUE TITLE
not deobfuscating [Private deobfuscator i think]

### ISSUE THREAD

**Issue by sennyy** [java-deobfuscator/deobfuscator#179]
hi, im trying all the transformer but the stringencryption of this jar is still not removed Please staff help me!!!!
http://www46.zippyshare.com/v/01SFaa8b/file.html

@ThisTestUser 
@samczsun

**Comment by ThisTestUser** [comment]
[inputDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1540707/inputDeob.zip)
Rename to jar

**Comment by samczsun** [comment]
In the future, please also attach the config file you used. For future reference, this is obfuscated with Zelix (probably 8 or 9) and Stringer 3 so you should be good with `stringer.v3.StringEncryptionTransformer` + `stringer.v3.InvokedynamicTransformer` + `stringer.v3.HideAccessTransformer` + `zelix.StringEncryptionTransformer`
