### ISSUE TITLE
how to i add this when deobfuscating..

### ISSUE THREAD

**Issue by sennyy** [java-deobfuscator/deobfuscator#180]
how i add the patch when deobfuscating? i have the config.yaml i done all good, but when i start the deobfuscator it says Have you added the necessary files to the -path argument? 
but i dont know how to add the library..

file: http://www66.zippyshare.com/v/dHsGtXTC/file.html
its obfuscated with zkm 8-9 and stringer 3 if you can obfuscate this for me thanks. and i love you

@ThisTestUser 
@samczsun

**Comment by sennyy** [comment]
btw the file is the new version not the old of the old post

**Comment by ThisTestUser** [comment]
[inputDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1544328/inputDeob.zip)

**Comment by sennyy** [comment]
@ThisTestUser can you crack it too? theres like a login and the main window, can you do that it go directly to the main window? plss

**Comment by Janmm14** [comment]
this platform is not meant to ask and share cracked content I'd say

**Comment by sennyy** [comment]
ok thanks, what about the path? how do i set-up it @Janmm14

**Comment by ThisTestUser** [comment]
You should use bytecode viewer to search the string called "Login".
Using this method, you can see that a/a/a/a/c.class determines the login, with private void c() determining the login (new a.a.a.b.d(var4.a);) and protected void b() adding the buttons.
Since I don't know much about the program I'm not going to crack it, but this should be enough to crack it.

**Comment by sennyy** [comment]
so practically, in the private coid c(); (a/a/a/a/c.class) i can delete all the Initialization Failed! shit and remain only where the new window get called (   new a.a.a.b.d(var4.a);
)

**Comment by sennyy** [comment]
@ThisTestUser just tried, deleted things in a/a/a/a/c.class for remain where the main window get called , all ok but now it doesnt open anymore

**Comment by Janmm14** [comment]
simply deleting stuff doesn't crack a program

**Comment by ThisTestUser** [comment]
There's probably no way to crack it anyways, because the program depends on a valid key sent to the server.

**Comment by sennyy** [comment]
what about going direct to the main window and not to the login window? idk where it get called so i can change it

**Comment by ThisTestUser** [comment]
You could, but nothing would work, or the program will crash.

**Comment by sennyy** [comment]
oh rip

**Comment by ThisTestUser** [comment]
That's because the application can only work if your server is registered. If you're trying to "crack" it to get it free licence for your server, you're out of luck.

**Comment by samczsun** [comment]
Closing and locking (and purging) this because deobfuscation is one thing, but actively discussing how to bypass license checks is a whole different story
