### ISSUE TITLE
ZKM9.0.2E Not Support

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#190]
File:
https://mega.nz/#!KNIg1ZDD!rvU7BllOLATOk3psPsmIwhhOrmQwMzuGoyMeH98PILI

**Comment by samczsun** [comment]
This is ZKM 9? Weird...

**Comment by CrackFileso** [comment]
Obfu with ZKM9

**Comment by CrackFileso** [comment]
http://prntscr.com/hx4f7i

**Comment by samczsun** [comment]
Try the new transformer, `zelix.string.SimpleStringEncryptionTransformer`. Also, try the detection feature and see if it works for other samples
