### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Quantum64** [java-deobfuscator/deobfuscator#191]
What is the timeline for ZKM 9 method parameter change string encryption support?

**Comment by samczsun** [comment]
I've got a version in the works but there's some issues to be worked out. If you have a sample I'd be happy to take a look, since I don't have too many to work with right now.

**Comment by Quantum64** [comment]
Nothing that I can share, sorry.

**Comment by Quantum64** [comment]
@samczsun I don't see any transformers for reversing ZKM control flow obfuscation. Is this possible?

**Comment by samczsun** [comment]
It's in consideration. I'd have to see if I even have samples with flow obfuscation lying around
