### ISSUE TITLE
Detection system doesn't work

### ISSUE THREAD

**Issue by liovy** [java-deobfuscator/deobfuscator#192]
Hello,

When I wanted to detect transformers (following instructions), with the good config.
It return me this error: 
> java -jar deobfuscator.jar --config detect.yml
> [main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An output JAR must be specified

Here's my config file (detect.yml):
> input: obfuscated.jar
> detect: true

**Comment by Moonfield** [comment]
It happen to me too I can confirm it's a bug.

**Comment by samczsun** [comment]
Detection was added on a whim. Forgot about the output jar check. Will fix later

**Comment by st4ycool** [comment]
Same here. Waiting for the fixxx

**Comment by samczsun** [comment]
As a temporary fix you can just specify some random output. I'll fix this tonight if I remember

**Comment by ryantheleach** [comment]
FYI, specifying an output results in "At least one transformer must be specified"

**Comment by liovy** [comment]
Yeah, I've the same problem but I think we should wait for fix @ryantheleach :)

**Comment by samczsun** [comment]
Sorry, seems I've caught the flu yesterday. I've pushed a commit
