### ISSUE TITLE
Error when trying to use Stringer transformer

### ISSUE THREAD

**Issue by yumitsu** [java-deobfuscator/deobfuscator#195]
Good day. I tried to deobfuscate a jar obfuscated by stringer > 3.0, but it fails on OS X with following backtrace:
https://gist.github.com/fde8f1ae6b732caa5e257f6dd5e083f3

Looks like it uses SunMSCAPI provider, which is Windows specific. 

```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

**Comment by samczsun** [comment]
Yeah. Saw it happening on a Ubuntu box too. Problem is I don't have a good way of quickly testing osx/linux java versions. You could try manually downloading a sunmscapi.jar (I don't remember whether it has any native methods). Supporting osx/linux is on my to-do list.

**Comment by samczsun** [comment]
Actually, a very very very quick test seems to suggest those jars aren't even needed. I may have left them in because I was too lazy to check whether they were necessary. I've removed them for now. Try the latest build and if anything fails to deobfuscate please open a new ticket
