### ISSUE TITLE
Deobfusucater stuck

### ISSUE THREAD

**Issue by NewUser1234321** [java-deobfuscator/deobfuscator#196]
Hello, I'm trying to deobfuscate an obfuscated A Minecraft server Plugin jar with ZKE SimpeStringEncryptionTransformer, But the Deobfuscator stuck at 
`[Filesystem] Getting boolean attributes of C:\Program Files\Java\jre1.8.0_151\lib\security\java.security (C:\java_home_dir\lib\security\java.security)
[Filesystem] Opening C:\Program Files\Java\jre1.8.0_151\lib\security\java.security (C:\java_home_dir\lib\security\java.security) for reading
`
It has been going for an hour now.

**Comment by ThisTestUser** [comment]
You have to send the JAR file.

**Comment by NewUser1234321** [comment]
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/1648614/Plugin.zip)

**Comment by Quantum64** [comment]
Unfortunately ZKM flow obfuscation cannot currently be reversed. I've been painstakingly reverse engineering a ZKM 9 enhanced string + multiple layers of flow obfuscation for over a week now. D:

**Comment by NewUser1234321** [comment]
It is almost a month for me, I tried from Reverse Engineering from the Low-Level language to the ZKM obfuscator itself :(,

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1649345/PluginDeob.zip)

**Comment by NewUser1234321** [comment]
Thank you, sir, I was suspicious with the Plugin may relate to Breach attempt at My server, But May I ask what method you use? I need to deobfuscate the Original one that has my Spigot ID.

**Comment by Janmm14** [comment]
@NewUser1234321
no, you do not need to deobfuscate your original then. it shouldnt have different code?!
Also it looks like you are too sceptical about  premium plugins in general. if you buy them and you give them money, they have no reason to breach your server.

**Comment by NewUser1234321** [comment]
No, I don't have any real evidence for now as our Security Plugin was disabled by force by Unauthorized Source before the Breach Happen, According to The Log, The Source called the PluginManager to Disable Our Security Plugin, so it must be From one of the Plugin as Command can't do it. That's why we need to Deobfuscate and Decompile our All of Our Installed Plugins, Including our own Plugin. My Experience that Some of "Nulled" or "Cracked" Plugin had their Original AntiPiracy Stripped, I may be too skeptical, Knowing that Spigot rules don't allow AntiPiracy code to contain harmful code,

**Comment by Janmm14** [comment]
You maybe want to output a stack trace in onDisable in that case?

**Comment by Quantum64** [comment]
@ThisTestUser What transformers did you use?

**Comment by ThisTestUser** [comment]
If you input the fake fields manually, its easy to write a transformer that clears all the flow obfuscation
