### ISSUE TITLE
Deobfuscation stuck on ZKM9 try

### ISSUE THREAD

**Issue by i0xHeX** [java-deobfuscator/deobfuscator#208]
Tried to run deobf on zkm 9 eval, but on Zelix String Tranformers it stucks and doesn't do anything.
Log:
_[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer_
... waited for 10 minutes, nothing changed.

Tried both simple and enchanced. I know that (III) pattern not currently supported, but why it simply stucks at that? Used build 54.
Code:
https://hastebin.com/alifuqirev.cs

**Comment by Janmm14** [comment]
sample likely required

**Comment by i0xHeX** [comment]
https://www.dropbox.com/s/y086tbkugq4j46o/ZKMEval.jar?dl=0

**Comment by ItzSomebody** [comment]
ZKM 9 has Method parameter change and Java-deobfuscator looks only for (II)Ljava/lang/String;

Plus that file is huge and JavaVM is a little slow.

**Comment by ItzSomebody** [comment]
Since the hastebin has expired (meaning, what information we had is now lost), I'll close this for now. Feel free to reopen if you have any extra information that we could use. :)
