### ISSUE TITLE
Deobfuscated Jar Won't Run

### ISSUE THREAD

**Issue by Ringwid** [java-deobfuscator/deobfuscator#209]
Hi, I'm trying to deobfuscate a Bukkit plugin but the generated jar won't run. 

Here's the stacktrace:
```
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location: SomeGarbledStaff.b(Z)V @1006: getfield
  Reason:
    Type 'org/bukkit/scheduler/BukkitRunnable' (current frame, stack[0]) is not assignable to 'SomeGarbledStaff.Class'
```

[Here](https://pastebin.com/KJRLpnsA)'s a full version.

I've switched the order of the transformers and tried different combinations, but nothing helped. Finally, after testing all the transformers one by one, I found out the problem is irrelevant to the transformer. No matter what transformers were used, the problem still exists. Then I viewed the decompiled code of the class that BukkitRunnable is "not assignable to", but the class seemed perfectly normal and extends the BukkitRunnable class. I know little about Java bytecode, but I suspect that the problem originates from the detailed handling of generating the new bytecode.

What I was trying to do is to inject some API to the plugin, but the Zelix obfuscated jar left me with no chance. I couldn't provide the plugin because it's proprietary, though I know it's difficult to help without it. I sincerely ask for some suggestions.

Thank you in advance.

**Comment by samczsun** [comment]
Deobfuscation isn't intended to produce a JAR which passes validation. It's nice to have and I try to do it when possible, but sometimes it's just too much of a hassle. Zelix in particular is pretty annoying to handle.

Why do you need to run the deobfuscated jar? If it's a reasonable... reason... I'll add making the jar verify to my todo list but if it's just for the sake of running the jar then I don't see much point

**Comment by define-evil** [comment]
Thanks for replying. I want to add some custom api and events to the deobfuscated jar by adding and modifying the bytecode, which is not possible if the jar is obfuscated. However, a jar that won't run will defeat the purpose.

**Comment by Janmm14** [comment]
Did you asked the author before?

**Comment by define-evil** [comment]
Yes, but no luck.

**Comment by samczsun** [comment]
Hmm... That's unfortunate, but making the JAR run is not a big concern of mine right now (especially when ZKM 9 isn't even supported yet). It'll be a while until I can find time to work on this. Your best bet apart from manually fixing the JAR is waiting for someone else to open a PR for this

**Comment by define-evil** [comment]
Sorry I messed up with my accounts. How can I manually fix the jar?

**Comment by sowbener** [comment]
It would be some of the most requested features, also for debugging purposes.

**Comment by FireMasterK** [comment]
Use -noverify in the server's jvm arguments
