### ISSUE TITLE
Errors while deobfuscating using zelix!

### ISSUE THREAD

**Issue by RTGOHARDG** [java-deobfuscator/deobfuscator#221]
Error:

https://pastebin.com/xCEJSTbm

config:

`transformers:
  - com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.FlowObfuscationTransformer`

File that i try to deobfuscate:

[Bot.zip](https://github.com/java-deobfuscator/deobfuscator/files/1822574/Bot.zip)

and no, i'm not trying to bot a server or something like that (remove blacklist etc). i wan't to know how it works so i can try to improve my plugin. thanks!

**Comment by ItzSomebody** [comment]
Looks like you have a jar which has Zelix 5, lol. Dump this into jbyteedit and hit "Decrypt ZKM strings"

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/1858188/output.zip)

Here is most of zelix removed.

**Comment by RTGOHARDG** [comment]
Thanks!
