### ISSUE TITLE
Error: java/lang/Object could not be found while writing .... Using COMPUTE_MAXS

### ISSUE THREAD

**Issue by belfagoor** [java-deobfuscator/deobfuscator#222]
Error details

"C:\Program Files\Java\jdk1.8.0_111\bin\java" -Xss512m -jar deobfuscator-1.0.0.jar --config config.yml
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - I was unable to back up the previous output JAR
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 1409 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
_**Error: java/util/Enumeration could not be found while writing it/rgi/passpro/api/Copertura. Using COMPUTE_MAXS
Error: java/sql/SQLException could not be found while writing it/rgi/passpro/api/QryCalendario. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing it/rgi/passpro/api/Bene. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing it/rgi/passpro/api/PPCustomPropCache. Using COMPUTE_MAXS
Error: java/sql/SQLException could not be found while writing it/rgi/passpro/api/Cedola. Using** COMPUTE_MAXS_

**Comment by ThisTestUser** [comment]
Attach rt.jar as a library.

**Comment by marcossapp** [comment]
How do I do this?

**Comment by ThisTestUser** [comment]
By adding the below 2 lines to config.yaml:
path: 
  - c:\Program Files\Java\jre1.8.0_144\lib\rt.jar

**Comment by bonsko** [comment]
Can I get your discord id, please? @ThisTestUser

**Comment by ItzSomebody** [comment]
Old issue and it seems like the issue has been resolved. Closing.
