### ISSUE TITLE
Error on write file

### ISSUE THREAD

**Issue by marcossapp** [java-deobfuscator/deobfuscator#223]
Hi, I am using stringer.StringEncryptionTransformer for decompile a jar with encrypted strings. It says:

Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 1139 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Done 40%
[Stringer] [StringEncryptionTransformer] Done 50%
[Stringer] [StringEncryptionTransformer] Done 60%
[Stringer] [StringEncryptionTransformer] Done 70%
[Stringer] [StringEncryptionTransformer] Done 80%
[Stringer] [StringEncryptionTransformer] Done 90%
[Stringer] [StringEncryptionTransformer] Done 100%
[Stringer] [StringEncryptionTransformer] Decrypted 1139 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 18 decryption classes
[Stringer] [StringEncryptionTransformer] Done

But in the end says

Error: com/mobile/new/app/http/HttpResponse could not be found while writing com/mobile/new/app/http/HttpService. Using COMPUTE_MAXS
Error: com/google/android/gms/location/FusedLocationProviderClient could not be found while writing com/mobile/new/app/location/SingleLocationRequest. Using COMPUTE_MAXS
Error: com/google/android/gms/location/GeofencingRequest$Builder could not be found while writing com/mobile/new/app/locationmanager/geofence/a. Using COMPUTE_MAXS

So one class which is in jar already cannot be found? How so?

And about this other google class, does anyone know how to solve?

**Comment by ThisTestUser** [comment]
You can usually ignore this, but if you want you have to try to find which library it is.

**Comment by marcossapp** [comment]
Ok, but importing the original and the deobfuscated jars and comparing them in eclipse some class are removed and they were important I guess. I decompiled using fernflower and in classes there are things like:

com.app....settings.a.c("⬡\ude7cﲋ욼Ʒ\uef39蠚\ueaba秚\ue3a3ᨸ㦠ഺ붣䔷袝篁")

Using fernflower I saw it was something like settings.a.c( settings.a.g("encrypted_string")) before use deobfuscator, so probably only part was done.

Which means the string is still obfuscated and I was thinking in use reflection to try get the original string using the method a.c() However the class settings.a does not exists in imported jar in eclipse project.

**Comment by marcossapp** [comment]
And about Ignore the error  _Error: com/mobile/new/app/http/HttpResponse could not be found while writing com/mobile/new/app/http/HttpService._ the HttpResponse does not exists in new jar (generated from deobfuscator)

**Comment by ThisTestUser** [comment]
That's because HttpResponse didn't exist in the original jar.

**Comment by marcossapp** [comment]
But it exists! That's why I could not understand this error.

![image](https://user-images.githubusercontent.com/34035271/37713446-c1272a54-2cf5-11e8-9d94-3bb06c866af2.png)

**Comment by marcossapp** [comment]
Here, the original one and the deobfuscated

[files.zip](https://github.com/java-deobfuscator/deobfuscator/files/1833918/files.zip)

**Comment by ThisTestUser** [comment]
I'm going to try myself, but it seems that com/mobile doesn't exist in the jar.

**Comment by ThisTestUser** [comment]
[deobfuscated.zip](https://github.com/java-deobfuscator/deobfuscator/files/1834227/deobfuscated.zip)
It seems that you have to prevent the classes from being deleted the first time.

**Comment by marcossapp** [comment]
Perfect!

**Comment by marcossapp** [comment]
Just for curiosity, what did you do to get this working properly?

**Comment by Janmm14** [comment]
Transformers can be set to not remove potential decryption classes in the config.

**Comment by marcossapp** [comment]
Ok but where I can find this instruction? Is there a command line example for this setting?

**Comment by marcossapp** [comment]
I want to understand what was done to reproduce here

**Comment by ThisTestUser** [comment]
https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/stringer/StringEncryptionTransformer.java#L99
Just delete this section there and compile.

**Comment by marcossapp** [comment]
Now I see! Thanks.
