### ISSUE TITLE
Allatori trash String & Allatori new String obfu

### ISSUE THREAD

**Issue by Mysels** [java-deobfuscator/deobfuscator#226]
http://prntscr.com/j21dbs
https://ghostbin.com/paste/e8jcp
(In new Allatori version I think)

**Comment by ThisTestUser** [comment]
The trash string is caused by the new Allatori transformer. You can send the obfuscated Jar if you want no trash strings.

**Comment by ItzSomebody** [comment]
@AnnaDev24 it's caused by the new Allatori transformer which uses JavaVM

ldc "EncryptedString"
invokestatic path/to decryptor (Ljava/lang/String;)Ljava/lang/String;

becomes

ldc "EncryptedString"
pop
ldc "DecryptedString"
