### ISSUE TITLE
ThisTestUser's fork (Missing things)

### ISSUE THREAD

**Issue by ToonBasic** [java-deobfuscator/deobfuscator#227]
Hello, I had permission from Sam to post an issue here in-regards to your fork @ThisTestUser 

From your latest push you seem to be missing:
ArgsAnalyzer.FAILED_RESULT
setIgnoreNeeded();
setSpecialDup();
setBreakpoint();
getSwap();
and getArgsNeeded (There's probably more, but I noticed these)

According to IntelliJ that is. 

Any idea as per why? Am I missing something, or was the complete source not uploaded? Thanks.

**Comment by ThisTestUser** [comment]
Solved. I sometimes forget to commit certain files.

**Comment by ToonBasic** [comment]
Awesome! Thanks!
