### ISSUE TITLE
Unknown type of jar obfuscation

### ISSUE THREAD

**Issue by DoNotSpamPls** [java-deobfuscator/deobfuscator#228]
Hi there,
I'm trying to deobfuscate a jar, but so far I've had no success. I tried all included deobfuscators without luck, and the detector didn't help me either. Can someone help?

File download: https://files.fm/u/8hnd5eza

**Comment by AnnaDev24** [comment]
That's Zelix with some lightweight Flow Obfuscation Settings and Enhanced Mode of String Encryption.

**Comment by ThisTestUser** [comment]
[TemporaryPermsDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1905062/TemporaryPermsDeob.zip)

**Comment by DoNotSpamPls** [comment]
Thanks everyone!. I'll tinker with it more, since I have other jars to experiment with too.
