### ISSUE TITLE
Allatori String encryption error through it uses exceptions to get the calling method's name

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#23]
Don't have the exception now but its very easy to reproduce as allatori has a free version.

**Comment by samczsun** [comment]
I'll need some samples before I can proceed

**Comment by Janmm14** [comment]
You could've possibly downloaded the demo version, but here you have a sample (Allatori 3.7 and 3.8 demo seem to produce the same output):
Krakatau decompiler:
```
StackTraceElement a = new NullPointerException().getStackTrace()[1];
String s0 = new StringBuffer(a.getMethodName()).append(a.getClassName()).toString();
```

Relevant bytecode (from Krakatau):
```
L0:     new java/lang/StringBuffer 
L3:     dup 
L4:     new java/lang/NullPointerException 
L7:     dup 
L8:     invokespecial Method java/lang/NullPointerException <init> ()V 
L11:    invokevirtual Method java/lang/NullPointerException getStackTrace ()[Ljava/lang/StackTraceElement; 
L14:    iconst_1 
L15:    aaload 
L16:    dup_x2 
L17:    invokevirtual Method java/lang/StackTraceElement getMethodName ()Ljava/lang/String; 
L20:    invokespecial Method java/lang/StringBuffer <init> (Ljava/lang/String;)V 
L23:    swap 
L24:    invokevirtual Method java/lang/StackTraceElement getClassName ()Ljava/lang/String; 
L27:    invokevirtual Method java/lang/StringBuffer append (Ljava/lang/String;)Ljava/lang/StringBuffer; 
L30:    invokevirtual Method java/lang/StringBuffer toString ()Ljava/lang/String; 
```
After that a loop with xoring and other fun follows, with a ```return new String(char[])```

**Comment by samczsun** [comment]
I can't go around downloading everything. If you want to send me a copy of the relevant jar or class file it would be much more beneficial

**Comment by Janmm14** [comment]
This is the only bytecode pattern I've sawn while obfucating one of my projects. However I'll create a test project for you.

**Comment by Janmm14** [comment]
[Test-obf.zip](https://github.com/java-deobfuscator/deobfuscator/files/301476/Test-obf.zip)

**Comment by PunKeel** [comment]
Looks like the open source community is not so big after all :o 

In case you need any help, @samczsun, I do have an active Allatori license ... wait, I won't benefit from it, will I?

**Comment by samczsun** [comment]
I'm not sure of what you're implying

**Comment by PunKeel** [comment]
if you want me to obfuscate a given jar, I may. Working on simple files where you know what to expect might be easier

**Comment by Janmm14** [comment]
Well I already uploaded a test file obfuscated but with a clear and simple source  that anyone can think of if the string obfuscation is reversed.

**Comment by LPK-Matt** [comment]
Here's another sample _(Stringer itself)_. 

        final StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();
        final int hashCode = (SharedSecrets.getJavaLangAccess().getConstantPool(Class.forName(stackTrace[2].getClassName())).getSize() + stackTrace[2].getClassName() + stackTrace[2].getMethodName() + SharedSecrets.getJavaLangAccess().getConstantPool(Class.forName(stackTrace[3].getClassName())).getSize()).hashCode();
        //
        // What's being checked:
        // stackTrace[2] - The last method
        // stackTrace[3] - The class that called the last method
        
[stringer.zip](https://github.com/java-deobfuscator/deobfuscator/files/315442/stringer.zip)

**Comment by Janmm14** [comment]
@LPK-Matt is it getting deobfuscated or not if you try?

**Comment by LPK-Matt** [comment]
@Janmm14 I haven't tried but the existing [Allatori](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java) deccrypter doesn't look like it's designed to account for the class called as mentioned in my comment.

**Comment by Janmm14** [comment]
@LPK-Matt I asked whether stringer is deobfuscated by the stringerdeobfuscator or not. However I think its not.

Also things might get a bit tricky if strackTrace elements are checked with with indexes >1, you basically have to start simulating every possibility starting at the main method, know entry points of reflection, window handling, handling natives...

**Comment by LPK-Matt** [comment]
@Janmm14 Not really. Allatori only checks what method the call comes from. Stringer on the other hand... It wants to know what class called the method that called the decrypt function. That's where it gets brutal.

**Comment by Janmm14** [comment]
@lpk-matt I know that with allatori its relative simple. Did you checked whether reflection obfuscation is used? In that case with stringer its also a lot simpler (if stringer manages to stop generatedmethodaccessors from being created)

**Comment by LPK-Matt** [comment]
@Janmm14 Haven't checked but I doubt it uses reflection. It's not mentioned once in their [user manual](https://jfxstore.com/stringer/docs).

**Comment by Janmm14** [comment]
I know allatori does not have reflection obfuscation, however allatori just checks the calling class and method (index 1) and because of these two things the deobfuscator could simply look for such method calls

**Comment by samczsun** [comment]
@LPK-Matt Your Stringer and Allatori samples were deobfuscated successfully
@Janmm14 Your Allatori sample is now supported
