### ISSUE TITLE
Decryption with key by stacktrace

### ISSUE THREAD

**Issue by etmatrix** [java-deobfuscator/deobfuscator#233]
I trying to deobuscate strings in a jar converted by apk. I have already tried simplify and dex-oracle but don't support emulation of stacktrace, so no luck.
I read java-deobfuscator support many obuscators with key taken by stacktrace.
I have the following code in my jar:

    StackTraceElement v1 = new RuntimeException().getStackTrace()[1];
    String v4 = new StringBuffer(v1.getMethodName()).insert(0, v1.getClassName()).toString();
    // code with xor and string v4

but java-deobfuscator don't detect it.

    # cat detect.yml
    input: uret.jar
    detect: true

    # java -jar deobfuscator-1.0.0.jar --config detect.yml
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators

I tried with 

    # cat config.yml
    input: uret.jar
    output: output.jar
    path: 
        - /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
    transformers:
        - stringer.StringEncryptionTransformer

    # java -jar deobfuscator-1.0.0.jar --config config.yml
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
    [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
    [Stringer] [StringEncryptionTransformer] Starting
    [Stringer] [StringEncryptionTransformer] Found 0 encrypted strings
    [Stringer] [StringEncryptionTransformer] Done

[uret.zip](https://github.com/java-deobfuscator/deobfuscator/files/1934193/uret.zip)

**Comment by ThisTestUser** [comment]
[uretDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1934592/uretDeob.zip)
(Allatori deobfuscator)

**Comment by ThisTestUser** [comment]
I changed some things in the transformer to match your JAR.

**Comment by Wetitpig** [comment]
@etmatrix Agree

**Comment by ThisTestUser** [comment]
https://gist.github.com/ThisTestUser/aee25594ad51baf30b79ba51788ef777
This is just the old version of allatori string encryption transformer.

**Comment by Col-E** [comment]
The distance in the StackTrace is only `1` so the StackElement should just be the caller method. You won't need any simulation for making a decrypter.
