### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dollarssign** [java-deobfuscator/deobfuscator#237]
where are the name of the deobfuscators to put into the config? i can't see the list with the names right

**Comment by ItzSomebody** [comment]
https://github.com/java-deobfuscator/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers

**Comment by helloxdd** [comment]
why zelix.StringEncryptionTransformer is not a thing?

**Comment by ItzSomebody** [comment]
The old string encryption transformer for zelix was buggy and didn't work all too well.

The new ones are

zelix.string.EnhancedStringEncryptionTransformer
zelix.string.SimpleStringEncryptionTransformer

**Comment by Migsi** [comment]
> https://github.com/java-deobfuscator/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers
> 
> Replace stringer.StringEncryptionTransformer with whatever you need.
> 
> ```yaml
> input: input.jar
> output: output.jar
> transformers:
>   - stringer.StringEncryptionTransformer
> path:
>   - "C:/Program Files/Java/jdk1.8.0_XXX/jre/lib/rt.jar"
> ```

Not topic relevant, but please add the "path" detail to the readme.md or usage.md. It was hard for me to find out where to specify additional jars until I checked this issue.
