### ISSUE TITLE
Mapping example

### ISSUE THREAD

**Issue by infreq** [java-deobfuscator/deobfuscator#239]
Hello, is there any mapping examples? I'd like to use mapping file with package normalizer. Could someone provide an example if I want to rename package file.jar/net/a/\*.class to file.jar/net/b/\*.class?

**Comment by ItzSomebody** [comment]
From https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/normalizer/AbstractNormalizer.java

```java
    public static abstract class Config extends TransformerConfig {
        @JsonProperty(value = "mapping-file")
        private File mappingFile;

        public Config(Class<? extends Transformer> implementation) {
            super(implementation);
        }

        public File getMappingFile() {
            return mappingFile;
        }

        public void setMappingFile(File mappingFile) {
            this.mappingFile = mappingFile;
        }
    }
```

So as far as a I can see, no. It seems you need to add the mapping file code to a private fork.
