### ISSUE TITLE
DashO deobfuscator only works for low-setting configurations.

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#24]
Here are different setting combinations of DashO's string encryption. 

What [currently](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/dasho/StringEncryptionTransformer.java#L62) is checked:
- Is the description _(String, int)String_?
- Are the parameters and method calls directly next to each-other?

Some things to account for:
- Parameters that are not constants loaded right before the method call.
- Methods that have the same description but paramters do different things.

Example:       

```
    final int n = 14 * 12;
    final int n2 = 4;
    this.setTitle(Type.subSequence((n + (n2 + (n2 + n2))) / (14 << 2), 11, "[xwmBv9 !'?{ie"));

    final int n3 = 5 << 2;
    final int n4 = 2;
    final int n5 = n3 + (n4 + n4);
    final int n6 = 5;
    final String subSequence = Type.subSequence(n5 / (n6 + n6), 52, ";s;n;5L6f)l+>e8){9}}+)--\u0004w.pdq?swz,h6lz|t.m36h4r > \u0000{*,`\tz\"f+)mmJ~;k8o%sJ>{+8o\u0011r*>/,ek\u001e@\n;\u000bfd(m:wo&l97}!9\u001df&;oe3g\u001df&{/\u0011r*~olek^\u0000J;\u000bf$hm:w/f,97=ay\u0017K\u0000-k\fg5r!d8\bp=to.m#x#|o/b/i");
    this.d.setToolTipText(subSequence);
```

Samples: [DashO String Encryption Samples.zip](https://github.com/java-deobfuscator/deobfuscator/files/299147/DashO.String.Encryption.Samples.zip)

**Comment by samczsun** [comment]
Unfortunately this will have to wait until method analysis is fully thought out and implemented

**Comment by Janmm14** [comment]
As far as I looked at your method analysis it looked pretty complete.

**Comment by MoofMonkey** [comment]
It is an accident.

**Comment by samczsun** [comment]
hey it's only been a year but this is done now :)
