### ISSUE TITLE
Feature: DashO dummy exception removal

### ISSUE THREAD

**Issue by Col-E** [java-deobfuscator/deobfuscator#240]
**Targeted Obfuscator**: DashO

**Effect**:  All methods are wrapped with `try-catch` blocks. The exception is a dummy class that in most cases is unnecessary. Each class is given a dedicated dummy exception. This creates a large amount of bloat in the jar due to potentially hundreds of dummy classes being created in larger programs. Most decompilers can't sort by file size, so navigating past them is annoying.

**Example**: 

* [Code with dummies](https://user-images.githubusercontent.com/21371686/39719803-5afce1a0-5208-11e8-9e1f-8b703eccfa32.png)
* [The dummy](https://user-images.githubusercontent.com/21371686/39719813-612ca9f2-5208-11e8-9179-164d0be87551.png)

**Solution**: Iterate try-catch nodes and check if the node is located in the jar. If so, and the node extends `RuntimeException` and has [no other attributes other than the name and super-name](https://user-images.githubusercontent.com/21371686/39719908-a6857146-5208-11e8-80f2-0f59d72c2c0a.png)
then it should be removed from the jar and in-line replaced with normal `RuntimeException` to preserve behavior *(or removed if analysis shows no potential behavior changes)*.

**Comment by ThisTestUser** [comment]
If you want some dummy exceptions removed from a specific jar, you can send it and we'll remove the try-catch blocks for you.

**Comment by Col-E** [comment]
I can do that myself pretty easily. This is just a feature request since the project only decrypts DashO's strings. It's be neat to counter more of the features. This could potentially be bundled in with a bloat removing transformer as well.
