### ISSUE TITLE
Allatori ? can't deobfuscate

### ISSUE THREAD

**Issue by gesucanez** [java-deobfuscator/deobfuscator#242]
Hi guys,

can't deobfuscate this jar

some times ago it was protected with allatori and checking with jd-gui i think it's again allatori but updated.
tried some techniques but nothing.

can you help me ? 
ty

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/1996557/output.zip)
Use ThisTestUser's flow obfuscation transformer first then the allatori string encryption transformer

**Comment by gesucanez** [comment]
i'm using the gui version of thistestuser and i can only decrypt the strings but zelix.flowobfuscation transfomer doesn't work..am i choosing the wrong one ?

**Comment by gesucanez** [comment]
[test.zip](https://github.com/java-deobfuscator/deobfuscator/files/2000328/test.zip)
can you help me with that ?

**Comment by ItzSomebody** [comment]
@gesucanez that jar you provided isn't zelix flow obfuscation. I was referring to the flow signatures left by Allatori. ThisTestUser has a fork of Java-Deobfuscator over (https://github.com/ThisTestUser/deobfuscator)[here] (allatori.FlowObfuscationTransformer)which can restore a decent version of what the bytecode might have looked like before transformation by Allatori.

To deobfuscate the sample you provided, use allatori.FlowObfuscationTransformer then allatori.StringEncryptionTransformer from ThisTestUser's fork.
