### ISSUE TITLE
Need help deobfuscating allatori

### ISSUE THREAD

**Issue by CrimedTK** [java-deobfuscator/deobfuscator#246]
I am new to deobfuscation. 
here is my console output:
https://hastebin.com/ocoyajubiw.tex

my config file:
https://hastebin.com/mabariqivo.css

If someone can help me deobfuscate something i would be super grateful,
and if you need to you can contact me via Crimed#2273

p.s. can you explain what it means by "found possible SourceFile attribute"?

**Comment by FireMasterK** [comment]
Change your config to https://hastebin.com/aruzodaqun.css

**Comment by ItzSomebody** [comment]
@CrimedTK the java classfile format typically has debug information embedded into it when compiled. One of these debug information types is known as the source file attribute which is typically used to determine what the name of the source file was when it was compiled. (i.e. SocketListener.java)

**Comment by CrimedTK** [comment]
I ran it with the new config and i got this error.
https://hastebin.com/kukedodigo.css

**Comment by CrimedTK** [comment]
Used the GUI and it worked. because there is no clear way of adding the path via CMD i had to do it via the GUI

**Comment by CrimedTK** [comment]
https://hastebin.com/elihiwiham.vbs
It went through the whole thing and then it got this error at the end.

**Comment by ItzSomebody** [comment]
Add the library which contains that class

**Comment by CrimedTK** [comment]
it required a file named jdi.jar, downloaded it and added it to the path and it worked, thanks.
