### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by NanoNik** [java-deobfuscator/deobfuscator#256]
After deobfuscation I have a jar with a lot of reflection calls, is there a way to replace reflection calls with direct calls?
![image](https://user-images.githubusercontent.com/11991329/41823689-036b3484-780d-11e8-8a2f-a7fd6b7e5d4a.png)

I used zelix.ReflectionObfuscationTransformer

**Comment by Janmm14** [comment]
no secure way, because those reflection calls do put out completely different exceptions

**Comment by NanoNik** [comment]
I don't want to execute this jar, just for analyzing

**Comment by Janmm14** [comment]
Write your own transformer then. but first some of the strings also seem to be stiöll encrypted

**Comment by ThisTestUser** [comment]
Upload your obfuscated JAR here and we might be able to do it.

**Comment by Janmm14** [comment]
Just in case you are allowed to share the jar.

**Comment by NanoNik** [comment]
[Obfuscated.zip](https://github.com/java-deobfuscator/deobfuscator/files/2137052/Obfuscated.zip)
It is fully obfuscated file

**Comment by ThisTestUser** [comment]
[ObfuscatedDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2137891/ObfuscatedDeob.zip)

**Comment by NanoNik** [comment]
Wow, It look ideal, thank you!
