### ISSUE TITLE
static class constructor skipped string deobfuscation.

### ISSUE THREAD

**Issue by lab313ru** [java-deobfuscator/deobfuscator#260]
For example, class contains some static initialization:
```
    static {
        String v0 = "encrypted string";
        do {
            // decrypting loop
        } while ()
    }
```
In this case data won't be decrypted.

**Comment by Janmm14** [comment]
The deobfuscator's transformers are created for specific obfuscators. You should name which obfuscator was used and which transformers you tried.

**Comment by lab313ru** [comment]
Oh, sorry, I mean SimpleZelix transformer.

Janmm14 <notifications@github.com> 29 июня 2018 г. 19:41:14 написал:

**Comment by ThisTestUser** [comment]
If you have permission, you could send the JAR and we'll try to fix it.

**Comment by Enteerman** [comment]
Open a new issue with attached sample that you own.

**Comment by ItzSomebody** [comment]
I think it's more appropriate to tag this one as invalid. JavaVM has the ability to skip class initialization, if I recall correnctly and in the case of MethodExecutor, you can feed it the clinit method.
