### ISSUE TITLE
Initialization of VM took 1060ms

### ISSUE THREAD

**Issue by DrakMC** [java-deobfuscator/deobfuscator#264]
Hello, I have problem. I try deobfuscate my plugin but doesn't work. 

==============================[ LOG ]==============================

[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 1060ms

==============================[ CONFIG ]==============================

input: input.jar
output: output.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer

==============================[ DETECT ]==============================

input: input.jar
detect: true

**Comment by ItzSomebody** [comment]
I would recommend using stringer.StringEncryptionTransformer instead of stringer.v3.StringEncryptionTransformer since JavaVM has been known to hang for long periods of time for unknown reasons.

**Comment by DrakMC** [comment]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.io.FileNotFoundException: output.jar (Přístup byl odepřen)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:294)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by DrakMC** [comment]
Can you help me please? How to fix that error?

**Comment by Jerem584** [comment]
input != output

**Comment by Enteerman** [comment]
You have specified the input as `output.jar`, which does not exist.
