### ISSUE TITLE
ClassLoader cannot load class-file

### ISSUE THREAD

**Issue by lab313ru** [java-deobfuscator/deobfuscator#265]
```
java.lang.ArrayIndexOutOfBoundsException: 46592
	at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:188)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
```

[OCIPlugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/2158190/OCIPlugin.zip)

**Comment by ThisTestUser** [comment]
Download the latest deobfuscator.

**Comment by lab313ru** [comment]
I'm using the latest one.

**Comment by ThisTestUser** [comment]
The file seems to be corrupt, because if you look at it with Bytecode viewer there's a lot of NOP instructions.

**Comment by lab313ru** [comment]
Why NOPs is a problem?
They should just be skipped.

ThisTestUser <notifications@github.com> 3 июля 2018 г. 16:52:19 написал:

**Comment by ThisTestUser** [comment]
The problem is that there's nothing to deobfuscate in the JAR.

**Comment by lab313ru** [comment]
But it cannot be decompiled anyway.

**Comment by lab313ru** [comment]
And my guess is that many nops and catches are used for breaking decompilation (so, to "deobfuscate".

**Comment by ThisTestUser** [comment]
It's actually missing code, which means that the JAR will not run correctly, and thus is impossible to deobfuscate. Even if the nops are removed, the result will still be decompilable.

**Comment by lab313ru** [comment]
But this code is runnable and usable.

**Comment by ThisTestUser** [comment]
But your file only contains 1 class, which doesn't have a main method.

**Comment by lab313ru** [comment]
It's not a problem. Because I just extracted this file to show you the exact problem.

**Comment by ThisTestUser** [comment]
That means that this specific class file is corrupt, and your best option is to remove it.

**Comment by lab313ru** [comment]
It is not corrupted. All other files in the jar look like this one.

**Comment by ThisTestUser** [comment]
Do the other files reference methods in this class? =

**Comment by lab313ru** [comment]
Nope.

**Comment by ThisTestUser** [comment]
Then you should remove this class file from the JAR, and it should not bug out.
