### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by iyordiii** [java-deobfuscator/deobfuscator#27]
It says: Deobfuscation failed, please open a ticket on Github

What can i do?

https://gyazo.com/201bd7fda354ada430295818a81cfae9

**Comment by Janmm14** [comment]
See https://github.com/java-deobfuscator/deobfuscator/issues/19

**Comment by iyordiii** [comment]
Where can i download rt.jar

**Comment by Janmm14** [comment]
You don't need to download, its in the lib folder of your java installation, inside a directory called jre1.x_xx (x: placeholder)
