### ISSUE TITLE
New Smoke version

### ISSUE THREAD

**Issue by c0d03d2d3e717da54ffdfc8a76c0f089** [java-deobfuscator/deobfuscator#271]
This file has been obfuscated with the latest version of the Smoke obfuscator.
Things i noticed:
-string deobfuscator still works (but does not remove decryption methods)
-number obfuscation has a new types, like this: (0xF4240 | 0 << 32), (0x4B | 0 << 32), Double.longBitsToDouble(0x0 | 1079574528 << 32), Float.intBitsToFloat(1132396544)
-flow obfuscation uses now switch statements and got other improvements
-pop2 and pop obfuscation

[Release.zip](https://github.com/java-deobfuscator/deobfuscator/files/2176514/Release.zip)

**Comment by ItzSomebody** [comment]
[deobbed.zip](https://github.com/java-deobfuscator/deobfuscator/files/2177245/deobbed.zip)

The flow obfuscation is really easy to read through and the new number obfuscation can also be read easily by simply sticking it into Python shell or similar.
