### ISSUE TITLE
Decr quest [Stringer(Might) + Dasho +2Km(10.XPaid)]

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#272]
Seems to be hard.
Help me removed the String obfu & signature Check thanks.
https://mega.nz/#!jQIXhC5R!ICRIP22N7xaXD6mBsPMwJgmZVJwdfsm_0hDGOF00GOo

**Comment by rettlsteiner** [comment]
I didn't deobfuscated, decompiled, and compiled it. The class names, that're like "A\u0391\u0391\u0410\u0391AAA", are causing a lot of trouble in all deobfuscator and decompiler.

**Comment by Janmm14** [comment]
This deobfuscator shouldn't have problems with unicode characters in class names. @rettlsteiner

**Comment by rettlsteiner** [comment]
It still doesn't explain why it's throwing a lot of errors in the deobfuscation. In all decompiler I tried to decompile the Jar-File, after deobfuscation, it gets a lot of empty classes.

**Comment by Janmm14** [comment]
If you get erros in deobfuscation, why don't show these?
Compeltely empty class files in your decompiler usually means you need to use the syntheticbridgetransformer. Alternatively use for example krakatau+pypy with bytecodeviewer gui.

**Comment by ThisTestUser** [comment]
[sdDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2264633/sdDeob.zip)

**Comment by CrackFileso** [comment]
@ThisTestUser You Are A True God.Thanks!
