### ISSUE TITLE
Zelix deobfuscator fail

### ISSUE THREAD

**Issue by TheNamedMeFilip** [java-deobfuscator/deobfuscator#275]
Hello, i used Detect to see what obfuscator is used and when i tried to deobfuscate it using the choosen deobfuscator (zelix.string.SimpleStringEncryptionTransformer), it does not work. Can you help me or deobfuscate it?
_snipped link_

**Comment by TheNamedMeFilip** [comment]
I do it when i needed help first time and ThisTestUser not told me that i cannot upload premium spigot plugins... nevermind... But about that, stringer hasn't been able to deobfuscate that. Can you do that for me?

**Comment by Janmm14** [comment]
You should definitely respect the authors work @TheNamedMeFilip and not deobfuscate/decompile premium spigot plugins.
