### ISSUE TITLE
deobfuscation request (malware)

### ISSUE THREAD

**Issue by theminecraftlegend27** [java-deobfuscator/deobfuscator#276]
Hello, I am wondering what obfuscator this is and how to decrypt strings. I am certain it is used for malware in these samples. I really want to prevent people from having their credentials stolen. Password is infected.
[infected.zip](https://github.com/java-deobfuscator/deobfuscator/files/2225922/infected.zip)

**Comment by ItzSomebody** [comment]
Did you try running java-deobfuscator’s detect more?

**Comment by theminecraftlegend27** [comment]
yes, no obfuscators detected

**Comment by ThisTestUser** [comment]
Are you sure the same is runnable?

**Comment by theminecraftlegend27** [comment]
Not runnable as a standalone jar, but decryption of strings should still be possible.

**Comment by ThisTestUser** [comment]
Did you rename the methods in the JAR in any way? Decrypting the strings throws an exception, usually because it requires the method names/class names to remain static.

**Comment by theminecraftlegend27** [comment]
no, they run. I know it is malware because of network analysis
11108 62.385046 10.0.2.15 142.93.15.69 TCP 66 [TCP Retransmission] 49845 → 1337 [SYN] Seq=0 Win=8192 Len=0 MSS=1460 WS=256 SACK_PERM=1

**Comment by ThisTestUser** [comment]
[2Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2229966/2Deob.zip)
[1Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2229967/1Deob.zip)

**Comment by theminecraftlegend27** [comment]
what obfuscator was it, and program to remove?

**Comment by ThisTestUser** [comment]
Custom obfuscator, so I used a custom transformer.

**Comment by theminecraftlegend27** [comment]
mind sharing? The file downloaded by 2.jar is also obfuscated the same. the C&C server and activity seems to be the same though.

**Comment by ThisTestUser** [comment]
The transformer is a hasty edit of allatori's stringencryptiontransformer: https://gist.github.com/ThisTestUser/8834dfcdbb41af08e6c26294a41767b4

**Comment by theminecraftlegend27** [comment]
the transformer did not work for me unfortunately
https://ghostbin.com/paste/57j7v

**Comment by ThisTestUser** [comment]
Try using JVMMethodProvider.java from here:
https://github.com/ThisTestUser/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/executor/defined/JVMMethodProvider.java
Also take other files if you have compile errors.

**Comment by theminecraftlegend27** [comment]
cloned the git and replaced stringencryptiontransformer, same output.

**Comment by ThisTestUser** [comment]
Below line 394 in JVMMethodProvider.java (https://github.com/ThisTestUser/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/executor/defined/JVMMethodProvider.java#L394), insert these lines of code:
```
put("java/security/MessageDigest$Delegate", new HashMap<String, Function3<JavaValue, List<JavaValue>, Context, Object>>() {{
        	put("digest([B)[B", (targetObject, args, context) -> {
            	Method digest = Class.forName("java.security.MessageDigest.Delegate").getDeclaredMethod("digest");
            	digest.setAccessible(true);
            	try
            	{
            		return digest.invoke(targetObject.value(), args.get(0).as(byte[].class));
            	}catch(InvocationTargetException e)
            	{
            		throw e.getTargetException();
            	}
            });
        }});
```

**Comment by theminecraftlegend27** [comment]
added, all strings are replaced with "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
now

**Comment by ThisTestUser** [comment]
[jre1.8Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2237480/jre1.8Deob.zip)

**Comment by theminecraftlegend27** [comment]
changes to fix? Found another sample in the wild by same attacker, seems to be active. pass infected.
[infected.zip](https://github.com/java-deobfuscator/deobfuscator/files/2237519/infected.zip)

**Comment by ThisTestUser** [comment]
It's Radon obfuscator by ItzSomebody, and there are several different types of obfuscation, so it's hard to give you a transformer that will work for all cases here.
[infectedDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2237578/infectedDeob.zip)
All the RATs practically do the same thing (fetch JAR from server and run it).

**Comment by theminecraftlegend27** [comment]
Dang lol, didn't realize it's an obfuscator you guys made. Kinda sucks to see people using free and open source software maliciously. Not exactly your fault as avs have not come this far on java applications as native software with code emulation. Only thing avs can really do at this point is adding a generic signature for all programs obfuscated with it like they do for commercial packets like vmprotect and thermida.
also is there a way to fix the ArrayIndexOutOfBoundsException or did the last 2 samples use a different obfuscation technique?

**Comment by ThisTestUser** [comment]
It's caused by fake classes, so at line 205 (https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java#L205) in Deobfuscator.java you also need to catch ArrayIndexOutOfBoundsException.
