### ISSUE TITLE
REMOVE

### ISSUE THREAD

**Issue by SwartZCoding** [java-deobfuscator/deobfuscator#278]
REMOVE

**Comment by ThisTestUser** [comment]
[minecraftDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2237172/minecraftDeob.zip)
I deleted all the assets to save space, but you can add them back from your minecraft.jar.

**Comment by MysoriaDev** [comment]
OHOH thqnks / But how did you do that ... :)

**Comment by MysoriaDev** [comment]
@ThisTestUser Man i have a problem, a lot of function is obfuscate. Can you resend me with a good fonction ?
