### ISSUE TITLE
[Allatori] [FlowObfuscationTransformer]

### ISSUE THREAD

**Issue by PandaHaxor** [java-deobfuscator/deobfuscator#280]
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.FlowObfuscationTransformer
[Allatori] [FlowObfuscationTransformer] Starting

It still shows me this.

**Comment by ThisTestUser** [comment]
It's not perfect, so you have to send your file so we can see what's wrong.
