### ISSUE TITLE
ThisTestUser's Lastest

### ISSUE THREAD

**Issue by PandaHaxor** [java-deobfuscator/deobfuscator#283]
Hello! @ThisTestUser , I need your lastest java-deobfuscator version, this released version was so old! It's can't deobf the new obfuscator.

**Comment by rettlsteiner** [comment]
You can get the newest version from ThisTestUser here.

Bamboo Build Server:
https://ci.plugindev.de/browse/GITHUB-DEOBF/latestSuccessful

Bitbucket Front-end Git Server:
https://git.plugindev.de/projects/GITHUB/repos/deobfuscator/browse

Feel free to use them. BTW, please notify me if I abuse the Github rules with this message, idk if I'm allowed to post links to my server. I mean, it could be interpreted as "advertisement".

**Comment by netindev** [comment]
https://github.com/ThisTestUser/deobfuscator
