### ISSUE TITLE
I can't deobf anything!

### ISSUE THREAD

**Issue by PandaHaxor** [java-deobfuscator/deobfuscator#284]
I tried Stringer v3 String, ZKM all way.  Also can't deobf. Can you help me to deobf it???? Thank you.

Jar download link:http://4lpha.one/dl/1LgUIlaUOvH3pEF2xOOSlt8OMDRzdm-Vr

**Comment by fikawka** [comment]
SHA-256

**Comment by ThisTestUser** [comment]
[YCClientDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2268161/YCClientDeob.zip)
