### ISSUE TITLE
Can't deobfuscation this. (Maybe DashO and ZKM?)

### ISSUE THREAD

**Issue by PandaHaxor** [java-deobfuscator/deobfuscator#287]
I can't deobfuscation anything, but then I can't launch it. And I can't deobfuscation the String, I tried ThisTestUser's version but I can't deobfuscation, either. What the heck? Can you help me to deobfuscation it?
Download link:https://4lpha.one/dl/1RL1__ZaQwZd-bYNemqEVQz1Js-iTRoIK

**Comment by ThisTestUser** [comment]
[ExhibitionDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2295421/ExhibitionDeob.zip)

**Comment by RealNefIntent** [comment]
What did you use to do that @ThisTestUser

**Comment by ThisTestUser** [comment]
Custom deobfuscators and github.com/ThisTestUser/deobfuscator.
