### ISSUE TITLE
partial deobfuscation?

### ISSUE THREAD

**Issue by ThrowawayBotAccount** [java-deobfuscator/deobfuscator#288]
Wondering if this file can be deobfuscated any further or what kind of obfuscation it is using.

Original: https://nofile.io/f/S03Fr6HK32q/onetap.jar
Attempt: https://nofile.io/f/zntT6cYa0bX/onetap+partial.jar

Detection: sourcefileclassnormalizer

transformers used: 
-transformer normalizer.SourceFileClassNormalizer -transformer normalizer.PackageNormalizer -transformer normalizer.MethodNormalizer -transformer normalizer.FieldNormalizer -transformer normalizer.DuplicateRenamer -transformer normalizer.ClassNormalizer -transformer allatori.FlowObfuscationTransformer -transformer allatori.LightFlowObfuscationTransformer -transformer allatori.StringEncryptionTransformer

If you could deobfuscate it fully, that would be a great help!

**Comment by Janmm14** [comment]
if you use SourceFileClassNormalizer , don't use ClassNormalizer

**Comment by ThisTestUser** [comment]
[onetapDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2293690/onetapDeob.zip)
I only removed Allatori, but you can use the normalizers to fix the names.

**Comment by ThrowawayBotAccount** [comment]
Thank you for the advice Jamm14 and ThisTestUser for the output.
