### ISSUE TITLE
Deobfuscating not working?

### ISSUE THREAD

**Issue by ThrowawayBotAccount** [java-deobfuscator/deobfuscator#292]
Hello again, this time I have a file that doesn't seem to be deobfuscating even with the detected transformer(s)?

Original file: https://expirebox.com/download/d9eb1943f3016c15dae36f1d5faadc61.html
Detection:  stringer.v3.StringEncryptionTransformer
libs: rt, tools, and this https://expirebox.com/download/2b91f7919f50cddfd7f8744958fdf44d.html

Run:
> [Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 375ms
[Thread-4] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer - Decrypted 0 strings
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing

I later ran it through almost every single transformer and found that allatori seems to be helpful a bit but it still seems to be a mess.

A look in the decompiler shows that part of the file has some nonobfuscated classes (useless?)
If you could remove the deobfuscation, thanks.

**Comment by ItzSomebody** [comment]
Password for file download?

**Comment by ThrowawayBotAccount** [comment]
My bad, didn't mean to put a password.
I have fixed the link

**Comment by ItzSomebody** [comment]
That's obfuscated with allatori, not stringer

**Comment by ThisTestUser** [comment]
[KSmodDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2299551/KSmodDeob.zip)
