### ISSUE TITLE
ThisTestUser I can't decrypt these DashO strings.

### ISSUE THREAD

**Issue by RealNefIntent** [java-deobfuscator/deobfuscator#295]
[Exhibition.zip](https://github.com/java-deobfuscator/deobfuscator/files/2320966/Exhibition.zip)
I can't decrypt the strings in this jar. I saw a previous post of you giving someone else the decrypted strings of an older version of this jar. Your dash-o string decrypter didn't work. Please help.

**Comment by ThisTestUser** [comment]
[ExhibitionDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2328999/ExhibitionDeob.zip)
I know you closed the issue but here it is anyways.
