### ISSUE TITLE
run say open ticket on github

### ISSUE THREAD

**Issue by supermegajavacoder2006** [java-deobfuscator/deobfuscator#300]
i try deobfuscate 'hello world' JAR application

it gives error

when i using command `java -Xmx6G -jar deobfuscator-1.0.0.jar --config hello-normalizer.conf` it writed out of heap space

help??

configuration:
[hello-normalizer.conf.txt](https://github.com/java-deobfuscator/deobfuscator/files/2342800/hello-normalizer.conf.txt)

error:
[error.txt](https://github.com/java-deobfuscator/deobfuscator/files/2342802/error.txt)

**Comment by ItzSomebody** [comment]
Increase the heap space with -Xmx

**Comment by supermegajavacoder2006** [comment]
i run already with 6 gigabyte

my computer have only 8

**Comment by ItzSomebody** [comment]
Did you try to see what happens when you simply don't use it at all?

**Comment by supermegajavacoder2006** [comment]
firstly i ran without -Xmx but when it gave a bug i followed advice you gave at another bug report

**Comment by ItzSomebody** [comment]
Are you able to provide the jar you are trying to deobfuscate?
