### ISSUE TITLE
Deobfuscation failed - Said to open a ticket

### ISSUE THREAD

**Issue by Johanmans10** [java-deobfuscator/deobfuscator#301]
I tried to deobfuscate a jar file, and it said to open a ticket, so here I am.
I can provide the jar file, but I cannot post it publicly, so if you really need it you can contact me through discord: Johanmans10#0171
(In order for me to give you the file you would need to prove to me that you are one of the developers working on this project)

[error.txt](https://github.com/java-deobfuscator/deobfuscator/files/2342875/error.txt)
[config.txt](https://github.com/java-deobfuscator/deobfuscator/files/2342878/config.txt)

**Comment by ItzSomebody** [comment]
Increase the heap space with -Xmx

**Comment by Johanmans10** [comment]
I did, but even with 2GB it still gave the same error, so I don't think that's the problem.

**Comment by ItzSomebody** [comment]
Oops, I read the wrong error. Maybe when ThisTestUser gets on, you could try sending it to him.

**Comment by Johanmans10** [comment]
Ok, and how do I know when he is on?

**Comment by ThisTestUser** [comment]
Contact TheOPPerson#9796.
