### ISSUE TITLE
Deobfuscation failed ._.

### ISSUE THREAD

**Issue by hypedcxde** [java-deobfuscator/deobfuscator#303]
I have a probelm, i buyed a Bungeecord system and now i want to deobfuscate it.
He uses da Aliatori Obfuscator, but when i try to do java -jar deobfuscator.jar, [main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - A config file must be specified, appears,
and if i try java -jar deobfuscator.jar --config config.yml that appears https://ghostbin.com/paste/gr9gu .

Config » https://ghostbin.com/paste/nh9rs

**Comment by Janmm14** [comment]
Remove existing transformers and write `allatori.string.StringEncryptionTransformer`
without `[]`

**Comment by hypedcxde** [comment]
Thanks for the quick Support, but when i now type java -ajr deobfuscator.jar --config config.yml type,
https://ghostbin.com/paste/ng9pb appears. And if i try java -jar deobfuscater.jar
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - A config file must be specified
appears.

 Config » https://ghostbin.com/paste/2xpkt

**Comment by hypedcxde** [comment]
Oh youre German? Können auch Deutsch schreiben xd

**Comment by Janmm14** [comment]
Warum willst du BungeeCord überhaupt deobfuscaten? Ist doch open source.

**Comment by hypedcxde** [comment]
Das ist ein Bungeecord System. Kannst du mir helfen ?
