### ISSUE TITLE
Help with custom transformer

### ISSUE THREAD

**Issue by ThatGamerBlue** [java-deobfuscator/deobfuscator#306]
-- relevant info --
"deobfuscation" method signature: (I)Ljava/lang/String;
method calling: public static
example bytecode: 
```
sipush 123
invokestatic exampleclass.unscramble (I)Ljava/lang/String;
```

Have tried copying allatori deobber and changing the signature and the bytecode, I'm stupid? https://i.imgur.com/arcuBQL.png 

The "deobfuscation" method is just an array lookup, so I'm probably just stupid.

**Comment by ThisTestUser** [comment]
Not sure what you're doing wrong there, but you can send your JAR for us to see.

**Comment by ThatGamerBlue** [comment]
Can't share the JAR itself (copyright and all that) but I've made something pretty close to the original w/ source: 
[packed.zip](https://github.com/java-deobfuscator/deobfuscator/files/2400210/packed.zip)

**Comment by ThisTestUser** [comment]
In your imgur file, try removing the "methodInsnNode.clone(null)". If it doesn't work there isn't really much we could do.
