### ISSUE TITLE
Unable to deobfuscate two jars

### ISSUE THREAD

**Issue by DreenDex** [java-deobfuscator/deobfuscator#308]
There are two jars that cannot be deobfuscated with your deobfuscator. Especially strings. Also code is needed.

[jars.zip](https://github.com/java-deobfuscator/deobfuscator/files/2435045/jars.zip)

**Comment by ThisTestUser** [comment]
[Sbfixobfc-1.12Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2435809/Sbfixobfc-1.12Deob.zip)
[CheckerDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2435810/CheckerDeob.zip)
