### ISSUE TITLE
Deobf it, please :(

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#309]
Guys, please, deobf that jar, I can't :'C

File: https://www.upload.ee/files/9018308/LauncherSoket.jar.html

**Comment by ThisTestUser** [comment]
[LauncherSoketDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2439884/LauncherSoketDeob.zip)

**Comment by lIceCreaml** [comment]
Thankyou
