### ISSUE TITLE
LabelNodes stopping PeepholeOptimizer

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#31]
I got onto some bytecode today that randomly had some `LabelNode`s, leading to the issue that one ldc-pop structure was not removed by the PeepholeOptimizer (the `POP` was added by me with my just-created `DupPop2Replacer` through the iterator of `InsnList`).

Just as a note - there was also no jump to that particular LabelNode.

**Comment by samczsun** [comment]
Not sure if this is still a case as peephole optimizer has been revamped

**Comment by Janmm14** [comment]
This issue was created when I had no clue what LabelNodes actually do.
