### ISSUE TITLE
top 1 deobfuscation that gone wrong

### ISSUE THREAD

**Issue by DreenDex** [java-deobfuscator/deobfuscator#310]
Unable to deobf this jar.

[jarjava.zip](https://github.com/java-deobfuscator/deobfuscator/files/2439195/jarjava.zip)

**Comment by ThisTestUser** [comment]
[ScreenModObfDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2439578/ScreenModObfDeob.zip)
