### ISSUE TITLE
Deobf that, I want to believe

### ISSUE THREAD

**Issue by V1nga** [java-deobfuscator/deobfuscator#312]
Please, deobf that jar, I can't do anything ;'C 
File: https://www.upload.ee/files/9020899/LauncherSoket.jar.html

**Comment by Janmm14** [comment]
#309

**Comment by Xed0sS** [comment]
> #309

File in last issue has old :\

**Comment by ThisTestUser** [comment]
[LauncherSoketDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2443958/LauncherSoketDeob.zip)


Libaries (future reference for me):
rt.jar
jce.jar
tools.jar
Project Nashorn (https://minecraft.curseforge.com/projects/project-nashorn)
Bungee and Spigot
dom4j (https://mvnrepository.com/artifact/dom4j/dom4j/1.6.1)
launch4j (https://mvnrepository.com/artifact/net.sf.launch4j/launch4j/3.12)
