### ISSUE TITLE
Deobfuscator error

### ISSUE THREAD

**Issue by Spark61** [java-deobfuscator/deobfuscator#314]
Hello,
I have a problem with me always comes this error what does that mean?
https://hastebin.com/atamaridac.css

**Comment by ThisTestUser** [comment]
What is your configuration? It looks like you messed up on something.
If you want a GUI interface, you can try https://github.com/java-deobfuscator/deobfuscator-gui

**Comment by Spark61** [comment]
I've already used the GUI because there was no offuscateter code found even though the code is

**Comment by Spark61** [comment]
Or you can look at this plugin times it should actually be obfusatet http://workupload.com/archive/24DRZnQ

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2462626/PluginDeob.zip)

**Comment by Spark61** [comment]
Can you give me this also with the Ending. Java and not with the Ending. class please

**Comment by Janmm14** [comment]
@spark61 no, you need to a decompiler for that, for example bytecodeviewer (its a gui for multiple decompilers)
