### ISSUE TITLE
deobfuscator issue, pretty BIG

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#323]
Hello,
Today I have a problem with: Field and Method normalizer.

Where is the problem?
It just doesnt rename the fields/methods when the class is extended by other class.

Example,
there are 3 files named Entity, ExampleClass, Hello

//Entity - before deobfuscation
public class Entity {
 int AllatoriXDemo;
 int fhufuhdHIIOHFIOFADIJFSDJOFIOj;
 boolean SDGOJNSDGGSDNNIGGSDNIGOSGSDNNOIK;
}

//Hello - before deobfuscation

public class Hello 
extends Entity // here is the problem.
{
 int g;
 int verIrrr;
}

// ExampleClass - before deobfuscation
public class ExampleClass {
 
 public Hello gnhSg = new Hello();

 public void SomeRandomMethod() {
 gnhSg.AllatoriXDemo = 1; // from Entity
  }
}

//and the exampleclass - after deobfuscation 1. problem

public class ExampleClass {
 
 public Hello Field132 = new Hello();

 public void Method165() {
 Field132.AllatoriXDemo = 1; // it just sometimes doesnt rename or it is sometimes random Field like
  }
}

//and the exampleclass - after deobfuscation 2. problem

public class ExampleClass {
 
 public Hello Field132 = new Hello();

 public void Method165() {
 Field132.Field156 = 1; // just random field + number...
  }
}

//

I can include the file with this problem.

edit: it does everytime.

**Comment by ThisTestUser** [comment]
What do you mean by "deobfuscation 1" and "deobfuscation 2"? Please list your transformers you used to get the results.

**Comment by ItzSomebody** [comment]
Just provide a before & after jar, it's a pain to read that.

**Comment by awesomennguy** [comment]
ThisTestUser i used ClassNormalizer, FieldNormalizer and MethodNormalizer.

**Comment by awesomennguy** [comment]
and do you fix it?

**Comment by ThisTestUser** [comment]
Since I didn't make the normalizer, it's hard to push fixes to it. So for now use ProGuard.

**Comment by awesomennguy** [comment]
if you want i can send you the code from proguard

**Comment by Janmm14** [comment]
@awesomennguy that doesn't help
