### ISSUE TITLE
The deobfucator isnt working. It's very hard !!

### ISSUE THREAD

**Issue by TerriblePanda** [java-deobfuscator/deobfuscator#324]
The deobfucator isnt working. Because it's very strong.

Download Link: https://4lpha.one/dl/19M3fATN_KLytz7fT_jPzJiEwVWIpOM0V

Help me please!

**Comment by ItzSomebody** [comment]
The deobfuscator works fine on it, it just needs a few edits and transformers added to it. This obfuscation is honestly not that strong, there's some simple flow obfuscation, string encryption and some anti-decompiler techniques ripped out of https://github.com/Janmm14/decompiler-vulnerabilities-and-bugs

**Comment by TerriblePanda** [comment]
> The deobfuscator works fine on it, it just needs a few edits and transformers added to it. This obfuscation is honestly not that strong, there's some simple flow obfuscation, string encryption and some anti-decompiler techniques ripped out of https://github.com/Janmm14/decompiler-vulnerabilities-and-bugs

Can you help me deobf it?
