### ISSUE TITLE
Deobfuscator throwing Errors when trying to run Stringer deobfuscation.

### ISSUE THREAD

**Issue by onemoreplays** [java-deobfuscator/deobfuscator#325]
Hello,
so I'm trying to deobfuscate file protected with Stringer 3 (Looks like cracked version from BSMC) and when using recommended 
transformers (
    - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
    - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
)
SourceFileClassNormalizer is okay
And it looks like StringEncryptionTransformer doesn't decrypt anything.
So, back to the problem, when Deobfuscator tries to write changes, I only get Errors 
![image](https://user-images.githubusercontent.com/29712695/48019015-aead2f80-e132-11e8-886b-295089a924b1.png)
btw, it's Spigot plugin. I'm deobfuscating because of report saying it can contain Crypto miner.

Can someone help?
Thank you,
Jakub (inao)

**Comment by awesomennguy** [comment]
inao potřebuješ includnout jary ;)

**Comment by onemoreplays** [comment]
> inao potřebuješ includnout jary ;)

A jaké prosimtě? :D Spigot už mám included. možná ještě že rt.jar

(btw, for ENG speaking users, translate from Czech)

**Comment by onemoreplays** [comment]
Thanks @awesomennguy 
Problem solved.
