### ISSUE TITLE
Obfuscator Questions

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#326]
1, Hello what is this obfuscator? : http://prntscr.com/lfl9k2
2, What is good(best) obfuscator?

**Comment by Janmm14** [comment]
1. maybe some obfuscator like allatori or stringer combined with smoke obfuscator
2. obfuscated native code protected by vmprotect / themida / etc.

**Comment by ItzSomebody** [comment]
1. That's [this obfuscator](https://github.com/superblaubeere27/obfuscator)
2. For Java? I would say ZKM. For natives, probably Themida (I have heard that VMP's VMs are significantly easier to reverse).

**Comment by superblaubeere27** [comment]
@awesomennguy Yes. This is my obfuscator (https://github.com/superblaubeere27/obfuscator)

**Comment by Janmm14** [comment]
Not like its already linked...

**Comment by superblaubeere27** [comment]
@Janmm14 I just verifed it .-.
