### ISSUE TITLE
Please help me with deobfuscation

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#328]
Hello, I already did issue about this jar, but it was old version.
So, can someone please help me with deobfuscation?
The obfuscator is named "SimpleObfuscator" by xRubiks
dl: https://workupload.com/file/6MWQaURx
I dont know how I can deobfucsate this.

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2569028/output.zip) (most strings decrypted)

That's actually a fork of [this](https://github.com/ItzSomebody/Radon) with minimal edits combined with Allatori.

**Comment by awesomennguy** [comment]
@ItzSomebody yes, i used allatori for normalizing the fields & methods.
i toggled off the string encryption so idk.

**Comment by awesomennguy** [comment]
> [output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2569028/output.zip) (most strings decrypted)
> 
> That's actually a fork of [this](https://github.com/ItzSomebody/Radon) with minimal edits combined with Allatori.

btw he is selling for 5€ i thought
Can you deobfuscate this jar? 
I post bad jar :(
I am so sorry. :(

link: https://workupload.com/file/4fjJ3pBS

**Comment by ItzSomebody** [comment]
Do you have a jar without allatori in it? Because you use allatori on it, it's flow obfuscating the stacks.

**Comment by awesomennguy** [comment]
> Do you have a jar without allatori in it? Because you use allatori on it, it's flow obfuscating the stacks.
> 
> > btw he is selling for 5€ i thought
> 
> Lol.

yes i have without

link: https://workupload.com/file/tvPDR94F

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2569615/output.zip)

**Comment by awesomennguy** [comment]
//close
