### ISSUE TITLE
Found possible SourceFile attribute on

### ISSUE THREAD

**Issue by kotovdkotov** [java-deobfuscator/deobfuscator#329]

**Comment by kotovdkotov** [comment]
![image](https://user-images.githubusercontent.com/45015708/48492882-d17aca80-e83b-11e8-84f6-84a8181bda88.png)

Hello guys. Error with deobfuscator. Can you help me?

**Comment by Janmm14** [comment]
The deobfuscator cannot detect all kinds of obfuscation.

**Comment by kotovdkotov** [comment]
And how should I be?

**Comment by Janmm14** [comment]
Either try with available deobfuscators or wait for some users who think left-wing enough that all software should be free and open and deobfuscate a sample for you, that you only provide IF YOU HAVE THE RIGHT TO SHARE IT, or you learn java bytecode and how to write your own transformer to deobfuscate, or don't have the jar deobfuscated.
