### ISSUE TITLE
ProGuard Config

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#330]
Hello can someone help me with config?
I want to fields look like as: field_180145_F

**Comment by ThisTestUser** [comment]
If your program was obfuscated with a custom obfuscator (Allatori, Proguard, etc.) then you cannot do anything about it.
But if your program used the default MCP recompile command to recompile, you can use https://github.com/immibis/bearded-octo-nemesis.

**Comment by Enteerman** [comment]
Or use the transformers under [this package](https://github.com/java-deobfuscator/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/minecraft)
