### ISSUE TITLE
Ineffective against Paramorphism obfuscation

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [java-deobfuscator/deobfuscator#333]
Paramorphism (https://paramorphism.serenity.enterprises) is an obfuscator that has, so far, evaded my deobfuscation attempts. (please ignore that I am the developer of this obfuscator)

Whenever `java-deobfuscator` attempts to read in a JAR like this, an immediate spike in RAM usage occurs, and the normalization system seems to crash.

**Comment by half-cambodian-hacker-man** [comment]
An example of this can be found at #300.

**Comment by Janmm14** [comment]
my idea of what happens: Invalid java class files added and valid java class files added which are never used and contain only a really big string or something like that.
