### ISSUE TITLE
Can't deobf that jars

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#334]
I can't deobf that jars, please, deobf it =(

Jar 1: https://www.upload.ee/files/9218228/petcheck-rc.jar.html
Obfuscation: Stringer

Jar 2: https://www.upload.ee/files/9218240/fw-gui-release.jar.html
Obfuscation: Allatori

**Comment by ThisTestUser** [comment]
[fw-gui-releaseDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2608356/fw-gui-releaseDeob.zip)
[petcheck-rcDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2608374/petcheck-rcDeob.zip)
