### ISSUE TITLE
Helping with coding

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#335]
Hello, today I decided to make something as "deobfuscator".
The "deobfuscator" will do if the class equals some string or field it will rename to example. "Entity".

Where I should start?

**Comment by ThisTestUser** [comment]
You would make a class similar to ClassNormalizer.java (check in the code).
Here's an example of how you would do it:
```
    @Override
    public void remap(CustomRemapper remapper) {
        AtomicInteger id = new AtomicInteger(0);
        classNodes().forEach(classNode -> {
        	if(classNode.name.contains("YOUR_NAME_HERE"){
            remapper.map(classNode.name, mappedName);
        	}
        });
    }
```
Of course, this is just a basic example, and can get more complicated.
