### ISSUE TITLE
Can you help me recover the source code of xray ?

### ISSUE THREAD

**Issue by NullHF** [java-deobfuscator/deobfuscator#340]
For almost 2 years, xray is no longer maintained by the owners
So, I try to maintain myself but I get too much error to get class in .java

Original : 
[original.zip](https://github.com/java-deobfuscator/deobfuscator/files/2639211/original.zip)
https://mega.nz/#!1l1RxIIL!9r4CGKrb2_mkzF2OTY0lGOSEo4C8kL7jawvV0Qb0euU

Renamed :
[renamed.zip](https://github.com/Konloch/bytecode-viewer/files/2638176/renamed.zip)
 https://mega.nz/#!Vk0TmQRb!Xh6fVJ9GRCAM3PGqKI9OfRFpWs4MrvBpVw-g6Tn-CbU

I succes (i think) totally renamed version (class name) works well, but after decompilation and backup it does not work anymore, and it lacks a lot of code
I can only edit the code as a string via Smali / Dex
I'd like so much to get the clean code to edit it in eclipse easily
Thank you if anyone can help me

**Comment by ItzSomebody** [comment]
This doesn't look like it was renamed properly.

**Comment by NullHF** [comment]
> This doesn't look like it was renamed properly.

You want the original ?

**Comment by Jerem584** [comment]
xray so easy to do lol
