### ISSUE TITLE
Can you help me obfuscate this? 

### ISSUE THREAD

**Issue by IzzyMichiel** [java-deobfuscator/deobfuscator#341]
Hey,

I was trying to deobfucate this plugin,but I tried everything it gives me errors like this: 
Error: java/lang/Exception could not be found while writing me/.../.../utils/RuRpTAj/TL90Qkv/l7. Using COMPUTE_MAXS

 - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer

Anybody help?

Download: https://cdn.discordapp.com/attachments/522422196648411140/522505993368633374/plugin.jar

**Comment by ItzSomebody** [comment]
Add the required libraries (including rt.jar) to the path.

**Comment by IzzyMichiel** [comment]
> Add the required libraries (including rt.jar) to the path. Also, that error only means the stack frames aren't written, if you are trying to produce only legible code, the frames shouldn't be needed.

Hey, 

Thanks for the fast reply.
This is my current config so everything is included but still unreabale... :(

input: input.jar
output: output.jar
path:
  - C:\Program Files (x86)\Java\jre1.8.0_191\lib\rt.jar
  - C:\Users\....\Desktop\Server.jar
  - C:\Users\....\Desktop\New folder\worldguard-6.2.1.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer

**Comment by ThisTestUser** [comment]
You have to use ClassNormalizer then. Sometimes, the original names are removed completely, and there's no way to retrieve them.

**Comment by IzzyMichiel** [comment]
ThisTestUser,

Ill try to use that when I am home but I mean also code is not readable will that probably fix it?

**Comment by IzzyMichiel** [comment]
> You have to use ClassNormalizer then. Sometimes, the original names are removed completely, and there's no way to retrieve them.

It looks like this, any way to make it more readable?

https://snag.gy/nIQjgi.jpg

**Comment by IzzyMichiel** [comment]
Now made most of the code readable only still some methods couldn't be decompiled. Still something that is obfuscated why the decompiler can't read? Also some classes can't open nullpointerexep

**Comment by ThisTestUser** [comment]
[pluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2682079/pluginDeob.zip)
If you use bytecode viewer, there shouldn't be any decompiling errors.

**Comment by IzzyMichiel** [comment]
> [pluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2682079/pluginDeob.zip)
> If you use bytecode viewer, there shouldn't be any decompiling errors.

Hey,

Thanks, but when I try recompiling in eclipse it gives 5K errors :( 
Like a lot of A can not be resolved etc.. Any suggestions

Thanks,

**Comment by ThisTestUser** [comment]
Recompiling is a whole different issue from deobfuscating, you need the correct libraries to recompile.
You basically have to attach every library (like Spigot.jar) that the files need, but otherwise you're on your own.
