### ISSUE TITLE
Custom obfuscator (for probably hide malware into rat builder)

### ISSUE THREAD

**Issue by NullHF** [java-deobfuscator/deobfuscator#347]
In this software (Ratty) some class has been added, they are obfuscated / encrypted, I can not find out what is hidden is some class that has been added

i succes "illegalSignatureRemover" and some other , but not the encrypt string and renaming
Someone can help me ?

[ratty.zip](https://github.com/java-deobfuscator/deobfuscator/files/2716773/ratty.zip)

**Comment by ThisTestUser** [comment]
[rattyDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2718685/rattyDeob.zip)

**Comment by NullHF** [comment]
> [rattyDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2718685/rattyDeob.zip)

Thanks !

**Comment by NullHF** [comment]
True , ransomware find !
