### ISSUE TITLE
Need Dash-O strings Decrypted

### ISSUE THREAD

**Issue by spongebobe** [java-deobfuscator/deobfuscator#350]
[DashO Obfuscated Client.zip](https://github.com/java-deobfuscator/deobfuscator/files/2721445/DashO.Obfuscated.Client.zip)

Thanks!

**Comment by ThisTestUser** [comment]
Already done.
https://github.com/java-deobfuscator/deobfuscator/issues/295

**Comment by spongebobe** [comment]
This is a much newer version. It uses the same obfuscation though. Please come back ;)

**Comment by TerriblePanda** [comment]
woah! The best exhibition cracker. o/
