### ISSUE TITLE
Can someone convert my updated Dash-O matcher to a transformer?

### ISSUE THREAD

**Issue by spongebobe** [java-deobfuscator/deobfuscator#351]
Here I made what should be a decryption pattern for DashO strings. If anyone knows what to do, feel free to use this in a transformer. If you do make any progress, please leave the transformer in a reply.

public static final InstructionPattern DASHO_DECRYPT_PATTERN = new InstructionPattern(
    		new LoadIntStep(),
            new OpcodeStep(NOP),
            new OpcodeStep(SIPUSH),
            new OpcodeStep(I2C),
            new OpcodeStep(ISUB),
            new LoadIntStep(),
            new OpcodeStep(NOP),
            new OpcodeStep(SIPUSH),
            new OpcodeStep(I2C),
            new OpcodeStep(ISUB),
            new OpcodeStep(LLOAD),
            new OpcodeStep(L2I),
            new InvocationStep(INVOKESTATIC, null, null, "(III)Ljava/lang/String;", false)
    );

**Comment by Janmm14** [comment]
Honestly that is not even one third of the work a transformer likely needs. You just present us some bytecode pattern anyone with a dasho sample jar can find out.

**Comment by ThisTestUser** [comment]
The pattern is not always the same, so the best deobfuscator for DashO is this one: https://github.com/ThisTestUser/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/dasho/StringEncryptionTransformer.java
