### ISSUE TITLE
Can anyone deobf this jar?

### ISSUE THREAD

**Issue by a2692866561** [java-deobfuscator/deobfuscator#352]
Radon :(
https://www.file-upload.net/download-13458394/Remix.jar.html

**Comment by TerriblePanda** [comment]
No, we can't. You're big skidderrrrr!!

**Comment by ThisTestUser** [comment]
[RemixDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2729765/RemixDeob.zip)

**Comment by aidanwd** [comment]
@ThisTestUser please don't deobf my stuff ;(
