### ISSUE TITLE
How do you map an old jar that isn't obfuscated to an obfuscated newer version automatically?

### ISSUE THREAD

**Issue by aidanwd** [java-deobfuscator/deobfuscator#353]
The title says all...

Please let me know if there are any good tools for this, thanks!

**Comment by FinalException** [comment]
Hello, Aidan Dorfler

This might be what you're looking for: http://www.etccatering.com/

Cheers!

**Comment by TerriblePanda** [comment]
> Hello, Aidan Dorfler
> 
> This might be what you're looking for: http://www.etccatering.com/
> 
> Cheers!

Cheers!

**Comment by 0xa00** [comment]
You will need:
1 (15.25 ounce) can corn niblets, drained
1 (15 ounce) can green lentils, drained and rinsed
2 large carrots, finely diced
3 tablespoons olive oil
2 teaspoons curry powder
½ teaspoon salt 

Then: toss corn, lentils, carrots, olive oil, curry powder, and salt in a bowl.
..and you're done! Please let us know what you think!
