### ISSUE TITLE
Unable to deobfuscate jar file

### ISSUE THREAD

**Issue by biepie70** [java-deobfuscator/deobfuscator#356]
I hava a jar file for analysis. Strings suggests  it is allatori obfuscated
![strings](https://user-images.githubusercontent.com/22099619/51013237-80602c00-1589-11e9-8d19-4344b80501b3.JPG)
I used this tool to detect and it says 
![detect](https://user-images.githubusercontent.com/22099619/51013244-8d7d1b00-1589-11e9-9fe8-a74712a8a864.JPG)
And i have no luck deobfuscating this file.
![deobfuscation_failed](https://user-images.githubusercontent.com/22099619/51013257-a2f24500-1589-11e9-914a-09623ca78358.JPG)
Can anyone help me to deobfuscate this file as i need to analyze this file as soon as possible.
This is a malicious jar file so please use a VM to deobfuscate.
Here is the link to the obfuscated file 
[https://ufile.io/lmx3b](url)

**Comment by Janmm14** [comment]
1. Don't use sourcefileclassnormalizer.
2. The error says the config is invalid.

**Comment by ThisTestUser** [comment]
[indicative_nepal_rastra_bnk_dtd_01082019_docxDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2751244/indicative_nepal_rastra_bnk_dtd_01082019_docxDeob.zip)
By the way, you should rename the jar to a zip and upload that instead, as it makes it easier for us to deobfuscate it.
