### ISSUE TITLE
Custom Radon OBF. Deobf this please!

### ISSUE THREAD

**Issue by TerriblePanda** [java-deobfuscator/deobfuscator#358]
Custom Radon. LMFAO    Deobf everything.

https://4lpha.one/dl/1g5msrQcXFhgwwO5lRYRYSSvtYKp3FU8X

**Comment by ThisTestUser** [comment]
[DebugDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2776828/DebugDeob.zip)
Removed assets to save file space.
