### ISSUE TITLE
Zelix can't deobfuscate

### ISSUE THREAD

**Issue by IzzyMichiel** [java-deobfuscator/deobfuscator#362]
Hey,

Could anybody help me deobofcating this?
It's protected with Zelix I guess but when I do string decryption it's still full of errors.

https://cdn.discordapp.com/attachments/436861633223065601/537642814536679474/but.jar

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2787899/output.zip)

**Comment by IzzyMichiel** [comment]
> [output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2787899/output.zip)

Thank you very much, in Bot.class there is a method that blocks some things could I remove that check?
I tried decompiling and importing in Eclipse but got ALOT of errors..

**Comment by ItzSomebody** [comment]
Getting errors after decompiling something is expected and is often something you have to fix yourself.

**Comment by IzzyMichiel** [comment]
> Getting errors after decompiling something is expected and is often something you have to fix yourself.

Yeah I know but I tried using byecode to remove a if statement in bot.class but can't bypass it :(

**Comment by Janmm14** [comment]
> > Getting errors after decompiling something is expected and is often something you have to fix yourself.
> 
> Yeah I know but I tried using byecode to remove a if statement in bot.class but can't bypass it :(

Simply removing an if is not how such stuff can be done.
Also deathbot had multiple checks in the past.

Additionally you might want to remove the remote control stuff where it can be forced to silently attack a server the deathbot owner's server dictates (At least it was in there one or 2 years ago)

**Comment by insane27** [comment]
I managed to remove some versions ago of deathbot (back in august) the check method hehe. I can try again in this new version and if I manage I will PM you with link! Sorry guys for offtopic 💯

**Comment by Janmm14** [comment]
(I don't need it)

**Comment by IzzyMichiel** [comment]
I don't think it's still there.
