### ISSUE TITLE
Need help in deobfuscation!44!!4!4!!!!!!!

### ISSUE THREAD

**Issue by wwdawdad** [java-deobfuscator/deobfuscator#366]
please deob this comrade.
https://anonfile.com/yeh5Dfrfbe/uwu_rar

yeet

**Comment by ThisTestUser** [comment]
Download my deobfuscator. https://github.com/ThisTestUser/deobfuscator/releases
Use allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer.
