### ISSUE TITLE
Help in making custom transformer

### ISSUE THREAD

**Issue by GSharma789** [java-deobfuscator/deobfuscator#367]
Hi dev , i tried deobfuscating a jar with allatori string deobf. and many string got decrypted but still many of them remain encrypted , after searching i get the decryption routine and now those remained string can also be decrypted but doing decryption of each string by manual way is very lengthy process , now i think i need to write transformer for this but don't know how to do , reading help in 'custom transformation writing' did not help me . Any more explaination will be highly appreciated. Thanks

**Comment by ItzSomebody** [comment]
Since you mentioned that some of the strings got decrypted and others didn't, I suspect that there is some kind of flow obfuscation going on. You could try [this](https://github.com/ThisTestUser/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/FlowObfuscationTransformer.java) to see if that helps.

**Comment by GSharma789** [comment]
Thanks . This almost solved my problem

**Comment by GSharma789** [comment]
[X Messenger Privacy Premium 2.8.1-enjarify.zip](https://github.com/java-deobfuscator/deobfuscator/files/2845240/X.Messenger.Privacy.Premium.2.8.1-enjarify.zip)

Here is file. Decryption Routine is in com/john/xmessengerprivacypremium/ModuleChecker.class but want to do it in auto mod by deobfuscator . Please give me best method to do this . tried flow deobfuscation and allatori string deobfuscation also but not all strings in com/john/xmessengerprivacypremium/ are decrypted . @ThisTestUser please help .Thanks

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2846377/output.zip)

**Comment by GSharma789** [comment]
Thanks a lot @ItzSomebody for your great work but i want to know the way you did this . may you share the custom transformer if you made for this ? or let me know any other way how you did

**Comment by ItzSomebody** [comment]
I used [this](https://github.com/java-deobfuscator/deobfuscator/blob/a46a6b02db4f8f393d6d91aa6211ac0818e7485d/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java)

and changed a couple of values in here

```java
    private boolean isAllatoriMethod(Map<Integer, AtomicInteger> insnCount, Map<String, AtomicInteger> invokeCount) {
        //XXX: Better detector
    	if(insnCount.get(Opcodes.IXOR) == null ||
    		insnCount.get(Opcodes.ISHL) == null ||
    			insnCount.get(Opcodes.NEWARRAY) == null ||
    			invokeCount.get("charAt") == null || invokeCount.get("length") == null)
    			return false;
        return ((int) ((insnCount.get(Opcodes.IXOR).get() * 100.0f) / 8)) >= 50 &&
                ((int) ((insnCount.get(Opcodes.ISHL).get() * 100.0f) / 4)) >= 50 &&
                ((int) ((insnCount.get(Opcodes.NEWARRAY).get() * 100.0f) / 1)) >= 100 &&
                ((int) ((invokeCount.get("charAt").get() * 100.0f) / 4)) >= 50 &&
                ((int) ((invokeCount.get("length").get() * 100.0f) / 2)) >= 50;
    }
```

If I recall correctly, there wasn't any bitshifts in some of the decryptors so I removed that part out of the detector.

**Comment by GSharma789** [comment]
Thats Great explaination.

**Comment by GSharma789** [comment]
> I used [this](https://github.com/java-deobfuscator/deobfuscator/blob/a46a6b02db4f8f393d6d91aa6211ac0818e7485d/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java) and changed a couple of values in here

which value you changed , thats main point i want to know. Thanks

**Comment by ItzSomebody** [comment]
private boolean isAllatoriMethod(Map<Integer, AtomicInteger> insnCount, Map<String, AtomicInteger> invokeCount) {
        //XXX: Better detector
    	if(insnCount.get(Opcodes.IXOR) == null ||
    		//insnCount.get(Opcodes.ISHL) == null ||
    			insnCount.get(Opcodes.NEWARRAY) == null ||
    			invokeCount.get("charAt") == null || invokeCount.get("length") == null)
    			return false;
        return ((int) ((insnCount.get(Opcodes.IXOR).get() * 100.0f) / 8)) >= 25 &&
                //((int) ((insnCount.get(Opcodes.ISHL).get() * 100.0f) / 4)) >= 50 &&
                ((int) ((insnCount.get(Opcodes.NEWARRAY).get() * 100.0f) / 1)) >= 100 &&
                ((int) ((invokeCount.get("charAt").get() * 100.0f) / 4)) >= 50 &&
                ((int) ((invokeCount.get("length").get() * 100.0f) / 2)) >= 50;
    }
