### ISSUE TITLE
Help me Deobfu this,pls

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#368]
mEgA.Nz/#!7F5SiIQJ!PooiDc62_doLFryb6kAG_N92gKqbce1Exi5U42cifO0

This is the latest one(no the old one,if someone had uploaded here)
signature check inside
the String in main class  is no obfuscated.

Thanks.

**Comment by TerriblePanda** [comment]
Good morning skidder ho3.

Good luck!

**Comment by CrackFileso** [comment]
@TerriblePanda Yes.You mInEcRafT Cheater and Debug Client ReNaMer

**Comment by CrackFileso** [comment]
Closed,thanks anyway.
