### ISSUE TITLE
Some strings don't deobfuscated

### ISSUE THREAD

**Issue by SinnicK** [java-deobfuscator/deobfuscator#37]
Today I have come across some obfuscate texts (Allatori) that have not been deobfuscated. I don't know why. I let them here, maybe can help to improve the strings deobfuscate.

- [x] Jzh|[M -> **Accept** 
- [x] XHZNI\u007f4Gxe~~xL\\ -> **Accept-Language**
- [x] Hvewnz\u007fpDW -> **Connection**
- [x] @|ni&Xgp]\\ -> **Keep-Alive**
- [ ] mZ,\u0003m\\tdy\\pG0\u0001

Best regards.

**Comment by samczsun** [comment]
Please send the jar to submit@javadeobfuscator.com with the subject "Issue #37"

**Comment by SinnicK** [comment]
Sent @samczsun. Thanks ;).

**Comment by samczsun** [comment]
Will be fixed in next commit (the string decrypts to "firefoxProfile")
