### ISSUE TITLE
Add a DashO Control Flow Transformer

### ISSUE THREAD

**Issue by spongebobe** [java-deobfuscator/deobfuscator#371]
After doing some research and testing, I have come to the conclusion that the DashO Control Flow Obfuscation is what breaks the DashO String Encryption Transformer. Without control flow, ThisTestUser's transformer works perfectly at decrypting 9.2.0 strings. It is when control flow is added to the mix, that strings are unable to be found and decrypted. If samczsun or thistestuser could publicize a DashO control flow transformer, that would improve deobfuscation for all.

**Comment by Enteerman** [comment]
Can you provide a sample?

**Comment by ThisTestUser** [comment]
The transformer was already added (dasho.FlowObfuscationTransformer).
