### ISSUE TITLE
Compile Time Warning In Intellij Idea

### ISSUE THREAD

**Issue by GSharma789** [java-deobfuscator/deobfuscator#372]
![deob](https://user-images.githubusercontent.com/27184655/52544473-e0ebb000-2d65-11e9-9fbe-858890437b0b.JPG)

Hi Dev , Is There Any Fix For Removing These Warning ? Thanks

**Comment by ItzSomebody** [comment]
The first one should not be removed as that is a part of the emulation behavior. Check [this](https://github.com/java-deobfuscator/deobfuscator/pull/248).

The second one, well I don't know. Perhaps you could create a new way or use existing libs to convert an InputStream to a String.
