### ISSUE TITLE
please help me java.lang.ArrayIndexOutOfBoundsException: 29268

### ISSUE THREAD

**Issue by 2902598890** [java-deobfuscator/deobfuscator#373]
I encountered an error during the configuration process.
I am using the latest version of deobfuscator
I am a newbie, I don't know how to solve him.
My Config.yml
----------------------------------------------------------------
output: out.jar
path:
 - "C:\\Program Files\\Java\\jre1.8.0_202\\lib\\rt.jar"
transformers:
 - allatori.StringEncryptionTransformer
======================================
The error I encountered:
G:\fan>java -jar deobfuscator.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input

Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.ArrayIndexOutOfBoundsException: 29268
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(Clas
sReader.java:2659)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassRea
der.java:2676)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader
.java:536)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader
.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator
.java:187)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator
.java:173)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:249)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

I am not used to the operation of github, I am very sorry about this.

**Comment by ThisTestUser** [comment]
Use my deobfuscator: https://github.com/ThisTestUser/deobfuscator/releases

**Comment by GSharma789** [comment]
@ThisTestUser 2 request : FIRST - can you send me your custom transformer created by you when u deobfuscated jasi-patcher on request of that f**king rajesh . I want that one to learn . Please send me at govindsharma111998@gmail.com ( obivisouly not here plz) . SECOND : compiling your cus. deobfuscator only generating some .class file not jar , in intellij idea (manualy zipping them only creats 1 mb file while your jar is approx 9 mb in size, don't know which ide u used for making jar file. May u give me info about your way of compiling or ide ( if link thats great) . Thanks

**Comment by ItzSomebody** [comment]
> @ThisTestUser 2 request : FIRST - can you send me your custom transformer created by you when u deobfuscated jasi-patcher

The code I gave you for that other Allatori sample should work. Also, there's a lot of good transformers to learn from that already exist in java-deobfuscator.

> SECOND : compiling your cus. deobfuscator only generating some .class file not jar , in intellij idea (manualy zipping them only creats 1 mb file while your jar is approx 9 mb in size, don't know which ide u used for making jar file. May u give me info about your way of compiling or ide ( if link thats great) . Thanks

You have to build it with Maven.

**Comment by GSharma789** [comment]
@ItzSomebody thanks for answer but i am already trying to compile it as maven project . It completed with 3 warning & .class files are generated but still missing a lot of code although all dependency is resolved.

**Comment by ItzSomebody** [comment]
> @ItzSomebody thanks for answer but i am already trying to compile it as maven project . It completed with 3 warning & .class files are generated but still missing a lot of code although all dependency is resolved.

Are you exporting a JAR or are you actually building it via `mvn clean package`?

**Comment by GSharma789** [comment]
I am using intellij idea and importing directly from github assign the project as maven due to pom.xml and start resolving dependency . Now after 3 warning building completed and a 'target' folder generated but don't contains jar only has .class . Don't know what to do as never build jar before . Does i need different ide ?

**Comment by ItzSomebody** [comment]
Exporting a JAR is not the same as building the software as a Maven project. In IntelliJ, there is a Maven tab which contains a set of actions under the tab `Lifecycle`. Hit `clean` and `package`.

**Comment by GSharma789** [comment]
@ItzSomebody great . now its compiled & working . Removed 1 decryption routine and decrypted 256 strings but issue is code is not decompiled properly in any of decompiler in bytecodeviewer (only showing //decompiled failed and all byte code here ) not java code. If you don't mind may you send me that modified java file with your code . Seems i am doing something wrong. thanks

**Comment by GSharma789** [comment]
![ttttt](https://user-images.githubusercontent.com/27184655/52865194-e3952f00-30f0-11e9-8475-5243d3c5ccbc.JPG)
Tried Maven clean package and get this result
![d](https://user-images.githubusercontent.com/27184655/52865253-13443700-30f1-11e9-83ec-b9cd05f533eb.jpg)
and this is error where can i allocate higher ram ?

**Comment by ThisTestUser** [comment]
@GSharma789 I basically used dex2jar and then slightly modified allatori.StringEncryptionTransformer (similar to ItzSomebody's modification).

**Comment by GSharma789** [comment]
@ThisTestUser i tried same modification by itzsomebody but string decrypted in weired form . Please tell me exact modification what you used . Thanks

**Comment by Janmm14** [comment]
@GSharma789
He uses his fork as base for the modifications of the transformer.

**Comment by GSharma789** [comment]
@Janmm14 i am also trying his folk and trying to modify code

**Comment by ThisTestUser** [comment]
@GSharma789 https://gist.github.com/ThisTestUser/ebd606f4a1513c6ae0c4fd4706f51376
To be honest though, decrypting the strings barely improved the readability of the code.

**Comment by GSharma789** [comment]
you are right @ThisTestUser but i am noob in reversing field , not good like you so depend on strings . Although i don't want to decrypt the string for that apk as creater of that apk is too good man and i respect him , due to sit request of rajesh-12345 i get that decrypted jar so want to learn how you did . Anyway great thanks for code link . Any more place where i can contact you other than discord? Like google+ , telegram etc

**Comment by GSharma789** [comment]
@ThisTestUser well i get your code , if you can delete link thats will be great help as to stop others from decrypting patcher again. and request you to not decrypt that apk again for any others request.Thanks

**Comment by GSharma789** [comment]
@ThisTestUser plz delete the link

**Comment by Janmm14** [comment]
@GSharma789 I do not think he cares about that.

**Comment by GSharma789** [comment]
@Janmn14 may be he think about it or not but i hope that he will think about it . He has too much helping nature so hope is there

**Comment by GSharma789** [comment]
@Janmm14 I hope he will think about it. He has very helping nature

**Comment by 2902598890** [comment]
> 使用我的反混淆器：[https](https://github.com/ThisTestUser/deobfuscator/releases)：[//github.com/ThisTestUser/deobfuscator/releases](https://github.com/ThisTestUser/deobfuscator/releases)

Thank you very much for your help, now I have a new question.
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space


I am using deobfuscator-gui to match deobfuscator

**Comment by ThisTestUser** [comment]
You have to use -Xmx to launch deobfuscator-gui.

**Comment by 2902598890** [comment]
> You have to use -Xmx to launch deobfuscator-gui.

Thank you very much for your help
