### ISSUE TITLE
zip_slip

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [java-deobfuscator/deobfuscator#374]
Hi,
There is a zip_slip vulnerability found by Qihoo360 CodeSafe Team.
Details are as follows:
In deobfuscator/src/main/java/com/javadeobfuscator/deobfuscator/utils/Utils.java
![default](https://user-images.githubusercontent.com/39950310/52700755-a70fe900-2fb3-11e9-9954-f0c00794b579.png)
Since the entry name is not checked, the attacker can construct a jar file with "../" for path penetration to overwrite any .class file.

**Comment by Janmm14** [comment]
This is no vulnerability, because the deobfuscator is not saving the unzipped files on disc.
