### ISSUE TITLE
Is there a way to rename classes that are numbers or decompile them

### ISSUE THREAD

**Issue by Nubebuster** [java-deobfuscator/deobfuscator#378]
I successfully ran this deobfuscator! But the code has package and classnames as numbers. This makes me unable to recompile. Is there a feature that renames classnames?
[edit] Or is there a way to recompile classes and packages as numbers?
renaming makes the logger etc. break because the logging and UI are based on class names

**Comment by Janmm14** [comment]
The deobfuscator provides optional transformers which do this.

This looks like you just used everything available.

**Comment by Nubebuster** [comment]
@Janmm14 The obfuscated source itself has those names.

Update: I managed to fix the issue by editing byte code directly
