### ISSUE TITLE
Stringer 3 Issue

### ISSUE THREAD

**Issue by GSharma789** [java-deobfuscator/deobfuscator#379]
[deleted]

**Comment by ItzSomebody** [comment]
So, you go overboard when another dev posts a link to an app yet you feel perfectly comfortable leaking corporate software. Lol.

As far as I can see, there is no error there.

**Comment by GSharma789** [comment]
thats not my leak , downloaded from cracked link . search on google 'stringer 3 cracked ' u will get it

**Comment by GSharma789** [comment]
first result from google search of workupload site contain stringer 3.0.3 cracked zip so i don't think i am leaking it.

**Comment by ItzSomebody** [comment]
I know exactly where that came from as I recognized the manifest entries. My point being, it's still being redistributed... by you.

**Comment by samczsun** [comment]
I don't want to deal with DMCAs so please don't put me in a position where I need to
