### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by SchoolsCool** [java-deobfuscator/deobfuscator#38]
Error while deobfuscating a jar - 

[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 2186 encrypted strings
Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
	at java.lang.reflect.Array.get(Native Method)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:101)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:426)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:204)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:61)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

https://www.dropbox.com/s/bs2cq59lngje1jj/stringerx1.jar?dl=0

Here's the link to the file if you need it

**Comment by samczsun** [comment]
The file appears to be deobfuscated already (?)

**Comment by SchoolsCool** [comment]
If you go to the class com.licel.a.a.c you will see some strings are still obfuscated

**Comment by SchoolsCool** [comment]
Didn't mean to do that

**Comment by Janmm14** [comment]
@SchoolsCool Try to run some deobfuscator again

**Comment by SchoolsCool** [comment]
Same error

**Comment by SchoolsCool** [comment]
It is just skipping some strings, it skips from 60% to being done. 

Reading complete. Loading hierachy


Transforming

[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Found 8105 invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Inlining invokedynamic
[Stringer] [InvokedynamicTransformer] Done 10%
[Stringer] [InvokedynamicTransformer] Done 20%
[Stringer] [InvokedynamicTransformer] Done 30%
[Stringer] [InvokedynamicTransformer] Done 40%
[Stringer] [InvokedynamicTransformer] Done 50%
[Stringer] [InvokedynamicTransformer] Done 60%
[Stringer] [InvokedynamicTransformer] Done 70%
[Stringer] [InvokedynamicTransformer] Done 80%
[Stringer] [InvokedynamicTransformer] Done 90%
[Stringer] [InvokedynamicTransformer] Done 100%
[Stringer] [InvokedynamicTransformer] Removed 8105 invokedynamic instructions, took 47s
[Stringer] [InvokedynamicTransformer] Cleaning up bootstrap methods
[Stringer] [InvokedynamicTransformer] Removed 0 bootstrap methods
[Stringer] [InvokedynamicTransformer] Done
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 6342 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Done 40%
[Stringer] [StringEncryptionTransformer] Done 50%
[Stringer] [StringEncryptionTransformer] Done 60%
[Stringer] [StringEncryptionTransformer] Decrypted 4160 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 1 decryption classes
[Stringer] [StringEncryptionTransformer] Done

**Comment by samczsun** [comment]
Can you send me the original, non-deobfuscated, file?

**Comment by SchoolsCool** [comment]
You will have to unzip it
[stringer copy.zip](https://github.com/java-deobfuscator/deobfuscator/files/348631/stringer.copy.zip)

**Comment by samczsun** [comment]
Fixed in upcoming commit (assuming com.licel.a.a.c is a good indicator of whether it has been fixed or not)
