### ISSUE TITLE
Using COMPUTE_MAXS??

### ISSUE THREAD

**Issue by v54088** [java-deobfuscator/deobfuscator#380]
Hello everyone, why is this happening, how to solve it?? 
Error: com/google/protobuf/ByteString could not be found while writing n/bv. Using COMPUTE_MAXS

**Comment by ItzSomebody** [comment]
That comes from [this line](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java#L483).

It indicates that it was unable to find a class when it was attempting to rebuild the stackmap frames. It's not really important as the frames aren't needed to decompile / view source. However, if you wish to have the frames generated, you would have to find all libraries the program you are deobfuscating utilizes and add it to java-deobfuscator's classpath.

**Comment by v54088** [comment]
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 316ms
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted 0 strings
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: com/google/protobuf/ByteString could not be found while writing n/bv. Using COMPUTE_MAXS

I joined them but still the same，plz help me.

**Comment by v54088** [comment]
[Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 156ms
[Thread-10] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted 0 strings
[Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing

Can not  Decompile ?

**Comment by GSharma789** [comment]
dev or thistestuser or itzsomebody will say 'SEND THE JAR HERE IF YOU CAN' .so i said before them

**Comment by ItzSomebody** [comment]
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
> [ClassLoader] An attempt was made to load the library zip.dll
> Initialization of VM took 156ms
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted 0 strings
> [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
> 
> Can not Decompile ?

Are you saying either:

* You are unable to decompile the jar using a tool like FernFlower?
* There is obfuscation present but the transformer but it's not deobfuscating it?

**Comment by v54088** [comment]
[test13.jar](https://mega.nz/#!g551yYhD!zk-WbFnIxfouAcbteWNyuia_zBmgEnaqh3aaSwZXsIw)

**Comment by v54088** [comment]
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator  - 加載類路徑
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator  - 加載輸入
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator  - 計算調用者
> > [Thread] -10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator  - 轉換
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator  - 運行com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer 
> > [ClassLoader]試圖加載庫zip.dll 
> > 初始化VM需要156ms 
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer  - 解密0個字符串
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator  - 寫作
> > 不能反編譯？
> 
> 你是說：
> 
> * 您無法使用像FernFlower這樣的工具反編譯jar？
> * 存在混淆但是變壓器卻沒有反混淆它？



> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
> > [ClassLoader] An attempt was made to load the library zip.dll
> > Initialization of VM took 156ms
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted 0 strings
> > [Thread-10] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
> > Can not Decompile ?
> 
> Are you saying either:
> 
> * You are unable to decompile the jar using a tool like FernFlower?
> * There is obfuscation present but the transformer but it's not deobfuscating it?

Only AA BB BZ AB these characters

**Comment by Janmm14** [comment]
Class names, method names and variable names cannot be recovered.

**Comment by v54088** [comment]
> 無法恢復類名，方法名和變量名。

ok,Is there a way to do this?
[demo.exe](https://mega.nz/#!o5xUFKia!PLgQ3DZMkWrKSzlghQx2BbLIeQwp1yWLlirVt-1nnIM)

It is using JAVA

**Comment by GSharma789** [comment]
classname for this test123.jar can be recovered by using normalizer.sourcefileclassnormalizer.

**Comment by Slowftw** [comment]
> That comes from [this line](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java#L483).
> 
> It indicates that it was unable to find a class when it was attempting to rebuild the stackmap frames. It's not really important as the frames aren't needed to decompile / view source. However, if you wish to have the frames generated, you would have to find all libraries the program you are deobfuscating utilizes and add it to java-deobfuscator's classpath.

and how do I do that?

**Comment by ItzSomebody** [comment]
Old issue and I believe the OP's questions were sufficiently answered. Closing.
