### ISSUE TITLE
Strings don't deobfuscated

### ISSUE THREAD

**Issue by Argentoz** [java-deobfuscator/deobfuscator#381]
I'm trying deobf this jar : https://dropmefiles.com/16SxI
But nothing works.
Pls help. :/

**Comment by ItzSomebody** [comment]
```yaml
- zelix.string.EnhancedStringEncryptionTransformer
- stringer.StringEncryptionTransformer
- stringer.StringEncryptionTransformer
- zelix.FlowObfuscationTransformer
```

In that order.

**Comment by Argentoz** [comment]
[https://imgur.com/a/31Yhrji](url) did not help

**Comment by ItzSomebody** [comment]
Make sure you use the stringer.StringEncryptionTransformer twice.

**Comment by Argentoz** [comment]
Yep

**Comment by ItzSomebody** [comment]
Oh, I forgot... in my private fork I prevent removal of the Stringer classes. Whoops. 

In that case, you'll want to comment out lines 52 and 53 [from here](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/stringer/StringEncryptionTransformer.java) and then recompile the deobfuscator.

**Comment by GSharma789** [comment]
Wow @ItzSomebody you own your private fork . May you tell which transformer you have which are absent in this master branch ?

**Comment by ItzSomebody** [comment]
> Wow @ItzSomebody you own your private fork . May you tell which transformer you have which are absent in this master branch ?

A lot and why does it matter?

**Comment by GSharma789** [comment]
Awesome . Just curious to know . It does not matter
