### ISSUE TITLE
Can't deobf last verision ZKM

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#388]
I can't deobf last version ZKM, please, deobf that jar :(

Jar: https://www.upload.ee/files/9765966/MAC.jar.html
Obfuscation: ZKM

**Comment by ItzSomebody** [comment]
I don't see any zelix in there. Just some name obfuscation which can't be reversed.

My best suggestion would be to try using java-deobfuscator's normalizers.

**Comment by Xed0sS** [comment]
Oh, it's my mistake, sorry

Jar: https://www.upload.ee/files/9765966/MAC.jar.html

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/3025786/output.zip)

That's radon, not zelix.
