### ISSUE TITLE
NullPointerException :/

### ISSUE THREAD

**Issue by Argentoz** [java-deobfuscator/deobfuscator#390]
Tried to deobfuscate this jar: https://dropmefiles.com/O9xSj
Logs: https://hastebin.com/tuguqotuma.cs

Transformers:
zelix.string.EnhancedStringEncryptionTransformer
stringer.StringEncryptionTransformer
stringer.StringEncryptionTransformer
zelix.FlowObfuscationTransformer

**Comment by ThisTestUser** [comment]
[launcherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3077969/launcherDeob.zip)
