### ISSUE TITLE
Can't deobfuscator maybe not support?

### ISSUE THREAD

**Issue by 2902598890** [java-deobfuscator/deobfuscator#391]
private static String llIllIIllIIlIl(String llllllllllllllIIlIllIlIlIlIlIlll, String llllllllllllllIIlIllIlIlIlIlIllI) {
      try {
         SecretKeySpec llllllllllllllIIlIllIlIlIlIlIlIl = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(llllllllllllllIIlIllIlIlIlIlIllI.getBytes("UTF-8")), "Blowfish");
         Cipher llllllllllllllIIlIllIlIlIlIlIlII = Cipher.getInstance("Blowfish");
         llllllllllllllIIlIllIlIlIlIlIlII.init(lIIllIIIIllll[2], llllllllllllllIIlIllIlIlIlIlIlIl);
         return new String(llllllllllllllIIlIllIlIlIlIlIlII.doFinal(Base64.getDecoder().decode(llllllllllllllIIlIllIlIlIlIlIlll.getBytes("UTF-8"))), "UTF-8");
      } catch (Exception var4) {
         var4.printStackTrace();
         return null;
      }
   }
}
as well as:

   private static String llIllIIllIIIll(String llllllllllllllIIlIllIlIlIlIIllII, String llllllllllllllIIlIllIlIlIlIIlIll) {
      try {
         SecretKeySpec llllllllllllllIIlIllIlIlIlIIllIl = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(llllllllllllllIIlIllIlIlIlIIlIll.getBytes("UTF-8")), lIIllIIIIllll[8]), "DES");
         Cipher llllllllllllllIIlIllIlIlIlIIlllI = Cipher.getInstance("DES");
         llllllllllllllIIlIllIlIlIlIIlllI.init(lIIllIIIIllll[2], llllllllllllllIIlIllIlIlIlIIllIl);
         return new String(llllllllllllllIIlIllIlIlIlIIlllI.doFinal(Base64.getDecoder().decode(llllllllllllllIIlIllIlIlIlIIllII.getBytes("UTF-8"))), "UTF-8");
      } catch (Exception var4) {
         var4.printStackTrace();
         return null;
      }
   }
What is this obfuscator?

And whether it can be deobfuscator

**Comment by ItzSomebody** [comment]
That would be [this obfuscator](https://github.com/superblaubeere27/obfuscator).

The deobfuscator alone does not support it so custom transformers have to be added for it.

**Comment by 2902598890** [comment]
> 那将是[这个混淆器](https://github.com/superblaubeere27/obfuscator)。
> 
> 单独的反混淆器不支持它，因此必须为其添加自定义变换器。

This is too bad
