### ISSUE TITLE
Cant deobfuscate this jar. Someone help.

### ISSUE THREAD

**Issue by SystemRestored** [java-deobfuscator/deobfuscator#392]
Can some one deobfuscate this jar file I could not deobfuscate it.

https://drive.google.com/file/d/1DhIpKWadjhvUKFgCqHzqVD4es-qerOAv/view?usp=sharing

The following error is giving I dont know why.. used v3 stringEncryption , v3 HideAccess,  v3 Invoked dynamic
![image](https://user-images.githubusercontent.com/32890494/56186138-0cc43400-603c-11e9-8e4b-c64b4289794c.png)

**Comment by ThisTestUser** [comment]
The JAR doesn't appear to be obfuscated.
