### ISSUE TITLE
Can't deobf radon

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#393]
I can't deobf that jar, radon is hardcored obfuscator, I wanna die, please, somebody once tolde me =))))) (somebody deobf jar <3)

Jar: https://www.upload.ee/files/9856293/cases-0.1-client-obf.jar.html
Obfuscator: Radon

**Comment by Janmm14** [comment]
Skid?

**Comment by ItzSomebody** [comment]
That's a pretty lightly obfuscated JAR. Pretty sure you could just edit [this](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/stringer/InvokedynamicTransformer.java) and deobfuscate it.

**Comment by Xed0sS** [comment]
It's impossible 4 me, deobf pls :\
