### ISSUE TITLE
Can someone help me deobfuscate this jar?

### ISSUE THREAD

**Issue by BaiYeLoser** [java-deobfuscator/deobfuscator#395]
Can someone help me deobfuscate this jar?
I can't deobfuscate it myself
https://www.dropbox.com/s/6907x4f5d1du9f4/help.zip?dl=0
thx

**Comment by Janmm14** [comment]
There is nothing to deobfuscate.
Just some variables and functions were renamed to AllatoriXDemo, there is no flow obfuscation, no reflection obfuscation and strings weren't changed too.

**Comment by BaiYeLoser** [comment]
> There is nothing to deobfuscate.
> Just some variables and functions were renamed to AllatoriXDemo, there is no flow obfuscation, no reflection obfuscation and strings weren't changed too.

So how can I directly view its source code?
