### ISSUE TITLE
Cannot deobfuscate jar file (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by marnix409** [java-deobfuscator/deobfuscator#396]
Tried to deobfuscate a jarfile, but it didn't work..
This got printed: 

> Deobfuscation failed. Please open a ticket on GitHub and provide the following e
> rror:
> java.lang.ArrayIndexOutOfBoundsException: 2114752
>         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:171)
>         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator
> .java:185)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator
> .java:173)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
> a:249)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
> in.java:120)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
> in.java:92)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
> ain.java:50)

Could someone help me with this error?

Thanks!

**Comment by outpoints** [comment]
Did you figure it out?

**Comment by Dymeth** [comment]
Same:

> java.lang.ArrayIndexOutOfBoundsException: 3258
>         at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
>         at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676)
>         at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628)
>         at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
>         at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
>         at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ItzSomebody** [comment]
Since this wasn't addressed and is old at this point, I'll be closing the issue. If any of you are still having this issue, feel free to reopen.
