### ISSUE TITLE
ZKM 7.0.7E

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#397]
zelix class master 7.0.7E not deobfuscate 
jar link -> https://mega.nz/#!26IzxA5b!z101WC2xJph_AXoicRLELsaLoQEUsuuf2N0mUAtlRhc

**Comment by ThisTestUser** [comment]
[launcherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3170446/launcherDeob.zip)

**Comment by lolka13372** [comment]
Thanks!
What tools do you use for deobfuscation?
