### ISSUE TITLE
Cancel it. or Closed it

### ISSUE THREAD

**Issue by MrAlecroYT** [java-deobfuscator/deobfuscator#398]

**Comment by ThisTestUser** [comment]
[pluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3170462/pluginDeob.zip)

**Comment by MrAlecroYT** [comment]
Thanks

**Comment by MrAlecroYT** [comment]
![image](https://user-images.githubusercontent.com/36608550/57587432-04f59380-7505-11e9-9396-dab72fa675bc.png)
This is normal?

**Comment by lolka13372** [comment]
Luyten 0.5.33 Normal decompilation
![image](https://user-images.githubusercontent.com/50153944/57588438-d5eb1c00-751c-11e9-8e0c-fc4b1973c983.png)
