### ISSUE TITLE
Which obfuscator used for this plugin ?

### ISSUE THREAD

**Issue by LeakMania-v6** [java-deobfuscator/deobfuscator#399]
![Capture](https://user-images.githubusercontent.com/48015201/57790509-2c35a600-773b-11e9-83f3-7344b7874f37.PNG)

**Comment by Foxxite** [comment]
How about you stop infringing someone's copyright. People like you are the reason we have to obfuscate our software.

**Comment by LeakMania-v6** [comment]
The owner of SuperLuckyBlock doesen't legally have copyright lmao...

**Comment by LeakMania-v6** [comment]
The owner of SuperLuckyBlock doesen't legally have copyrights lmao...

**Comment by LeakMania-v6** [comment]
The owner of SuperLuckyBlock doesen't legally have copyrights lmao...

**Comment by PrankAlien** [comment]
Ok, but I explain you how this works. 
You have a car and i like it, but I don't wanna ask or pay for it so I decide to rob it, how do you feel in that moment ?

**Comment by LeakMania-v6** [comment]
We will stole a new car to resell it. (I'm joking.)

**Comment by PrankAlien** [comment]
But why you want his code ?

**Comment by LeakMania-v6** [comment]
I only asked the obfuscator, not the code.
I wanna use the same obfuscator for some programs.

**Comment by PrankAlien** [comment]
Then ask for it and don't try to deobfuscate his code.

**Comment by LeakMania-v6** [comment]
Cracks can be benefit for developers, look Minecraft...
Mojang tolerate cracks because they know that help Minecraft to be more famous and cracks didn't stop Mojang making money with his game.

**Comment by Foxxite** [comment]
If you really want tot know. It's Denuvo.
https://en.wikipedia.org/wiki/Denuvo

**Comment by LeakMania-v6** [comment]
That also help users to test plugins before purchasing.

**Comment by LeakMania-v6** [comment]
> If you really want tot know. It's Denuvo.
> https://en.wikipedia.org/wiki/Denuvo

Denuvo is the greatest joke i ever seen in my life.

**Comment by Foxxite** [comment]
Well I guess it shouldn't be a problem for you to deobfuscate I guess

**Comment by PrankAlien** [comment]
This is the best obfuscator that I know.
But it costs a lot https://www.zelix.com/klassmaster/featuresZKMScript.html

**Comment by LeakMania-v6** [comment]
> Well I guess it shouldn't be a problem for you to deobfuscate I guess

As i said, i don't want to deobfuscate his plugin because an LM user already cracked his plugin for me...
I only want to use this obfuscator for peronal reasons.
If i'll ask to the SuperLuckyBlock dev, i think he will ignore me. :d

**Comment by LeakMania-v6** [comment]
> This is the best obfuscator that I know.
> But it costs a lot https://www.zelix.com/klassmaster/featuresZKMScript.html

Ok ty. ;)

**Comment by 0-x-2-2** [comment]
> The owner of SuperLuckyBlock doesen't legally have copyrights lmao...

🤡

**Comment by ProSavage** [comment]
That's my friends obfuscator, you cannot actually buy it as it's between friends.

**Comment by LeakMania-v6** [comment]
> That's my friends obfuscator, you cannot actually buy it as it's between friends.

Lulz.

**Comment by ItzSomebody** [comment]
> That's my friends obfuscator, you cannot actually buy it as it's between friends.

I can verify this as I work for the manufacture in question.

**Comment by ItzSomebody** [comment]
> > That's my friends obfuscator, you cannot actually buy it as it's between friends.
> 
> Lulz.

I can verify this to be true.

**Comment by LeakMania-v6** [comment]
> I can verify this to be true.

K.

**Comment by Demeng7215** [comment]
> 
> 
> > I can verify this to be true.
> 
> K.

I can verify as well.

**Comment by LeakMania-v6** [comment]
> > > I can verify this to be true.
> > 
> > 
> > K.
> 
> I can verify as well.

?

**Comment by rucko24** [comment]
@Janmm14 LMFAOOO
