### ISSUE TITLE
# Can someone help me deobfuscate this jar?

### ISSUE THREAD

**Issue by suubix** [java-deobfuscator/deobfuscator#400]
Can someone help me deobfuscate this jar?
I can't deobfuscate it myself
https://workupload.com/file/n9TFFe22
thanks <3

**Comment by ThisTestUser** [comment]
[ApexCheatDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3194125/ApexCheatDeob.zip)
Your main class is at package3/Class40. Everything else is garbage.

**Comment by n1c0la2** [comment]
thanks
