### ISSUE TITLE
Can someone help me deobfuscate this jar?

### ISSUE THREAD

**Issue by Alkazuz** [java-deobfuscator/deobfuscator#401]
Allatori can not be deobfuscator, can someone help 
me?

[ob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3198317/ob.zip)

**Comment by Janmm14** [comment]
Use this deobfuscator with https://github.com/ThisTestUser/deobfuscator/releases with transformer com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer

**Comment by ThisTestUser** [comment]
[obDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3200546/obDeob.zip)

**Comment by Janmm14** [comment]
Why? He could've just done it himself lol
