### ISSUE TITLE
ZKM 5.5.8 not deobfuscate

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#402]
jar: https://mega.nz/#!zqhAmQDT!_wY8dOBF4ZnR_WCgkHInjcxkuCklTeIKJtFj55_gdWM

**Comment by ThisTestUser** [comment]
[manploitDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3220400/manploitDeob.zip)
There is a bug in the custom string encryption, so the plugin wouldn't work anyways.

**Comment by lolka13372** [comment]
@ThisTestUser Corrected everything works too thanks!!
