### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project deobfuscator: Compilation failure -> [Help 1]

### ISSUE THREAD

**Issue by LeakMania-v6** [java-deobfuscator/deobfuscator#403]
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.288 s
[INFO] Finished at: 2019-05-30T14:21:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project deobfuscator: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by Janmm14** [comment]
the actual compilation error is further up in the maven log

**Comment by LeakMania-v6** [comment]
> the actual compilation error is further up in the maven log

I imported the project into Eclipse to show syntax errors and i think it's because there are many errors on it:
![Capture](https://user-images.githubusercontent.com/48015201/58634051-8fead200-82ea-11e9-8935-d1db00183860.PNG)

**Comment by Janmm14** [comment]
These errors are some configuration issue on your side. Maybe you compiled / set this project up this with java 6 which doesn't support generics infering. This repo was not changed since more than 1 full year, oher peopel would have noticed this already.
Also the build on the ci went through without issues: https://ci.samczsun.com/job/java-deobfuscator/job/Deobfuscator/

**Comment by LeakMania-v6** [comment]
> These errors are some configuration issue on your side. Maybe you compiled / set this project up this with java 6 which doesn't support generics infering. This repo was not changed since more than 1 full year, oher peopel would have noticed this already.
> Also the build on the ci went through without issues: https://ci.samczsun.com/job/java-deobfuscator/job/Deobfuscator/

Ok, ty.
Also i don't use Java 6, i use Java 8 and that worked before i upgrade to Windows 10.
(I was on Windows 7 before.)
