### ISSUE TITLE
This jar wont work with the libary any help?

### ISSUE THREAD

**Issue by MikeDoge9** [java-deobfuscator/deobfuscator#404]
The application gets an array out of bounds error on this jar
Any help?

[JAR.zip](https://github.com/java-deobfuscator/deobfuscator/files/3242479/JAR.zip)

**Comment by ThisTestUser** [comment]
[oscrackDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3269885/oscrackDeob.zip)
[oscrackDeobRename.zip](https://github.com/java-deobfuscator/deobfuscator/files/3269886/oscrackDeobRename.zip)
