### ISSUE TITLE
Allatori 6.9 not deobfuscate

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#405]
Allatori 6.9 library demo not deobfuscate
jars: https://mega.nz/#!brxjmQAR!7_l88BnYWYWEAst8EOIANDE052iyTyTvMESY5oqj9CE

**Comment by ThisTestUser** [comment]
[allatoriDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3249068/allatoriDeob.zip)

**Comment by lolka13372** [comment]
@ThisTestUser Thx
