### ISSUE TITLE
Can someone deobfuscate this jar? (Allatori)

### ISSUE THREAD

**Issue by Alkazuz** [java-deobfuscator/deobfuscator#406]
Downlod:
https://www.sendspace.com/file/e1i3uz

**Comment by ThisTestUser** [comment]
Your archive is corrupt. Could you try uploading it via github instead.
Also, try using https://github.com/ThisTestUser/deobfuscator/releases and selecting allatori.StringEncryptionTransformer first.

**Comment by Alkazuz** [comment]
Its not work

**Comment by ThisTestUser** [comment]
ZIP your jar and reupload the file, as the zip is broken.

**Comment by Alkazuz** [comment]
https://anonfile.com/J8p6nfu2nf/nLogin_jar

**Comment by Alkazuz** [comment]
> 
> 
> ZIP your jar and reupload the file, as the zip is broken.

https://anonfile.com/J8p6nfu2nf/nLogin_jar

**Comment by ThisTestUser** [comment]
[nLoginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3267844/nLoginDeob.zip)

**Comment by Alkazuz** [comment]
> 
> 
> [nLoginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3267844/nLoginDeob.zip)

Thankx, can u send me the tool?

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/deobfuscator/releases
localVariableRemover, allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer

**Comment by Alkazuz** [comment]
Ok thankx
