### ISSUE TITLE
# Can someone help me deobfuscate this jar?

### ISSUE THREAD

**Issue by suubix** [java-deobfuscator/deobfuscator#407]
Can someone help me deobfuscate this jar?
I can't deobfuscate it myself
https://workupload.com/file/CMfbbP9F
thanks <3

**Comment by ThisTestUser** [comment]
[VeivDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3262760/VeivDeob.zip)

**Comment by n1c0la2** [comment]
kiss <3

**Comment by suubix** [comment]
kiss <3

**Comment by suubix** [comment]
![image](https://user-images.githubusercontent.com/24918242/59059303-e930a380-889e-11e9-9b78-363cd26d117e.png)
?

**Comment by ItzSomebody** [comment]
> ![image](https://user-images.githubusercontent.com/24918242/59059303-e930a380-889e-11e9-9b78-363cd26d117e.png)
> ?

That's a result of synthetic flags. I suggest you use a better decompiler.
