### ISSUE TITLE
Unknown obfuscator possible superblaubeere27

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#410]
for deobfuscate jar file: https://mega.nz/#!0uAAkIoK!ZmYdncMy3w_zIS4ps6VR_s0JLrkAnmEOcBSS6xZAPag

**Comment by ThisTestUser** [comment]
[Show HWID TsunamiDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3294202/Show.HWID.TsunamiDeob.zip)

**Comment by lolka13372** [comment]
@ThisTestUser Thanks

**Comment by Alkazuz** [comment]
> 
> 
> [Show HWID TsunamiDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3294202/Show.HWID.TsunamiDeob.zip)

what your tool to deobfuscate superblaubeere27 obfuscator

**Comment by ThisTestUser** [comment]
My own. You'll have to ask me to deobfuscate it for you.

**Comment by CrazyMentos** [comment]
> Мой собственный. Тебе придется попросить меня разоблачить это для тебя.
Hi, can you make out this mod?
https://mega.nz/#!UUs3RILS!2PJq0OcwSvGR4Yr9YVM13k3cgs-AHOJVBnzv7-YVjW8

**Comment by Wandover** [comment]
> My own. You'll have to ask me to deobfuscate it for you.

How to get it?

**Comment by Janmm14** [comment]
> 
> 
> > My own. You'll have to ask me to deobfuscate it for you.
> 
> How to get it?

You cannot get his deobfuscator. It stays his own.

**Comment by postrequest69** [comment]
> My own. You'll have to ask me to deobfuscate it for you.

Do you still do this?

**Comment by Janmm14** [comment]
> > My own. You'll have to ask me to deobfuscate it for you.
> 
> Do you still do this?

There is a superblaubeere transformer available now.

**Comment by kiwizn** [comment]
@ThisTestUser deobfuscate this? http://www.mediafire.com/file/frse3kboxpqz36s/SkyWarsPl.jar/file

**Comment by postrequest69** [comment]
> > > My own. You'll have to ask me to deobfuscate it for you.
> > 
> > 
> > Do you still do this?
> 
> There is a superblaubeere transformer available now.

I don't seem to see it in the transformer list? It's also not given via detection. Have you used it and if so could you give me a hand? if you have discord mine is Philippine eagle#0069

**Comment by Janmm14** [comment]
> > > > My own. You'll have to ask me to deobfuscate it for you.
> > > 
> > > 
> > > Do you still do this?
> > 
> > 
> > There is a superblaubeere transformer available now.
> 
> I don't seem to see it in the transformer list? It's also not given via detection. Have you used it and if so could you give me a hand? if you have discord mine is Philippine eagle#0069

Then you probably have an old version of the deobfuscator. its special.SuperblaubeereTransformer
