### ISSUE TITLE
Unknown obfuscator 

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#415]
jars: https://mega.nz/#!62oikaLL!JQt13TUqAiFZOB6ha2PlBbE3eTdtrsBK4_FPyq03oug

**Comment by ItzSomebody** [comment]
Looks like a fork of my obfuscator.

**Comment by lolka13372** [comment]
@ItzSomebody 
Can it be deobfuscated?

**Comment by lolka13372** [comment]
@ItzSomebody 
Send me the deobfuscated file as soon as it is ready

**Comment by ItzSomebody** [comment]
As a general rule of thumb, anything that can be executed by the computer can be reversed - especially as far as Java is concerned.

**Comment by lolka13372** [comment]
@ItzSomebody 
Can you send me the code that you received otherwise it can not be?
