### ISSUE TITLE
Impossible obfuscation

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#417]
Sup, I can't deobf that jar and I don't understand what kind of obfuscator he belong, please, help and deobf if you can, thanks <3

Jar: https://www.upload.ee/files/10173355/Launcher.jar.html
Obfuscator: Unknown

**Comment by ThisTestUser** [comment]
[LauncherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3363715/LauncherDeob.zip)
[LauncherDeobRenamed.zip](https://github.com/java-deobfuscator/deobfuscator/files/3363716/LauncherDeobRenamed.zip)

**Comment by Xed0sS** [comment]
Oh, god damn, you are awesome, thank you <3
