### ISSUE TITLE
I cant deobfuscate this class in a plugin.

### ISSUE THREAD

**Issue by Codemaster321** [java-deobfuscator/deobfuscator#418]
Hello!
I want to deobfuscate a plugin with 1 obfuscated class, but it dont work!
Class: [class.zip](https://github.com/java-deobfuscator/deobfuscator/files/3365910/class.zip)

i hope someone can deobfuscate it for me, thanks :D 

(If u need the whole .jar file i can send it!)

**Comment by ThisTestUser** [comment]
This is a .java file, and we need the .class file to deobfuscate it.

**Comment by Codemaster321** [comment]
[class file.zip](https://github.com/java-deobfuscator/deobfuscator/files/3366043/class.file.zip)
This is the .class file.
Do you have a link to a good bytecode viewer?

**Comment by ThisTestUser** [comment]
https://github.com/Konloch/bytecode-viewer/releases

**Comment by Codemaster321** [comment]
Thank you!

**Comment by Codemaster321** [comment]
It dont work on the bitecode viewer, it says:
VoertuigClaimInventory.class: Header does not start with CAFEBABE, ignoring.

**Comment by ItzSomebody** [comment]
> It dont work on the bitecode viewer, it says:
> VoertuigClaimInventory.class: Header does not start with CAFEBABE, ignoring.

That's because you renamed a .java file to a .class file. What @ThisTestUser meant to say is that you need to attach the compiled form of the source code (the files you put in a decompiler)

**Comment by Codemaster321** [comment]
> > It dont work on the bitecode viewer, it says:
> > VoertuigClaimInventory.class: Header does not start with CAFEBABE, ignoring.
> 
> That's because you renamed a .java file to a .class file. What @ThisTestUser means is that you need to attach the compiled form of the source code (the files you put in a decompiler)


I can't do it, can someone help me? The whole code: 
[Code plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/3368043/Code.plugin.zip)

**Comment by Janmm14** [comment]
The deobfuscator **only** works with jar files and not with already decompiled code.

**Comment by Codemaster321** [comment]
> The deobfuscator **only** works with jar files ehich contain compiled java classes and **not with already decompiled code**.

Here the .jar file, i hope you can help me :D 
[plugin jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/3368254/plugin.jar.zip)

**Comment by Codemaster321** [comment]
> > The deobfuscator **only** works with jar files ehich contain compiled java classes and **not with already decompiled code**.
> 
> Here the .jar file, i hope you can help me :D
> [plugin jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/3368254/plugin.jar.zip)

There is 1 class (vehiclesClaimInventory) that is obfuscated.

**Comment by Janmm14** [comment]
I just watched the decompiled class yiu mentioned.

The class is not obfuscated. The decompiler just has a bug.

Try using fernflower or krakatau (both inside the bytecodeviewer available) to decompile that class.
