### ISSUE TITLE
Unknown Obfuscator not deobfuscate 

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#420]
jar for deobfuscation: https://mega.nz/#!W6pFySQB!XLWWab6MUjzBbDlZAs6ka-Bv-1R-7li4vncXQnGKtt4

**Comment by ThisTestUser** [comment]
[vimeworldDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3370222/vimeworldDeob.zip)
[vimeworldDeobRename.zip](https://github.com/java-deobfuscator/deobfuscator/files/3370223/vimeworldDeobRename.zip)

**Comment by lolka13372** [comment]
Thx
