### ISSUE TITLE
Unknown Obfuscator

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#422]
jars for deob: https://mega.nz/#!Wjx0kSRY!2jVrNZf2CMMmdLvArHQKJ1ArRS04VBRH4MZNUm0LEBg

**Comment by ThisTestUser** [comment]
This is ItzSomebody's obfuscator, same as the one you posted earlier.

**Comment by lolka13372** [comment]
@ThisTestUser Strange it looks like the wrong obfuscator

**Comment by lolka13372** [comment]
@ThisTestUser You can decipher it seems to me that there is a malicious code

**Comment by ThisTestUser** [comment]
[junkPluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3414034/junkPluginDeob.zip)
I don't have time to deobfuscate the rest, but here's some of it deobfuscated.

**Comment by lolka13372** [comment]
@ThisTestUser It seems to me that it is not possible to decode there is not a single line that at least suggests something when I used deobfuscation via Java-deobfuscator my RAM was loaded up to 15 GB and CPU by 99%

**Comment by ThisTestUser** [comment]
You probably added all the libraries. You only need to add rt.jar in this case. Also, java-deobfuscator doesn't deobfuscate ItzSomebody's Radon obfuscator anyways.

**Comment by lolka13372** [comment]
@ThisTestUser How then did you deobfuscate the obfuscator superblauebeere27 so easily?

**Comment by ThisTestUser** [comment]
That obfuscator hasn't really changed that much since 2018, so I could use my deobfuscator I developed then. Most of the features you see in Radon were developed a few months ago.

**Comment by lolka13372** [comment]
@ThisTestUser And how can I get a deobfuscator that you developed for deobfuscation superblauebeere27?

**Comment by Janmm14** [comment]
@lolka13372 as he has public deobfuscation, and this is not part of it, I guess he doesn't want to release it

**Comment by lolka13372** [comment]
@Janmm14 But I still wait for him to answer about it.
