### ISSUE TITLE
Some strings won't get deobfuscated

### ISSUE THREAD

**Issue by Tempetek** [java-deobfuscator/deobfuscator#423]
Upon using deobfuscator on this file : [deobf](https://github.com/java-deobfuscator/deobfuscator/files/3413842/deobf.zip) (the jar contained in it) some strings won't get deobfuscated. Example with both obfuscated/deobfuscated strings :
	
	final String a2 = "F7N#\\>NpJ&x\u0013\u001c{\u0015cR~\u0000g\u0002y\u0010gD\u000fJ5";
	final String a3 = "\u001bq\u0010f\u0005|\u001f:\rz\u000e~8DZ7\u0015\"E9K+^2`\"#E\u0001`";
	this.field_149761_L = a.func_94245_a("palamod:machines/crusher_side");
	this.front = a.func_94245_a(vh.l(a3));
	this.top = a.func_94245_a(mo.l(a2));

There's also a weird behavior where the source file names are actually the obfuscated names instead of the original ones.

What could be happening?

(I do have a list of the libs used, but the .zip account for 150 MB, so I'm not uploading there).

**Comment by ThisTestUser** [comment]
[PalaClientDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3413959/PalaClientDeob.zip)

**Comment by Tempetek** [comment]
Wow, that was unexpectedly quick and efficient. Thank you so much for doing this. I do have one more selfish request though. Can I ask how you managed to do this?

**Comment by ThisTestUser** [comment]
What transformers did you use?

**Comment by Tempetek** [comment]
Only one: stringer.v3.StringEncryptionTransformer.

All the other transformers seemed pointless, and the SourceFileClassNormalizer seemed to do the complete opposite.

**Comment by Janmm14** [comment]
The SourceFileClassNormalizer is fully dependant on the information left in. That information could be intentionally altered / scrambled / changed to garbage though

**Comment by ThisTestUser** [comment]
What you should be using is allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer from my deobfuscator: https://github.com/ThisTestUser/deobfuscator/releases
However, allatori.StringEncryptionTransformer doesn't work, as you'll have to change "(Ljava/lang/String;)Ljava/lang/String;" to "(Ljava/lang/String;)Ljava/lang/String;" [here](StringEncryptionTransformer.java) and then recompile it.

**Comment by Janmm14** [comment]
@ThisTestUser some things got messed uo in your answer, the link and the replacement

**Comment by Tempetek** [comment]
I managed to reproduce perfectly. This has been really helpful, thank you for your guidance!
