### ISSUE TITLE
I cant deobfuscate this?

### ISSUE THREAD

**Issue by Codemaster321** [java-deobfuscator/deobfuscator#425]
Hello!
I want to deobfuscate a .jar file but it dont work for me, can someone deobfuscate it and help me please :)

Thanks!

**Comment by ThisTestUser** [comment]
Download my deobfuscator: https://github.com/ThisTestUser/deobfuscator/releases
Use allatori.StringEncryptionTransformer and then allatori.FlowObfuscationTransformer.

**Comment by Codemaster321** [comment]
> Download my deobfuscator: https://github.com/ThisTestUser/deobfuscator/releases
> Use allatori.StringEncryptionTransformer and then allatori.FlowObfuscationTransformer.

I can`t get it work 
(Sorry for late respond i was on vacation)
