### ISSUE TITLE
Help with deobfuscation

### ISSUE THREAD

**Issue by runstukf** [java-deobfuscator/deobfuscator#426]
Hi, I would like to deobfuscate this plugin. In detect, it only detected com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer and it deobfuscated just some of the code. Could you please help me?
[Deobfuscate PLS.zip](https://github.com/java-deobfuscator/deobfuscator/files/3462082/Deobfuscate.PLS.zip)

**Comment by ThisTestUser** [comment]
It is impossible to deobfuscate more.

**Comment by Janmm14** [comment]
All you can do with that now is use a tool like luyten for manual renaming back into meaningful names.

**Comment by runstukf** [comment]
Is there a way to edit it directly in Luyten?

**Comment by Janmm14** [comment]
What about you download the tool and use the menus or right click to find it out. Maaaaybe I specially suggested Luyten because of that functionality.

**Comment by runstukf** [comment]
Well I was searching through the Luyten menus and didn't found any option

**Comment by Janmm14** [comment]
@runstukf I'm sorry for my previous answer, I mixed up tool names :(((
This tool allows: http://www.cuchazinteractive.com/enigma/

**Comment by runstukf** [comment]
No problem, thank you anyways ;)
