### ISSUE TITLE
Reflection.

### ISSUE THREAD

**Issue by LuckerCracker** [java-deobfuscator/deobfuscator#427]
After deobfuscation I have a jar with a lot of reflection calls, is there a way to replace reflection calls with direct calls?
image
![image](https://user-images.githubusercontent.com/49616881/62417264-9be17000-b65c-11e9-8a04-40eda0585de6.png)
I used zelix.ReflectionObfuscationTransformer
OriginalFile: 
[launcher.zip](https://github.com/java-deobfuscator/deobfuscator/files/3464379/launcher.zip)

**Comment by Janmm14** [comment]
Not within this deobfuscator I believe.

**Comment by ThisTestUser** [comment]
[launcherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3464955/launcherDeob.zip)

**Comment by LuckerCracker** [comment]
thanks
