### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by SecurityFlaw** [java-deobfuscator/deobfuscator#428]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded

How to fix?

**Comment by 2902598890** [comment]
java -Xmx4G -jar DEOBFGUI.jar

**Comment by SecurityFlaw** [comment]
Seems to work now, no freeze until now

**Comment by SecurityFlaw** [comment]
Now it freezed a few times after the last line, and now no more reaction and near 100% CPU usage.
Screenshot: https://i.imgur.com/10AJa1j.png

[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/ael f()V: Audit finished.
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/ael a(Lburp/c9;)V: Audit failed!

But the "Audit failed!" message, is from the java software that i try to decompile!

**Comment by ThisTestUser** [comment]
If you are allowed to, upload your JAR.

**Comment by Janmm14** [comment]
All the strings it shows at the end of the line are from the java software you try to decompile, it is there for you to check whether you've chosen the right transformer I think.

**Comment by SecurityFlaw** [comment]
Here is the JAR-File that you want: https://workupload.com/file/XkWLpsFg

**Comment by Janmm14** [comment]
Ahaha burp deobfuscating ok lol

**Comment by ThisTestUser** [comment]
https://workupload.com/file/XnLTuYun
