### ISSUE TITLE
Hangs and Freeze on deobfuscation (evrytime the same point!)

### ISSUE THREAD

**Issue by SecurityFlaw** [java-deobfuscator/deobfuscator#429]
Console-Output:

g/String;Z)Ljava/lang/String;: ***[PROMPT_FOR_PASSWORD]***
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aeb a(Ljava/lang/String;Z)Ljava/lang/String;: Enter the master password to encrypt stored passwords. A strong password is recommended.
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aeb a(Ljava/lang/String;Z)Ljava/lang/String;: ***[ENCRYPTED]***
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aeb a(Ljava/lang/String;Z)Ljava/lang/String;: ***[ENCRYPTED]***
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aeb a(Ljava/lang/String;Z)Ljava/lang/String;: Unable to encrypt persisted password:
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej a(Ljava/lang/Object;)V: ffbc91f70aa68f54308c8ffe18f83959
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej a(Ljava/lang/Object;)V: 48856275610435746380308686717008649650124195563106791179114214321581136791008
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej a(Ljava/lang/Object;)V: burp.ass
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej a(Ljava/lang/Object;)V: burp.gs
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej a([Ljava/lang/Object;Ljava/lang/Object;)Z: burp
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej a([Ljava/lang/Object;Ljava/lang/Object;)Z: burp.fvr
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej <clinit>()V: 31586596721755645138215033955644168621298340881303555638749415877117182885316
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/aej <clinit>()V: bef79eaeed75b26ab724cc10a5890ff1
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/ael f()V: Audit finished.
[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in burp/ael a(Lburp/c9;)V: Audit failed!

**Comment by ItzSomebody** [comment]
Since this wasn't addressed and is old at this point, I'll be closing the issue. If you're still having this issue, feel free to reopen.
