### ISSUE TITLE
I think we got a software problem! - Deobfuscation failed - java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by SecurityFlaw** [java-deobfuscator/deobfuscator#430]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.Arrays.copyOf(Unknown Source)
    at java.util.ArrayList.grow(Unknown Source)
    at java.util.ArrayList.ensException in thread "Thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded

i give 8GB RAM to the proocess.

**Comment by Janmm14** [comment]
You have maybe chosen the wrong transformer for the task, otherwise it likely wouldn't create awt eventqueue threads.
