### ISSUE TITLE
Not deobfuscate superblauebeere27 obfuscator

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#432]
jars for deob: https://mega.nz/#!SzQ2xCDA!x3oxNZKchDi-UnDPJJ3L8ZdXEVoKc8cQSqqz28kr18I

**Comment by ThisTestUser** [comment]
[hwidDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3487107/hwidDeob.zip)

**Comment by lolka13372** [comment]
Thx
