### ISSUE TITLE
Stringer and Allatori deobfuscation failed

### ISSUE THREAD

**Issue by runstukf** [java-deobfuscator/deobfuscator#434]
Hi, so I have Issues deobfuscating this JAR, it says that a class is missing even when it's inside the input jar. I have added all required libraries.

Here is my config: https://pastie.io/pvvkfy.taggerscript
Here is my GUI config: https://pastie.io/hthzje.taggerscript 

File: [DELETED]

**Comment by ThisTestUser** [comment]
[pluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3487680/pluginDeob.zip)
I think you are missing authlib and gson.
There are a lot of libraries you need...

**Comment by runstukf** [comment]
there was a class from fancifull that the deobfuscator said is missing but it's inside the jar. Btw. thanks anyways.

**Comment by runstukf** [comment]
Btw. could you please remove the plugin since there probably is the leaker's spigot id?

Thank you very much

**Comment by runstukf** [comment]
@ThisTestUser I'm really sorry, I just noticed this was a diffrent plugin.

Here's the one: https://anonfile.com/F7P2Me29n4/plugin_jar
