### ISSUE TITLE
Obfuscator superblauebeere not deobfuscate

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#435]
jars for deobfuscation: https://mega.nz/#!LrJyVa7R!SbFeZqqiIPehOPtPk9kCJ677ZJ6y1b-Lh6-ssd1ClZU 
Client Package:
- net.minecraft.squad
Pls Full deobfuscation - this minecraft hacked client

**Comment by ThisTestUser** [comment]
[Optifine 1.12.2Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3487798/Optifine.1.12.2Deob.zip)

**Comment by lolka13372** [comment]
@ThisTestUser 
Do you have a discord?

**Comment by lolka13372** [comment]
@ThisTestUser 
Thx

**Comment by ThisTestUser** [comment]
TheOPPerson#9796

**Comment by lolka13372** [comment]
@ThisTestUser Accept my discord request

**Comment by lolka13372** [comment]
Thx
