### ISSUE TITLE
deobfuscation request - hidden malware

### ISSUE THREAD

**Issue by creeperslayer69** [java-deobfuscator/deobfuscator#437]
Hello the following file is infected with a chrome password stealer and obfuscated using Radon. The password of the archive is infected
[infected.zip](https://github.com/java-deobfuscator/deobfuscator/files/3488510/infected.zip)

**Comment by ThisTestUser** [comment]
[Ragnarok [Injector]Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3489288/Ragnarok.Injector.Deob.zip)
