### ISSUE TITLE
Can`t get this deobfuscated?

### ISSUE THREAD

**Issue by Codemaster321** [java-deobfuscator/deobfuscator#439]
Hello!
I can`t get this .jar file deobfuscated!

Thanks!

**Comment by Janmm14** [comment]
i dont think you are allowed to share this file.

**Comment by Codemaster321** [comment]
> i dont think you are allowed to share this file.

I will delete it when it is deobfuscated

**Comment by ThisTestUser** [comment]
Use the transformers as specified in #425.

**Comment by Codemaster321** [comment]
But if i do that it dont work the .bat file immediatly close

**Comment by ThisTestUser** [comment]
Use [deobfuscator GUI](https://github.com/java-deobfuscator/deobfuscator-gui/releases) instead.

**Comment by Codemaster321** [comment]
That doesnt work, its still obfuscated!

**Comment by ThisTestUser** [comment]
What error do you get? Show us your config also.

**Comment by Codemaster321** [comment]
Error on the end:
[Thread-4] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted 1066 strings
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/reflect/Field could not be found while writing me/gamerjoep/minetopiavehicles/c/b. Using COMPUTE_MAXS

Config:
java -jar deobfuscator.jar -input C:\Users\CodeMaster\Desktop\deob\File.jar -output C:\Users\CodeMaster\Desktop\deob\File-deob.jar -transformer allatori.string.StringEncryptionTransformer

**Comment by ThisTestUser** [comment]
I told you to use allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer. That's the most deobfuscation you can do.

**Comment by Codemaster321** [comment]
My config now is:
java -jar deobfuscator.jar -input C:\Users\GewoonLuca\Desktop\kimp\File.jar -output C:\Users\GewoonLuca\Desktop\kimp\FileDE.jar -transformer allatori.StringEncryptionTransformer -transformer allatori.FlowObfuscationTransformer

I downloaded your deobfuscator and i get this error now:
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/reflect/Field could not be found while writing me/gamerjoep/minetopiavehicles/c/b. Using COMPUTE_MAXS

**Comment by ThisTestUser** [comment]
Attach rt.jar in your java directory to fix the error. Also, are you sure you downloaded deobfuscator.jar from the link above?

**Comment by Codemaster321** [comment]
Yes i downloaded that deobfuscator and i use the GUI
Im gonna try to attach the rt.jar
