### ISSUE TITLE
Obfuscator superblauebeere27 not deobfuscate 

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#440]
jar for deob: https://mega.nz/#!2vojxYiL!4xdp9qGbzwUsUtSQ71sw4TkgDJ2QE86XinvKwqIx0eg
Hacked Client classes:
Path : a
Path : com\etb\client
Needed full deobfuscation

**Comment by ThisTestUser** [comment]
[ETB ReloadedDeob.ZIP](https://github.com/java-deobfuscator/deobfuscator/files/3510258/ETB.ReloadedDeob.ZIP)
There is some custom string encryption left.

**Comment by lolka13372** [comment]
Thx
