### ISSUE TITLE
Freeze screen

### ISSUE THREAD

**Issue by jakuubkoo** [java-deobfuscator/deobfuscator#442]
Hello, please can someone help me?

Normally I run a deobfuscator and then it freezes like that and doesn't respond..

[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 7699 source filenames

Config: https://hasteb.in/vayaradu.css

jar: https://workupload.com/file/VxBjL4F7

If anyone can deobfuscate it, I will be happy :)

**Comment by ThisTestUser** [comment]
Because you can't use this transformer on this specific file.
https://workupload.com/file/HCkKSxq9
The deobfuscated file is above, you'll need to use ProGuard to rename the sources.

**Comment by Jaku3ko** [comment]
How rename the sources?

**Comment by Jaku3ko** [comment]
Or can you send me .jar file please?
