### ISSUE TITLE
Help me with deobfuscation ALLATORIxDEMO

### ISSUE THREAD

**Issue by DeMoNeK** [java-deobfuscator/deobfuscator#446]
i will set up the settings [config.yml] and [detect.yml]
and it not work.

my config:
input: ppack.jar
output: ppack-deof.jar
transformers:
  - [Allatori]

my detect:
input: ppack.jar
detect: true

Screenshot: https://imgur.com/a/d9eeeMB

**Comment by ThisTestUser** [comment]
Remove detect: true, and use allatori.StringEncryptionTransformer instead.
