### ISSUE TITLE
I need help with deobfuscating | Allatori DEMO

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#448]
Hey @ThisTestUser .
I've never deobfuscated anything before and hereby try it the first time.
I just tried to deobfuscate something and tried it with my configuration below.
However, only the strings are unobfuscated.
The classes and methods are still the same.

Input: [Download](https://workupload.com/file/NMq5zku8)
Output: [Download](https://workupload.com/file/wyxFgED6)

My Config.yml:
`input: Input.jar
output: Output.jar
path:
  - C:\Program Files\Java\jre1.8.0_221\lib\rt.jar
  - C:\Program Files\Java\jre1.8.0_221\lib\jce.jar
  - C:\Program Files\Java\jre1.8.0_221\lib\ext\jfxrt.jar
  - C:\Users\Facke\OneDrive\Dokumente\Eclipse\spigot-1.8.8-R0.1-SNAPSHOT-latest.jar
transformers:
  - allatori.string.StringEncryptionTransformer
  - general.removers.LocalVariableRemover
  - normalizer.ClassNormalizer
  - normalizer.SourceFileClassNormalizer`

**Comment by Voyaris** [comment]
Can someone send me the direct download link to the latest version of the deobfuscator?
I currently have this: [Link](https://ci.samczsun.com/job/java-deobfuscator/job/Deobfuscator/)
This one does not support these transformers: [Link](https://github.com/ThisTestUser/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori)

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/deobfuscator/releases
Use allatori.StringEncryptionTransformer and then allatori.FlowObfuscationTransformer

**Comment by Voyaris** [comment]
> https://github.com/ThisTestUser/deobfuscator/releases
> Use allatori.StringEncryptionTransformer and then allatori.FlowObfuscationTransformer,
> and then general.removers.LocalVariableRemover and normalizer.ClassNormalizer.

All in one?
Or step by step?

**Comment by ThisTestUser** [comment]
All in one, but the other method would work too.

**Comment by Voyaris** [comment]
> All in one, but the other method would work too.

I tried that but nothing changed
Here the output: [Output](https://workupload.com/file/VAyKxxMt)

**Comment by Voyaris** [comment]
I tried it another time @ThisTestUser 
I deleted the Input.jar and inserted the original file again and renamed it.
Output.jar: [Output](https://workupload.com/file/ZwdzGaDk
![Unbenannt](https://user-images.githubusercontent.com/25487038/64465360-e62d9500-d0d1-11e9-8f92-482f1f8085be.PNG)
)

**Comment by Voyaris** [comment]
What am I doing wrong @ThisTestUser ?

**Comment by ThisTestUser** [comment]
You used allatori.FlowObfuscationTransformer twice instead of classfilenormalizer.
After that, nothing else can be deobfuscated.

**Comment by Voyaris** [comment]
Oh you're right
But this is the new Output: [Output](https://workupload.com/file/tvYXA3Zq)
Still a lot of Allatori

**Comment by ThisTestUser** [comment]
You can run normalizer.MethodNormalizer and normalizer.FieldNormalizer on the output.jar file.

**Comment by Voyaris** [comment]
Is there a way to get the original class names and methods names back?

**Comment by ThisTestUser** [comment]
Nope. That's why name obfuscation is powerful.

**Comment by Voyaris** [comment]
Okay thank you very much ;)
