### ISSUE TITLE
Help me deobfuscate this jar

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#449]
I have no idea how the Minecraft plugin was obfuscated.
Can anyone tell me how I deobfuscate something like that?
Or send me the unobfuscated version?

Link: DELETED

**Comment by ThisTestUser** [comment]
[KRK-Systems-AntiCrasherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3586716/KRK-Systems-AntiCrasherDeob.zip)

**Comment by Voyaris** [comment]
Can you tell me how you deobfuscated that?
Which transformer?

**Comment by ThisTestUser** [comment]
It's Radon, so it's a custom transformer not publicly available.

**Comment by Voyaris** [comment]
Of course this one's public.
You can download it on GitHub.
Link: [Download](https://github.com/ItzSomebody/Radon)

**Comment by ThisTestUser** [comment]
It is, but the transformer for it is not available in java-deobfuscator.

**Comment by Voyaris** [comment]
Do you think, you can make one?
So not right now.
But in the future?

**Comment by Voyaris** [comment]
@ThisTestUser can you delete the download link to the File?

**Comment by Janmm14** [comment]
@Voyaris He has a transformer for this, but he will not publish it.
