### ISSUE TITLE
Unknown Obfuscator not deobfuscate

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#450]
jar for deob: https://mega.nz/#!zrgiVIBZ!qUAquHhfrnrkgyvKU2-WM-IFxLHCD7lJ1n9ZwckMvDw

**Comment by ThisTestUser** [comment]
It looks like you modified the file, because the string decryption is broken.

**Comment by lolka13372** [comment]
@ThisTestUser I did not modify this file

**Comment by Janmm14** [comment]
1. The plugin has malicious intends. It loads asm and tries to connect to some server on the internet to listen for commands.
2. The plugin's string decryption is definitely broken in the jar you sent and therefore cannot do harm.

The malicious actions it could do if string stuff would not be broken af are:
send version, port and motd to control server, send file content to control server, enable whitelist on server, broadcast a chat message, kick all, download more malicious files, hide certain command executions from console logging, execute bash command, execute console command, list files, backdoor command, zip directories

**Comment by Janmm14** [comment]
Update: It seems like that plugin got obfuscated to only work uo to a certain time.

**Comment by lolka13372** [comment]
@Janmm14 Can you send me to discord deobfuscated jar?

**Comment by Janmm14** [comment]
No, i will not send it to anyone. Basically i wrote everything what it can do. And the ip it connected to is also not reachable anymore. I don't want new malware based on this one around.

**Comment by lolka13372** [comment]
@Janmm14 I need it not for malicious actions but for testing + there are only obfuscated strings, this already means that I can take all these strings from my old plugin but I need the strings that are in this plugin

**Comment by Janmm14** [comment]
why do you need the strings for testing when you will definitely find such plugins only string obfuscated?

**Comment by lolka13372** [comment]
@Janmm14 I need these lines to understand how this works. I already read the main code.

**Comment by Janmm14** [comment]
@lolka13372 No, and this is my final answer on that question.

**Comment by lolka13372** [comment]
@Janmm14 And still it’s a shame that you can’t prove it to me by sending a decrypted file, I found only FTP lol 
It turns out everything you told me it was a hoax

**Comment by Janmm14** [comment]
@lolka13372 hahaha most of the stuff that this malicious plugin does is visible without decrypting any string.
Also I do not have to prove anything. ThisTestUser for example could easily do the same stuff that I did and he'd be able to decrypt it just as easy.

You want decrypted strings? You get some:
```
/root/.ssh/authorized_keys
os.name
http://78.**removed parts of the ip address**.171/cdn/update/
cmd.exe
https://www.youtube.com/user/MrRelayPlay
BASH_CMD
§eИспользование: /**removed command name** kickall <причина...>
0|8|9|17|
-== Вы активировали хак ==-
```

**Comment by lolka13372** [comment]
@Janmm14 Sorry, you just couldn’t send me this test even to discord so I wrote it
