### ISSUE TITLE
I can't deobfuscate this Plugin

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#454]
I tried to use the detect option but it droped an error.
Could you please deobfuscate it for me @ThisTestUser ?
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/3607901/Plugin.zip)

**Comment by ThisTestUser** [comment]
[pluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3612019/pluginDeob.zip)

**Comment by Voyaris** [comment]
Thank you, could you delete the link?
