### ISSUE TITLE
Please deobfuscate this Jar

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#455]
@ThisTestUser could you please deobfuscate this Spigot Plugin?
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/3612984/Plugin.zip)

**Comment by ThisTestUser** [comment]
[AC-FullFix (7.0)Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3613119/AC-FullFix.7.0.Deob.zip)
