### ISSUE TITLE
Please deobfuscate this

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#456]
[Plugin (2).zip](https://github.com/java-deobfuscator/deobfuscator/files/3613769/Plugin.2.zip)
I think it's Radon
It would be nice if you could deobfuscate me this.

**Comment by ThisTestUser** [comment]
[AntiCrash-8.0Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3613798/AntiCrash-8.0Deob.zip)

**Comment by Voyaris** [comment]
It is not deobfuscated
Nothign changed @ThisTestUser

**Comment by Janmm14** [comment]
Also it doesn't look like Radon, more like superblaubeere because of the constant calculations like `20 + 96 - 85 + 96 ^ (130 ^ 167) << " ".length() ^ -" ".length()`

**Comment by Voyaris** [comment]
> Also it doesn't look like Radon, more like superblaubeere because of the constant calculations like `20 + 96 - 85 + 96 ^ (130 ^ 167) << " ".length() ^ -" ".length()`, maybe some other obfuscation took also place

Do you know if there are any deobfuscators?

**Comment by ThisTestUser** [comment]
[AntiCrash-8.0Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3613841/AntiCrash-8.0Deob.zip)
