### ISSUE TITLE
zkm-chan nyo deobfuswcate :3

### ISSUE THREAD

**Issue by shimakaze-chan-uwu** [java-deobfuscator/deobfuscator#458]
jawa deobfuswcater fwail tew deobf :sob: stwings uwu hwere download :3

[Matrix.zip](https://github.com/java-deobfuscator/deobfuscator/files/3632580/Matrix.zip)

thank uwu ❤️

**Comment by shimakaze-chan-uwu** [comment]
@ItzSomebody 😕

**Comment by jiangdashao** [comment]
Deobfuscate your mom. x)

**Comment by shimakaze-chan-uwu** [comment]
@ThisTestUser can you help plz

**Comment by Janmm14** [comment]
I would not deobfuscate this.

**Comment by shimakaze-chan-uwu** [comment]
> 
> 
> I would not deobfuscate this.
> 
> Its a free and legitimate spigotmc resource.

I Don"t Trust Obfuscated Plugin For My Server But I Want Better AntiHack

**Comment by TerriblePanda** [comment]
> > I would not deobfuscate this.
> > Its a free and legitimate spigotmc resource.
> 
> I Don"t Trust Obfuscated Plugin For My Server But I Want Better AntiHack. Is It Really Safe?

You won't know if it's safe even though you deobfuscated it. :\

**Comment by shimakaze-chan-uwu** [comment]
> 
> 
> > > I would not deobfuscate this.
> > > Its a free and legitimate spigotmc resource.
> > 
> > 
> > I Don"t Trust Obfuscated Plugin For My Server But I Want Better AntiHack. Is It Really Safe?
> 
> You won't know if it's safe even though you deobfuscated it. :\

My Job Is Reverse Engineer For Native Code With IDA Pro Java Assembly Is Much Simpler. So I Doubt It Would Not Be Hard I Just Thought This Script Would Remove Some Of The Time It Will Take. It Seems Like The ZKM Obfuscate Is Much Complex? Requiring Me To Write My Own Transformer After I Do This I Will Post Deobfuscate Jar File For Future Analysis!

**Comment by TerriblePanda** [comment]
> > > > I would not deobfuscate this.
> > > > Its a free and legitimate spigotmc resource.
> > > 
> > > 
> > > I Don"t Trust Obfuscated Plugin For My Server But I Want Better AntiHack. Is It Really Safe?
> > 
> > 
> > You won't know if it's safe even though you deobfuscated it. :\
> 
> My Job Is Reverse Engineer For Native Code With IDA Pro Java Assembly Is Much Simpler. So I Doubt It Would Not Be Hard I Just Thought This Script Would Remove Some Of The Time It Will Take. It Seems Like The ZKM Obfuscate Is Much Complex? Requiring Me To Write My Own Transformer Script Like I Do With Python For IDA Pro After I Do This I Will Post Deobfuscate Jar File For Future Analysis!

Just do it.

**Comment by jiangdashao** [comment]
If you don't trust this plugin, please use another plugin, lol
