### ISSUE TITLE
deobfuscate this pls

### ISSUE THREAD

**Issue by cheel1337** [java-deobfuscator/deobfuscator#460]
[ob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3654462/ob.zip)

**Comment by ThisTestUser** [comment]
[obDeobRename.zip](https://github.com/java-deobfuscator/deobfuscator/files/3655439/obDeobRename.zip)
[obDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3655441/obDeob.zip)
