### ISSUE TITLE
Please deobfuscate this :)

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#461]
Hey @ThisTestUser could you try do deobfuscate that? I have never seen an obfuscator like that.
[Sativa v9.zip](https://github.com/java-deobfuscator/deobfuscator/files/3658985/Sativa.v9.zip)

**Comment by ThisTestUser** [comment]
[Sativa.v9Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3660014/Sativa.v9Deob.zip)
[Sativa.v9Deob1.zip](https://github.com/java-deobfuscator/deobfuscator/files/3660016/Sativa.v9Deob1.zip)
