### ISSUE TITLE
Need help deobfuscating

### ISSUE THREAD

**Issue by x0Rev** [java-deobfuscator/deobfuscator#463]
need some serious help can't manage to deobfuscate and its one of those annoying ones i originally bought this program (its free to download but has a hwid lock you need whitelisted for which i was but now its not working came out 2 years ago) i did contact the creator but apparently he doesn't respond to messages anymore which is an issue because he hosts the paid program 

pretty sure it uses zelix anyways heres the link id prefer a hwid bypass rather than a deobfuscate but if thats not possible im fine with a deobfuscate 
https://mega.nz/#!KwkxQC5Z!QvuJIpRrfeYVSyp2ZNXZi3CDdvOI_Vct3550e3ge2xs

**Comment by ThisTestUser** [comment]
[Black Ops II Wii U Mod InjectorDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3693352/Black.Ops.II.Wii.U.Mod.InjectorDeob.zip)

**Comment by x0Rev** [comment]
> [Black Ops II Wii U Mod InjectorDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3693352/Black.Ops.II.Wii.U.Mod.InjectorDeob.zip)

i really appreciate that man now i gotta go do some digging so many classes to check

**Comment by Janmm14** [comment]
What you got there is just the downloader, at least it looks like that for me.

it reads the download location from pastebin.com/raw/d1zgU5qC, currently its pointing to https://bullywiiplaza.website/B.jar
there you have another obfuscated jar file

**Comment by ThisTestUser** [comment]
[BDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3693849/BDeob.zip)

**Comment by x0Rev** [comment]
ok i found this in the second file it was a link to a mega download and the file is called data_stealer.jar its also obfuscated using the same thing is it a potential rat? or is it the actual file that grabs your hwid


[Data Stealer.zip](https://github.com/java-deobfuscator/deobfuscator/files/3694165/Data.Stealer.zip)

**Comment by ThisTestUser** [comment]
[Data.StealerDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3694483/Data.StealerDeob.zip)
