### ISSUE TITLE
Please deobf this jar.

### ISSUE THREAD

**Issue by Almonther2001** [java-deobfuscator/deobfuscator#464]
[PX.zip](https://github.com/java-deobfuscator/deobfuscator/files/3694703/PX.zip)

**Comment by ThisTestUser** [comment]
[PXDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3694742/PXDeob.zip)

**Comment by Almonther2001** [comment]
i can't open the source?

**Comment by Janmm14** [comment]
Use Fernflower or Krakatau decompilers. ByteCodeViewer is a multi-decompiler-gui you could use.

**Comment by Almonther2001** [comment]
Thanks.
