### ISSUE TITLE
What kind of obfuscator is this?

### ISSUE THREAD

**Issue by just4fun722** [java-deobfuscator/deobfuscator#465]
Hey,

I wasn't successful in deobfuscating this jar
https://workupload.com/file/PCAgHLMm
Maybe someone can take a look and see which obfuscator this is (or maybe even deobfuscate it).
Any help would be greatly appreciated 

Cheers

**Comment by ItzSomebody** [comment]
![Capture](https://user-images.githubusercontent.com/23221108/66521348-7fd5d100-eada-11e9-875c-0f547ddecb73.PNG)

**Comment by just4fun722** [comment]
Awesome, thank you 
Btw: congrats to you & your team for #1 @pico ;-)

**Comment by ThisTestUser** [comment]
[EDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3714644/EDeob.zip)
