### ISSUE TITLE
Need it deobfuscated

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#466]
Hey @ThisTestUser would you please deobfuscate this?
[Upload.zip](https://github.com/java-deobfuscator/deobfuscator/files/3710218/Upload.zip)

**Comment by ThisTestUser** [comment]
[UploadDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3714665/UploadDeob.zip)

**Comment by Voyaris** [comment]
It is still obfucated

**Comment by Voyaris** [comment]
@ThisTestUser Could you try it another time?

**Comment by ThisTestUser** [comment]
[UploadDeob1.zip](https://github.com/java-deobfuscator/deobfuscator/files/3715314/UploadDeob1.zip)
