### ISSUE TITLE
can't deobf this jar

### ISSUE THREAD

**Issue by Almonther2001** [java-deobfuscator/deobfuscator#467]
[PPP.zip](https://github.com/java-deobfuscator/deobfuscator/files/3714264/PPP.zip)

**Comment by ThisTestUser** [comment]
[MemoryFix-0.3Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3715303/MemoryFix-0.3Deob.zip)
[MemoryFix-0.3DeobRename.zip](https://github.com/java-deobfuscator/deobfuscator/files/3715306/MemoryFix-0.3DeobRename.zip)
