### ISSUE TITLE
Can't deobf help.

### ISSUE THREAD

**Issue by Almonther2001** [java-deobfuscator/deobfuscator#469]
[MB.zip](https://github.com/java-deobfuscator/deobfuscator/files/3721654/MB.zip)

**Comment by ThisTestUser** [comment]
[MotionBlur-1.0_1.8.9Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3721837/MotionBlur-1.0_1.8.9Deob.zip)
[MotionBlur-1.0_1.8.9DeobRename.zip](https://github.com/java-deobfuscator/deobfuscator/files/3721838/MotionBlur-1.0_1.8.9DeobRename.zip)
