### ISSUE TITLE
Error Could not locate a class file.

### ISSUE THREAD

**Issue by bruno10223** [java-deobfuscator/deobfuscator#47]
I have an error , look at the printscreens ,

http://i.imgur.com/ECBWZNv.png

command used : http://i.imgur.com/Kb1ts9X.png
yes, my patch is correct rt.jar , well I think

I created a folder inside put the Deobfuscator and the jar in which I
http://i.imgur.com/SlJ5yvM.png

If you have any silly mistake my , sorry I'm from Brazil and I am not good in English

**Comment by Shortninja66** [comment]
try using quotes around your rt path.

assuming that aac is the plugin, you'll also have to reference a bukkit jar and netty (or else you'll also get NoClassInPathException even after fixing the rt.jar).
