### ISSUE TITLE
Please help me deobfuscate this.

### ISSUE THREAD

**Issue by fuckedUpByEternity** [java-deobfuscator/deobfuscator#473]
Hi, will you please help me deobfuscate this? I already tried but I'm unable to determine the obfuscation. 

Download: https://anonfile.com/Hf02kb9bn3/Skid_jar

Thanks in advance.

**Comment by ThisTestUser** [comment]
https://anonfile.com/LbO5o99ene/SkidDeob_zip

**Comment by fuckedUpByEternity** [comment]
Hi. This is still very obfuscated and I can't read it.
What to do next?

**Comment by ThisTestUser** [comment]
You need to rename the "?" package using proguard.

**Comment by fuckedUpByEternity** [comment]
Can I contact you on the Discord so you can help me with that please?

**Comment by fuckedUpByEternity** [comment]
I added you on discord TheOPPerson#9796.
My discord is fuckedUpByEternity_#3828.
