### ISSUE TITLE
Help to deobfuscate this jar

### ISSUE THREAD

**Issue by TheEndGuy** [java-deobfuscator/deobfuscator#476]
im not getting the data from this jar, i would like to ask for help. i think is about allatori obfuscator.

[duel_file.zip](https://github.com/java-deobfuscator/deobfuscator/files/3786886/duel_file.zip)

**Comment by ThisTestUser** [comment]
[duel_fileDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3791965/duel_fileDeob.zip)
