### ISSUE TITLE
Method code too large! /w StringEncryptionTransformer

### ISSUE THREAD

**Issue by Shortninja66** [java-deobfuscator/deobfuscator#48]
[console](https://i.gyazo.com/cc891d47ed782898cb99c7dc347b5eb9.gif)
[full log](http://pastebin.com/2nh6W5ju)

args: java -jar deobfuscator.jar -input input.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path "C:/Program Files/Java/jre1.8.0_40/lib/rt.jar" -path "spigot.jar" -path "netty.jar"

**Comment by Shortninja66** [comment]
after increasing the stack size, it appears that [another error occurs](http://pastebin.com/yfAdF96d)

**Comment by samczsun** [comment]
Please send a copy of the obfuscated JAR to submit@javadeobfuscator.com with the subject "Issue #48"

**Comment by samczsun** [comment]
Use zelix.StringEncryptionTransformer

**Comment by Shortninja66** [comment]
works, thanks
