### ISSUE TITLE
Please deobfuscate

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#480]
I need this Spigot Plugin unobfuscated.
It might be whether Allatori / Radon / superblaubeere
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/3810002/Plugin.zip)

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3811829/PluginDeob.zip)
