### ISSUE TITLE
can't deobfuscate this jar

### ISSUE THREAD

**Issue by Almonther2001** [java-deobfuscator/deobfuscator#481]
[iPhoneXS.zip](https://github.com/java-deobfuscator/deobfuscator/files/3813919/iPhoneXS.zip)

**Comment by ThisTestUser** [comment]
[iPhoneXSDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3822318/iPhoneXSDeob.zip)

**Comment by ItzSomebody** [comment]
Just as an FYI, probably shouldn't be posting paid software (see https://funkemunky.cc/shop).

**Comment by Almonther2001** [comment]
it's a really old version this is before anticheat get recoded 2 times
