### ISSUE TITLE
Help with deobfuscation

### ISSUE THREAD

**Issue by fikawka** [java-deobfuscator/deobfuscator#489]
Hello, i need a help with deobfuscation.
It's minecraft plugin and it got leaked and cracked.
I wan't to check backdoors.
It's stringer (90%) but i don't know how to deobfuscate this.
To get real file change name from shit.zip to shit.jarx

[shit.zip](https://github.com/java-deobfuscator/deobfuscator/files/3848545/shit.zip)
x

**Comment by fikawka** [comment]
and this: 
[gf.zip](https://github.com/java-deobfuscator/deobfuscator/files/3848595/gf.zip)

**Comment by ThisTestUser** [comment]
[shitDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3848957/shitDeob.zip)
[obfuscated52 (2)Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3848958/obfuscated52.2.Deob.zip)

**Comment by fikawka** [comment]
Thanks, to close
