### ISSUE TITLE
Help me deobfuscate

### ISSUE THREAD

**Issue by NoTryhxs** [java-deobfuscator/deobfuscator#494]
[help.zip](https://github.com/java-deobfuscator/deobfuscator/files/3882322/help.zip)
I can't deobsufcate this could you help me

**Comment by cookiedragon234** [comment]
http://www.filedropper.com/pce-118-deobf

That was the best I could do, but only managed to remove stringer. Its layered with a second obfuscator that I couldn't identify. Idk what this mod does, but not much. If you can tell me what the second obfuscator is I might be able to write a transformer for it.

**Comment by ThisTestUser** [comment]
[Pce-1.18Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4093884/Pce-1.18Deob.zip)
I wasn't able to get rid of the invokedynamics.
