### ISSUE TITLE
Help please deobfuscate error JavaFX

### ISSUE THREAD

**Issue by Mrsasha45op** [java-deobfuscator/deobfuscator#497]
When I'm trying to decompile, I get this error: 
`Error: javafx/beans/value/ObservableValue could not be found while writing this/is/test/iiiIi. Using COMPUTE_MAXS`

**Comment by Janmm14** [comment]
You need to add the java fx jar to the path

**Comment by Mrsasha45op** [comment]
> You need to add the java fx jar to the path

I don't know where to find it

**Comment by Enteerman** [comment]
named `jfxrt.jar` usually under `libs`
