### ISSUE TITLE
Problem using Allatori.STRING_ENCRYPTION.

### ISSUE THREAD

**Issue by jacquesbizeray** [java-deobfuscator/deobfuscator#50]
Hello, I have been trying to use with the command below but it didn't work.

C:\Users\sniffer\Desktop>java -jar deobfuscator-1.0.0.jar -input "e2413e6df124e4
d319df8a869de2a8c936d907016d7f41424fe9f97d5c9b8049(jar).jar" -output output.jar
-transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\j
re1.8.0_101\lib\rt.jar"

Reading complete. Loading hierachy

Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.ClassCastException: com.javadeobfuscator.deobfuscator.org.objectweb.as
m.tree.InsnNode cannot be cast to com.javadeobfuscator.deobfuscator.org.objectwe
b.asm.tree.LdcInsnNode
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:72)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:61)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:60)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)

Here is the image using obfuscation.
![deob](https://cloud.githubusercontent.com/assets/6463663/17341349/9424b964-58ca-11e6-8804-c30007103229.jpg)

**Comment by MoofMonkey** [comment]
Use "Luyten" and select mode "ByteCode AST" and give ScreenShot.

**Comment by samczsun** [comment]
First off, let me recommend [this](https://github.com/helios-decompiler/Helios) ([download](https://ci.samczsun.com/job/bootstrapper/)).

Secondly, please send a copy of the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #50"
