### ISSUE TITLE
Allatori 7.0 not deobfuscate 

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#502]
jar for deobfuscation: https://mega.nz/#!HrxjgKQL!KINYRFoxNlkPFN5vG418UPm45NjKZuhuYsrbr3-ylJc

**Comment by cookiedragon234** [comment]
The allatori deobfuscator I wrote the other day seems to break class writing. Its deobfuscated all the strings just fine, heres a dump https://pastebin.com/q8JWgtPL. Ill work on fixing class writing.

**Comment by cookiedragon234** [comment]
[3.10-deobf.zip](https://github.com/java-deobfuscator/deobfuscator/files/3952065/3.10-deobf.zip)

Fixed it by replacing the parameters to the deobfuscating functions with the deobfuscated strings. Please note this jar wont be runnable.

**Comment by Janmm14** [comment]
> [3.10-deobf.zip](https://github.com/java-deobfuscator/deobfuscator/files/3952065/3.10-deobf.zip)
> 
> Fixed it by replacing the parameters to the deobfuscating functions with the deobfuscated strings. Please note this jar wont be runnable.

What you could do instead: Add a pop for every parameter (and another pop if the function is not static).
Replace the function call with LDC of deobfuscated string.
Next, run general.peepholeoptimizer

**Comment by cookiedragon234** [comment]
@Janmm14 Im still learning ASM, so sorry if I get this wrong, but the bytecode beforehand is something like this:
```Jasmin
LDC "~N\u007fY"
INVOKESTATIC ih.ALLATORIxDEMO:(Ljava/lang/String;)Ljava/lang/String;
```
The function call pops the encrypted string off the stack leaving it with only the decrypted string.

That would therefore be equal to
```Jasmin
LDC "decryptedstring"
```
no?

**Comment by ItzSomebody** [comment]
@cookiedragon234 What he is saying is you could do something like this:

```java
ldc "encrypted string"
invokestatic ih/ALLATORIxDEMO decrypt(Ljava/lang/String;)Ljava/lang/String;
```

Then, you replace the invokestatic with pop after decrypting the string

```java
ldc "encrypted string"
pop // used to be invokestatic
ldc "decrypted string"
```

This prevents stack-trickery from screwing up transformers say if you were dealing with something like this

```java
ldc "encrypted string"
iconst_5
dup_x1
swap
pop2
invokestatic ih/ALLATORIxDEMO decrypt(Ljava/lang/String;)Ljava/lang/String;
```

**Comment by cookiedragon234** [comment]
Ahhh I see, that's very clever. Thanks :)

**Comment by MKiperszmid** [comment]
> [3.10-deobf.zip](https://github.com/java-deobfuscator/deobfuscator/files/3952065/3.10-deobf.zip)
> 
> Fixed it by replacing the parameters to the deobfuscating functions with the deobfuscated strings. Please note this jar wont be runnable.

May I know what transformers you used to deobsfucate?
And if you could share

Thanks in advance

**Comment by ItzSomebody** [comment]
> May I know what transformers you used to deobsfucate?
> And if you could share
> 
> Thanks in advance

Maybe you should read the discussion??

**Comment by lolka13372** [comment]
@ItzSomebody 
![image](https://user-images.githubusercontent.com/51010014/70679246-9c8eb080-1ca5-11ea-8d5a-860684fbadd3.png)

**Comment by lolka13372** [comment]
@cookiedragon234 Thx

**Comment by cookiedragon234** [comment]
@MKiperszmid private ones that I can’t share, sorry
