### ISSUE TITLE
Help to Deaobfuscate Allatori 

### ISSUE THREAD

**Issue by jzr54732** [java-deobfuscator/deobfuscator#504]
With What Settings? 
![image](https://user-images.githubusercontent.com/58951350/70929099-99434e00-2032-11ea-8f67-786936e23ca9.png)

**Comment by ThisTestUser** [comment]
Use this one: https://github.com/thistestuser/deobfuscator
Select allatori.StringEncryptionTransformer, and allatori.FlowObfuscationTransformer.

**Comment by bozkurt13** [comment]
Bu programın nasıl çalıştırabileceğimi biri bana anlatabilir mi?
