### ISSUE TITLE
Please deobfuscate me a jar

### ISSUE THREAD

**Issue by Voyaris** [java-deobfuscator/deobfuscator#507]
Hey @ThisTestUser 
could you please deobfuscate me this jar?
It's obfuscated with Radon!
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/3990310/Plugin.zip)

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4094053/PluginDeob.zip)
