### ISSUE TITLE
Lambda trouble with zelix.ReflectionObfuscationTransformer

### ISSUE THREAD

**Issue by MoofMonkey** [java-deobfuscator/deobfuscator#51]
http://pastebin.com/kEhfmwUT
Using lastet build (24)

**Comment by samczsun** [comment]
Please send a copy of the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #51"

**Comment by MoofMonkey** [comment]
Done.

**Comment by MoofMonkey** [comment]
http://rgho.st/679XpDFn2
Password: link for this issue (https://github.com/java-deobfuscator/deobfuscator/issues/51)

**Comment by MoofMonkey** [comment]
........ Why?
