### ISSUE TITLE
Help to deobfuscate jar please, infinite writing

### ISSUE THREAD

**Issue by Mrsasha45op** [java-deobfuscator/deobfuscator#515]
Please, help to me deobfuscate this jar. I used com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer and com.javadeobfuscator.deobfuscator.transformers.zelix.FlowObfuscationTransformer
but it just says "Writing..." all the time. I will be happy, if you would do this! :) It's obfuscated with Zelix and this is a JavaFX application.
[launcher.zip](https://github.com/java-deobfuscator/deobfuscator/files/4031830/launcher.zip)

**Comment by ThisTestUser** [comment]
[launcherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4094340/launcherDeob.zip)

**Comment by Mrsasha45op** [comment]
> [launcherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4094340/launcherDeob.zip)

Thank you so much!
