### ISSUE TITLE
Deobfuscator couldn't detect obfuscation

### ISSUE THREAD

**Issue by JStyle21** [java-deobfuscator/deobfuscator#519]
Hi,

Looking for the obfuscation library for this
https://www9.zippyshare.com/v/PhVhP4WP/file.html

deobfuscator couldn't detect anything.

**Comment by Janmm14** [comment]
link error 403

**Comment by JStyle21** [comment]
It works fine for me, but here is another location
https://mega.nz/#!g5ZQzSDa!9iQcfwX1WyaYFsKPtdllYYK9V4exsiliIug5u4eZFiE

**Comment by ThisTestUser** [comment]
Nothing can be deobfuscated here.

**Comment by JStyle21** [comment]
Why not?

**Comment by ThisTestUser** [comment]
It's just name obfuscation.

**Comment by JStyle21** [comment]
Then why can't i read the files inside? like .json ones etc.
