### ISSUE TITLE
The problem is similar to that #51

### ISSUE THREAD

**Issue by MoofMonkey** [java-deobfuscator/deobfuscator#52]
The problem is similar to that #51
Same file
http://pastebin.com/fCQFDUNv

**Comment by samczsun** [comment]
Because you have to use the string encryption transformer first, then the reflection obfuscation transformer

**Comment by MoofMonkey** [comment]
Right off would wrote...

**Comment by MoofMonkey** [comment]
Nope.

>         at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
>         at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:267)
>         at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:221)
>         at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$null$2(DeadCodeRemover.java:42)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
>         at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
>         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
>         at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
>         at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
>         at java.util.stream.ReferencePipeline.forEach(Unknown Source)
>         at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$transform$3(DeadCodeRemover.java:40)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
>         at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
>         at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
>         at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
>         at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
>         at java.util.stream.ReferencePipeline.forEach(Unknown Source)
>         at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:39)
>         at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:45)
>         at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:155)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
> com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: java.lang.NullPointerException @ net/k773/a a(J)I
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1437)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
>         at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
>         at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:36)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1149)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
>         at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
>         at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:36)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1149)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
>         at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)
>         at java.util.HashMap$Values.forEach(Unknown Source)
>         at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
> Caused by: java.lang.NullPointerException
>         at java.lang.reflect.Array.get(Native Method)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:101)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:439)
>         ... 15 more
> java.lang.IllegalArgumentException: argument type mismatch
>         at java.lang.reflect.Array.set(Native Method)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayStore(MethodExecutor.java:167)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:472)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
>         at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)
>         at java.util.HashMap$Values.forEach(Unknown Source)
>         at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by samczsun** [comment]
I don't know what else to say beyond I debugged using the exact file you gave me and using those two transformers alone the file was deobfuscated

**Comment by MoofMonkey** [comment]
Deobfuscated, but errors in the logs. Okay... Thanks.
