### ISSUE TITLE
Help with transformer

### ISSUE THREAD

**Issue by Delerbo** [java-deobfuscator/deobfuscator#523]
Hi, this plugin have weird class names (https://www.spigotmc.org/threads/minianni-recoded-1-8-x-1-15-x.412697/) how transformers i can use to deobfuscate it?

**Comment by Janmm14** [comment]
if it only has weird class names I'd suggest using Proguard name obfuscation to rename that to class a, b, c etc.

**Comment by Delerbo** [comment]
> if it only has weird class names I'd suggest using Proguard name obfuscation to rename that to class a, b, c etc.

And what transformer or program I must use?

**Comment by cookiedragon234** [comment]
You can use the class,field and method normalisers included with this deobfuscator
