### ISSUE TITLE
Please deobfuscate this

### ISSUE THREAD

**Issue by SpookyCoder3** [java-deobfuscator/deobfuscator#526]
Hello,
Can someone please deobfuscate this for me.

Thanks
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/4210894/Plugin.zip)

**Comment by sw1tchbl4d3-github** [comment]
Its not obfuscated, you can just decompile it.

[Decompiled Files](https://please.dont-hack.me/8f0epmboofqh5.jar.src.zip)
and why do you want to decompile [a minecraft plugin](https://www.spigotmc.org/resources/ddg-pets-minetopia-pet-plugin.70347/)

**Comment by FinalException** [comment]
Here you go: 


[Plugin deobfuscated.zip](https://github.com/java-deobfuscator/deobfuscator/files/4271957/Plugin.deobfuscated.zip)
