### ISSUE TITLE
Allatori Deobfuscation problem

### ISSUE THREAD

**Issue by xiaonian233** [java-deobfuscator/deobfuscator#527]
I use allatori to obfuscate a jar multiple times, and deobfuscation cant restore the string. Is there any good way?

**Comment by ItzSomebody** [comment]
That depends. Perhaps the deobfuscator wasn't able to restore the string because the decryptor class/method is missing. Or maybe the deobfuscator emulated the decryptor code incorrectly. There's a variety of reasons why deobfuscation could've gone wrong.
