### ISSUE TITLE
Stringer 2 way

### ISSUE THREAD

**Issue by TheKoljas** [java-deobfuscator/deobfuscator#53]
Hello, On my program is used with strings Stringer encryption 2 way.Programma error.Sorri, using Google Translate.

Here is the image using obfuscation.

![screenshot_2](https://cloud.githubusercontent.com/assets/17952494/17476398/8b43d922-5d68-11e6-988a-ff12dd7b8f4a.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/17952494/17476345/4b6f7946-5d68-11e6-86cd-1163d26e8f86.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17952494/17476552/4a6b96f0-5d69-11e6-9926-d087d0a108e0.png)

**Comment by Janmm14** [comment]
try again with the same deobfuscator or add the transformer argument twice.

**Comment by maxim19116** [comment]
Вайм, хд он хреново обуфицирован XD))

**Comment by maxim19116** [comment]
И скинь какой коммандой декомпилируешь, прост не получается stringer декомпилить

**Comment by Janmm14** [comment]
@maxim19116 Please use google translator.

**Comment by ItzSomebody** [comment]
@maxim19116 it is not impossible to decompile stringer nor is it impossible to deobfuscate it. If a computer can run it that it also can be deobfuscated.

**Comment by samczsun** [comment]
Assuming this is resolved with the new Stringer 3.x transformers
