### ISSUE TITLE
NoClassInPathException: package36/google/gson/JsonObject HOWEVER package36/google/gson doesn't exist, only com/google/gson

### ISSUE THREAD

**Issue by B-Knight49** [java-deobfuscator/deobfuscator#531]
> `[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer
> 
> 
> 
> 
> 
> ** DO NOT OPEN AN ISSUE ON GITHUB **
> Could not locate a class file.
> Have you added the necessary files to the -path argument?
> The error was:
> com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: package36/google/gson/JsonObject
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:337)
>         at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$null$7(MethodNormalizer.java:161)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
>         at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
>         at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
>         at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
>         at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
>         at java.util.stream.ReferencePipeline.forEach(Unknown Source)
>         at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$remap$10(MethodNormalizer.java:150)
>         at java.util.HashMap$Values.forEach(Unknown Source)
>         at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.remap(MethodNormalizer.java:36)
>         at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`
> 

MethodNormalizer is asking for JsonObject from Google's GSON package but it's asking for it under the package group "package36" rather than the actual "com.google.[etc]". What's gone wrong here?

**Comment by Janmm14** [comment]
I suggest to use proguard for normalizing instead.

**Comment by Enteerman** [comment]
This can be a result of invalid configuration, so I am closing this issue now. We don't have enough information to identify the issue. If you want, you can attach the config and related files here (I will reopen if you do) or in a new issue.
