### ISSUE TITLE
Is it possible to deobfuscate invokedynamic in this jar file?

### ISSUE THREAD

**Issue by xomka2280** [java-deobfuscator/deobfuscator#533]
https://drive.google.com/file/d/1gkByjusENXe3rDk1ag3ngwwz0zsBmUdl/view?usp=sharing

**Comment by jackwpa** [comment]
I just tried the latest beta of JEB (3.15) and things are looking good. Not all invokedynamic were resolved to lambdas, but many were. There are decrypted strings (in purple) here and there as well, such as:

![image](https://user-images.githubusercontent.com/60268349/76059881-d08c1180-5f34-11ea-8471-ee20a9dc5ed9.png)
