### ISSUE TITLE
Anti Java Decompiler/ Provide Transformer Please

### ISSUE THREAD

**Issue by apkunpacker** [java-deobfuscator/deobfuscator#534]
[myapp2.apk.zip](https://github.com/java-deobfuscator/deobfuscator/files/4333863/myapp2.apk.zip)

Above is an apk and here is its jar file 
[myapp2-enjarify.jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/4333862/myapp2-enjarify.jar.zip)

This is obfuscated with 
https://m.apkpure.com/bg-anti-decompile-reverse-java/com.bgplus.Anti.JavaDecompiler

I tried all transformer but string can not be decrypted .
Please provide transformer for such jar .no need of deobfuscation just need transformer
 thanks

**Comment by jackwpa** [comment]
I tried JEB Decompiler on this file, it works just fine. It looks like the encrypted data is in the class ¢¢¢Þ. However, the log does not specify exactly how and where the decryption took place.

![image](https://user-images.githubusercontent.com/60268349/76783499-310a2280-676f-11ea-981d-ee8462b897f9.png)

**Comment by apkunpacker** [comment]
![858112513_303696](https://user-images.githubusercontent.com/27184655/76814066-c95fe000-681f-11ea-9464-bca830f6a131.jpg)
I know the decryption routine and decrypted at runtine also with frida but why not statically possible with this awesome deobfuscator . 
You are getting already decrypted string in JEB , probably you are using version above 3.11 , latest one 3.15 is already providing many automatic string decryption option
