### ISSUE TITLE
Is it possible to deobfuscate these classes ? They have invokedynamic and impossible to decompile methods

### ISSUE THREAD

**Issue by VenTaz** [java-deobfuscator/deobfuscator#535]
https://drive.google.com/file/d/1bSf7n9IXcbUpdW_bSmn_-ulF8Vc70Scg/view?usp=sharing

**Comment by ParadoxLegit** [comment]
Looks like zelix

**Comment by VenTaz** [comment]
Using zelix transformers, it doesn't do anything

**Comment by Janmm14** [comment]
this deobfuscator has no transformers for the latest versions of zelix

**Comment by chrisbog94** [comment]
I'm also looking for a Zelix 13.0.1 deobfuscator!
