### ISSUE TITLE
Java RAT Obfuscated

### ISSUE THREAD

**Issue by NotSoonTM** [java-deobfuscator/deobfuscator#537]
[malware.zip](https://github.com/java-deobfuscator/deobfuscator/files/4383887/malware.zip)

Appears to be obfuscated with radon, not entirely sure.

**Comment by ThisTestUser** [comment]
[vluciratDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4483511/vluciratDeob.zip)
[vluciratDeobRename.zip](https://github.com/java-deobfuscator/deobfuscator/files/4483512/vluciratDeobRename.zip)

**Comment by notverble** [comment]
I AM SORRY TO INTERFERE BUT WHEN TINY EVENT UPDATE
