### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by nathanfarlow** [java-deobfuscator/deobfuscator#538]
The download link https://ci.samczsun.com/job/java-deobfuscator/job/Deobfuscator/ specified in the Quick Start section of the Readme is down. Chrome reports "ci.samczsun.com’s server IP address could not be found. DNS_PROBE_FINISHED_NXDOMAIN"

**Comment by namazso** [comment]
a temporary solution is to build it yourself

**Comment by ItzSomebody** [comment]
Seems to be working as of the moment. Try again perhaps?

**Comment by nathanfarlow** [comment]
The download link is back up.
