### ISSUE TITLE
Nothing after detecting known obfuscators

### ISSUE THREAD

**Issue by Jeffmagma** [java-deobfuscator/deobfuscator#540]
Hi, I'm trying to deobfuscate this file, but after `Detecting known obfuscators` nothing happens, does this mean nothing was detected? From opening the source code, it seems like many methods were renamed to java keywords like `do` and `if`.
This is what I ended up with in one class after a small amount of manual deobfuscation:
![image](https://user-images.githubusercontent.com/7827718/78703036-88676280-78d7-11ea-8129-dc2234c03d9c.png)

[Moonwalker.zip](https://github.com/java-deobfuscator/deobfuscator/files/4446255/Moonwalker.zip)

**Comment by Janmm14** [comment]
Use proguard to rename methods again.

**Comment by Jeffmagma** [comment]
I tried that, but the result contains only 4 classes which take up less than a kilobyte, which is much less than the 30+ classes that take up over 60 kb in the jar

**Comment by jackwpa** [comment]
Are you still struggling with that? As an alternative, I just tried JEB on it. Run _Action, Auto-rename All_, with a policy of 100. Things will be nicely renamed:

![image](https://user-images.githubusercontent.com/60268349/78740651-2e34c480-790c-11ea-8e3b-01a3b5adc05d.png)

**Comment by Jeffmagma** [comment]
Oh yeah sorry, I fixed it by unchecking the shrink option in proguard, it removed most of the JavaFX fields and methods that I needed but looked like they were unused because they were only referenced in the FXML

**Comment by ItzSomebody** [comment]
So I have no idea what this is for but frankly some of the URLs seemed sketchy (though admittedly, I didn't look very carefully).

The sample in question looked like it just had class/method/field renaming applied to it which can be done by any number of obfuscators (notably, ProGuard). Since there's really no issue at hand, I'll go ahead and close this.
