### ISSUE TITLE
Is it possible to deobfuscate .litemod (LiteLoader is used for launching)?

### ISSUE THREAD

**Issue by xomka2280** [java-deobfuscator/deobfuscator#541]
I have an obfuscated .litemod and don't know how to decompile it. I tried to redo it in .jar, but it requires the LiteLoader library. Is there any way to remove obfuscation?

**Comment by jackwpa** [comment]
Can you share the jar please?

**Comment by xomka2280** [comment]
> Can you share the jar please?

https://drive.google.com/open?id=1BBU4U3C0O6SSMBZ6hpJ2VqC2WQ_2TULA

**Comment by jackwpa** [comment]
Hmm, I checked. You could use JEB to do that. Change the extension to "jar" and open. You will see lots or derypted strings in the code when decompiling, such as:

![image](https://user-images.githubusercontent.com/60268349/78912459-7a7f2200-7a3c-11ea-8979-45e8cb44b2da.png)
