### ISSUE TITLE
Getting error during deob .jar file

### ISSUE THREAD

**Issue by BrokeMe** [java-deobfuscator/deobfuscator#544]
I've been trying to deob a plugin so i can fix a bug and the dev does not give support anymore ...

Can someone tell mt the correct transformers to deob Stringer ?

im using that ones: 

transformers:
  - com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.ResourceEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.LocalVariableRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalVarargsRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.LineNumberRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.SyntheticBridgeRemover

**Comment by BrokeMe** [comment]
Im getting this error over and over 

[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - I was unable to back up the previous output JAR
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 23 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.LocalVariableRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalVarargsRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.LineNumberRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.SyntheticBridgeRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 0 encrypted strings
[Stringer] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.HideAccessTransformer
[main] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.HideAccessTransformer - Detected the following hide access decryption classes: [com/atlasplugins/armazem/listeners/cm, com/atlasplugins/armazem/apis/pq, com/atlasplugins/armazem/mysql/jk, com/atlasplugins/armazem/commands/c, com/atlasplugins/armazem/mu, com/atlasplugins/armazem/objects/nb]
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 2094ms
[main] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.HideAccessTransformer - Decrypted 0 hide access instruction
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 6 decryptors


Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object Method161(Ljava/lang/Object;)Ljava/lang/Object; @ com/atlasplugins/armazem/rg Method73(Ljava/lang/Object;SZI)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1188)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$1(HideAccessObfuscationTransformer.java:114)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:110)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Janmm14** [comment]
Please try without any normalizer, renamer or remover first. Try one stringer deobfuscator at a time, and add more to thelist as tgey succeed. The order of the stringer transformers is important too, it has to be the reverse order of stringer obfuscation applied, so try switching those around.
Also maybe you want to try stringer v3 transformers and see if tjey have more success.
You might also want to try using the fork of java-deobfuscator by ThisTestUser, it has some fixes and stuff.

**Comment by BrokeMe** [comment]
Hello, im only using the ones without #

         ## PARA TENTAR NORMALIZAR CLASSES, METODOS, ETC ##
#  - com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer
#  - com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer
#  - com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
#  - com.javadeobfuscator.deobfuscator.transformers.general.removers.LocalVariableRemover
#  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalVarargsRemover
#  - com.javadeobfuscator.deobfuscator.transformers.general.removers.LineNumberRemover
#  - com.javadeobfuscator.deobfuscator.transformers.general.removers.SyntheticBridgeRemover

         ## STRINGER ##
#  - stringer.v3.StringEncryptionTransformer
#  - stringer.v3.HideAccessTransformer
#  - stringer.v3.ResourceEncryptionTransformer
#  - stringer.v3.InvokedynamicTransformer

#  - com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v9.StringEncryptionTransformer
  - stringer.v3.StringEncryptionTransformer
#  - com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
#  - com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer
#  - com.javadeobfuscator.deobfuscator.transformers.stringer.ResourceEncryptionTransformer
# - com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer

         ## TIRAR CRASH DO DECOMPILER ##
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover

         ## ALLATORI ##
#  - com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
#  - com.javadeobfuscator.deobfuscator.transformers.allatori.FlowObfuscationTransformer

**Comment by Janmm14** [comment]
Can't really hel pmore into the blue and as you probably are not allowed to share the jar, there is not much more to help.

**Comment by BrokeMe** [comment]
@Janmm14  can i contact you on discord ? it might be urgent pls

**Comment by BrokeMe** [comment]
thats the download link i would like to have the src and the transformers pls

**Comment by BrokeMe** [comment]
https://anonfile.com/Xd2fF8u3o1/bOOks_jar

**Comment by Janmm14** [comment]
I'M not doing deobfuscation for others.
