### ISSUE TITLE
Can't deobf allatori,need some help pls

### ISSUE THREAD

**Issue by zpsw** [java-deobfuscator/deobfuscator#546]
Hi, I'm trying to deobfuscate this file , i used @ThisTestUser allatori.StringEncryptionTransformer but nothing happens,any information will be good , thanks
[input.jar](https://send.firefox.com/download/181655774e5fb17c/#kefg-81zBIOb57DQper3sQ)

**Comment by ThisTestUser** [comment]
That's probably because allatori changed its string encryption signature.
[inputDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4555261/inputDeob.zip)

**Comment by zpsw** [comment]
This is really helpful. thanks a lot.
