### ISSUE TITLE
I cant deobf this file completely

### ISSUE THREAD

**Issue by psg4078** [java-deobfuscator/deobfuscator#547]
https://mega.nz/file/UXJxxArT
plz deobf this file
In deobfed file, I can see the flow obfuscation

**Comment by Janmm14** [comment]
without the key, the link is not usable...

**Comment by psg4078** [comment]
amfitqxDKvxRbDyB01ubm137Pb7XUTJBX9G0_rZFiZg

**Comment by psg4078** [comment]
> without the key, the link is not usable...

I uploaded my key

**Comment by ThisTestUser** [comment]
[mcDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4581881/mcDeob.zip)
There are some errors with the file from the obfuscator:
aux.class is broken
afx.class at (Ljava/lang/Class;Ljava/util/List;Ljava/util/Random;IIIII)Lagq; is glitched
ajq.class at (Ljava/lang/String;Llc;)Z is glitched

**Comment by psg4078** [comment]
> [mcDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4581881/mcDeob.zip)
> There are some errors with the file from the obfuscator:
> aux.class is broken
> afx.class at (Ljava/lang/Class;Ljava/util/List;Ljava/util/Random;IIIII)Lagq; is glitched
> ajq.class at (Ljava/lang/String;Llc;)Z is glitched

What deobfuscator did you use?
