### ISSUE TITLE
Please help me deobfuscate!

### ISSUE THREAD

**Issue by GamerSpook321** [java-deobfuscator/deobfuscator#549]
Hello can someone please deobfuscate it for me and fix the classes please?

[plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/4582540/plugin.zip)

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4582947/PluginDeob.zip)

**Comment by GamerSpook321** [comment]
Thanks!
