### ISSUE TITLE
Please deobfuscate!

### ISSUE THREAD

**Issue by GamerSpook321** [java-deobfuscator/deobfuscator#550]
Hello!
Can someone please deobfuscate this for me and fix the classes?
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/4592685/Plugin.zip)

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4595066/PluginDeob.zip)

**Comment by GamerSpook321** [comment]
Thank you very much!
