### ISSUE TITLE
Please deobfuscate! i really need it!

### ISSUE THREAD

**Issue by GamerSpook321** [java-deobfuscator/deobfuscator#551]
Hello, can someone please deobfuscate this for me, and fix the classes? i really need it <3
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/4598499/Plugin.zip)

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4599289/PluginDeob.zip)

**Comment by ThisTestUser** [comment]
If you would like to deobfucate files similar to this, go to https://github.com/ThisTestUser/deobfuscator/releases, download my deobfuscator, and use allatori.StringEncryptionTransformer, allatori.FlowObfuscationTransformer, and general.removers.LocalVariableRemover.

**Comment by GamerSpook321** [comment]
ALright, thank you for the help!
