### ISSUE TITLE
Stringer 3.1.3 deobfuscation failed

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#556]
JAR: https://www.upload.ee/files/11704541/pchecker-rc.jar.html
Obfuscator: Stringer 3.1.3

**Comment by ThisTestUser** [comment]
[pchecker-rcDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4637616/pchecker-rcDeob.zip)

**Comment by Xed0sS** [comment]
Thanks!
