### ISSUE TITLE
Please deobfuscate this!

### ISSUE THREAD

**Issue by GamerSpook321** [java-deobfuscator/deobfuscator#557]
Hello, can someone please deobfuscate this for me and fix the classes?
It isnt obfuscated with allatori i see 
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/4670414/Plugin.zip)

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4672774/PluginDeob.zip)

**Comment by GamerSpook321** [comment]
Thank you very much!
