### ISSUE TITLE
Error stringer.StringEncryptionTansformer

### ISSUE THREAD

**Issue by nedogimov** [java-deobfuscator/deobfuscator#559]
> [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 63 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%

> Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
> java.lang.NullPointerException
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1025)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
>         at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
>         at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1357)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
>         at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
>         at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1357)
>         at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
>         at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:486)
>         at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:101)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
It looks like there might be another layer of obfuscation in the JAR besides Stringer.

**Comment by nedogimov** [comment]
> It looks like there might be another layer of obfuscation in the JAR besides Stringer.
pls decompile xD superblaubeere27 obfuscator


[HWIDTest (1).zip](https://github.com/java-deobfuscator/deobfuscator/files/4681021/HWIDTest.1.zip)

**Comment by ThisTestUser** [comment]
[HWIDTestDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4683092/HWIDTestDeob.zip)
If you are having problems opening the jar in bytecode viewer, simply run the deobfuscator with no transformers and decompile the output JAR.
