### ISSUE TITLE
Please deobfuscate.

### ISSUE THREAD

**Issue by Boniarz** [java-deobfuscator/deobfuscator#561]
Hi, can you deobf this?
Thanks.
https://mega.nz/file/QWJhAYIJ#IBI2pXow3XK7JlKZSCeRiK0itWrkHyrmTRvF2TAL7Mw

**Comment by ThisTestUser** [comment]
[proxyDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4690235/proxyDeob.zip)
