### ISSUE TITLE
DashO RunTimeException: SourceResult has different values

### ISSUE THREAD

**Issue by ptrtonull73331** [java-deobfuscator/deobfuscator#565]
![b](https://user-images.githubusercontent.com/65843086/83119365-79ee2980-a084-11ea-956c-5251193a0ce5.PNG)

**Download Link**: https://www.dropbox.com/s/4v7invubsdt3hxt/b.zip?dl=1

detect.yml and config.yml is inside the zip file too. Appreciate the help!

**Comment by ThisTestUser** [comment]
[b_extractedDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4699502/b_extractedDeob.zip)
This is caused by DashO's flow obfuscation. Asides from a couple of methods which I skipped, the code should look fine now.
