### ISSUE TITLE
Deobfuscating a possible superblaubeere27 Obfuscator

### ISSUE THREAD

**Issue by CodexApple** [java-deobfuscator/deobfuscator#567]
Is it possible to deobfuscate SuperBlaub's obfuscator using your Tool?
or at least be able to send the file for deobfuscation if that is possible?

**Comment by CodexApple** [comment]
Here is the link if its possible thank you.
https://mega.nz/file/FRszHYTA#RRNLLfA8u2jT-dklREhMDFliZp928V6D0rlATqXNEbg

**Comment by ThisTestUser** [comment]
There's only name obfuscation in the file. You should probably use another tool to deobfuscate the names.
