### ISSUE TITLE
Please deobfuscate this, i really need it!

### ISSUE THREAD

**Issue by GamerSpook321** [java-deobfuscator/deobfuscator#568]
Hello, i have a minecraft plugin that i really want to deobfuscate can someone do that for me and fix the classes please?
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/4719060/Plugin.zip)

**Comment by ThisTestUser** [comment]
Give me your discord, we'll talk privately.

**Comment by GamerSpook321** [comment]
MoneyMonkey#1873
