### ISSUE TITLE
Help me to deobf file

### ISSUE THREAD

**Issue by nedogimov** [java-deobfuscator/deobfuscator#569]
I have already used some transformers. I can’t deobfuscate classes: Class0, Class4, Class5 :( 
I hope for your help 
[out.zip](https://github.com/java-deobfuscator/deobfuscator/files/4732553/out.zip)

**Comment by ThisTestUser** [comment]
Everything in the file is already deobfuscated. There is still some junk code left, but you can send your original file if you want a cleaner version.

**Comment by nedogimov** [comment]
> Everything in the file is already deobfuscated. There is still some junk code left, but you can send your original file if you want a cleaner version.

Thank :3
[Loader.zip](https://github.com/java-deobfuscator/deobfuscator/files/4732807/Loader.zip)

**Comment by ThisTestUser** [comment]
[LoaderDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4732873/LoaderDeob.zip)
