### ISSUE TITLE
Field and methods renaming problem

### ISSUE THREAD

**Issue by netindev** [java-deobfuscator/deobfuscator#57]
![capturara](https://cloud.githubusercontent.com/assets/12552712/18244915/c9dcea9e-7338-11e6-9b2c-7d827298597c.PNG)
![capturar](https://cloud.githubusercontent.com/assets/12552712/18244916/c9e666b4-7338-11e6-9c11-1c288c365667.PNG)

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
