### ISSUE TITLE
Help me to deobfuscate this Jar

### ISSUE THREAD

**Issue by zecca-thor** [java-deobfuscator/deobfuscator#570]
Hey @ThisTestUser
could you please deobfuscate me this jar?
It's obfuscated with Radon 1.0.5 !
And can you explain to me how did you do because I can't me please.

[infected.zip](https://github.com/java-deobfuscator/deobfuscator/files/4742012/infected.zip)

**Comment by ThisTestUser** [comment]
[infectedDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4742662/infectedDeob.zip)
It's a private deobfuscator.

**Comment by zecca-thor** [comment]
ok, thanks
