### ISSUE TITLE
Unknown obfuscator, can't deobf

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#572]
I can't deobf this jar, because get an error during deobfuscation process :(

JAR: https://www.upload.ee/files/11857886/fonts-client-obf.jar.html

**Comment by Xed0sS** [comment]
@ThisTestUser 🤔

**Comment by ThisTestUser** [comment]
[fonts-client-obfDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4772469/fonts-client-obfDeob.zip)
