### ISSUE TITLE
Allatori String Unobf

### ISSUE THREAD

**Issue by wEisB0145** [java-deobfuscator/deobfuscator#58]
Hello! My problem is that some strings get unobfuscated and some not.

My task is to test a allatori obfuscation and I have to unobfuscate some strings. Sadly I cant send the jar because the owner doesn't want it...

For example: This string cant get unobfuscated (in fact the String decrypter doesn't even touch it): AQRFJA
But this simple string gets decrypted: http://prntscr.com/ch43wa

Can you help me?

**Comment by Janmm14** [comment]
Edit the deobfuscator yourself. Or simply send the jar in. Allatori is basically free so anyone could obfuscate a sample and see the changed algorithm. (Seems like there may be two different algorithms)

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
