### ISSUE TITLE
Hello! Deobfuscate this please!

### ISSUE THREAD

**Issue by TheKlimoT** [java-deobfuscator/deobfuscator#580]
[archivess.zip](https://github.com/java-deobfuscator/deobfuscator/files/4780068/archivess.zip)

**Comment by ThisTestUser** [comment]
[ExsiteStatusoDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4780535/ExsiteStatusoDeob.zip)
Next time, change the JAR to a zip and upload it instead of putting the JAR into a zip.
