### ISSUE TITLE
Deobfuscate this. Thanks!

### ISSUE THREAD

**Issue by TheKlimoT** [java-deobfuscator/deobfuscator#586]
Hello deobfuscate this!

[AdvancedAbilities.zip](https://github.com/java-deobfuscator/deobfuscator/files/4821766/AdvancedAbilities.zip)

**Comment by GreatZardasht** [comment]
bruh you cant do it yourself? you are wasting these guys time, this is made for deobfuscting and this is for issues not a place to ask people deobfuscate stuff for you.

**Comment by febryanasaperdana** [comment]
Have you tried it on your own?
This is not a free deobfuscation service.
You should try deobf-ing on your own first.

**Comment by Janmm14** [comment]
btw i already reported this to the spigotmc premium plugin author months ago ;)

**Comment by rucko24** [comment]
![image](https://user-images.githubusercontent.com/17187599/93365914-b370bd80-f84a-11ea-9d92-53e9a3124d91.png)
