### ISSUE TITLE
Help me because i can't decompile this.

### ISSUE THREAD

**Issue by jadsspt** [java-deobfuscator/deobfuscator#587]
Ok, so, this Is a Radon v1.0.5 obfuscation sample, can someone decompile it? 
[Zip.zip](https://github.com/java-deobfuscator/deobfuscator/files/4832659/Zip.zip)

**Comment by ThisTestUser** [comment]
[CACDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4976250/CACDeob.zip)
