### ISSUE TITLE
Some weird error

### ISSUE THREAD

**Issue by Hemonios** [java-deobfuscator/deobfuscator#591]
I m trying to deobfuscate aegis, a bungeecord fork, my config is

input: aegis.jar
output: output.jar
path: 
  - rt.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover

**Comment by Janmm14** [comment]
Normalizers don't deobfuscate.And IllegalSignatureRemover is fine, but not enough.

**Comment by Enteerman** [comment]
What is the error?

**Comment by ItzSomebody** [comment]
I think enough time has passed where this can be closed. Feel free to reply if that's not the case.
