### ISSUE TITLE
please, deobj file

### ISSUE THREAD

**Issue by keyfqsY** [java-deobfuscator/deobfuscator#592]
thanky :)
https://dropmefiles.com/wnM5g

**Comment by Janmm14** [comment]
jar file very likely does not contain any classes you want to have a closer look at.

**Comment by keyfqsY** [comment]
Contains 100%. )

**Comment by keyfqsY** [comment]
I don’t understand English and am translating Google translator now. I don’t understand what you mean, I just need a deobfucted .jar
