### ISSUE TITLE
Deobfuscate this file! Thanks you.

### ISSUE THREAD

**Issue by TheKlimoT** [java-deobfuscator/deobfuscator#593]
[AdvancedAbilities.zip](https://github.com/java-deobfuscator/deobfuscator/files/4866590/AdvancedAbilities.zip)

**Comment by ThisTestUser** [comment]
Download the latest version of deobfuscator (1.1.1) from the releases page, and then run allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer.
