### ISSUE TITLE
Error while deobf ZKM 12

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#595]
I have a random error while deobf, idk how to fix it, please deobf this jar :C
JAR: https://www.upload.ee/files/11968551/skillpvp.jar.html
Obfuscator: ZKM

**Comment by Janmm14** [comment]
this tool does not support newer zkm deobfuscation

**Comment by Xed0sS** [comment]
Feels bad, may be @ThisTestUser can deobf this ;C

**Comment by Xed0sS** [comment]
@ThisTestUser dude, release me :c

**Comment by ThisTestUser** [comment]
Deobbed, but only because the file wasn't using the features available in ZKM 9+.

[skillpvpDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4975888/skillpvpDeob.zip)
