### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by lucasparmentier** [java-deobfuscator/deobfuscator#598]
I'm using the GUI tool and the console freeze just before launching detection
`[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
`
how many time is it supposed to take?

**Comment by ThisTestUser** [comment]
You can look at the threadtear repo (https://github.com/GraxCode/threadtear) if you want to find out what obfuscators the file used.

**Comment by ItzSomebody** [comment]
@OP I'm closing this since this was made several months ago with little information to work from. Feel free to reopen if needed.
