### ISSUE TITLE
None of Transformers working

### ISSUE THREAD

**Issue by apkunpacker** [java-deobfuscator/deobfuscator#599]
[input.jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/4959790/input.jar.zip)
I tried all transformer but strings remain encrypted  . Please help to decrypt string or if possible provide used transformer please.
Thanks

**Comment by jackwpa** [comment]
- add a META-INF folder in the archive
- open with JEB
- open up input.jar.apk in the project explorer menu, then the "bytecode" node under it
- start a global analysis (Android menu), make sure to remove a filter if there is one
- wait 1-2 min.
- everything will get decrypted, you will see 10,000 events, most of them DECRYPTED_STRING

**Comment by apkunpacker** [comment]
I not have JEB buddy . If you have please decrypt string / may be "Decompile all" and send . Thanks a lot

**Comment by apkunpacker** [comment]
@ThisTestUser , @Janmm14 requesting you to please deobfuscate

**Comment by ThisTestUser** [comment]
[input.jarDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4975950/input.jarDeob.zip)
Managed to edit dasho.StringEncryptionTransformer to deobfuscate your file.
[StringEncryptionTransformer.txt](https://github.com/java-deobfuscator/deobfuscator/files/4975953/StringEncryptionTransformer.txt)
If you would like to run this yourself, you have to add java/lang/String.getBytes() and java/lang/Integer.parseInt(String, int) to JVMMethodProvider.

**Comment by apkunpacker** [comment]
Thanks a lot . Just last request to provide jar built with this transformer , not urgent need but i have 100's of apps with same obfuscation so everytime disturbing you is not good as compile never success for me if i try myself . give your discord id please so i can contact you there .
Thanks

**Comment by apkunpacker** [comment]
![Screenshot_2020-07-26-10-01-03-55](https://user-images.githubusercontent.com/27184655/88471461-8decc500-cf27-11ea-80dc-6e46b80d6362.jpg)

**Comment by apkunpacker** [comment]
Please send modified JVMMethodProvider.java also

**Comment by ThisTestUser** [comment]
[StringEncTransformer.zip](https://github.com/java-deobfuscator/deobfuscator/files/4977777/StringEncTransformer.zip)
The latest release of deobfuscator (1.2.0) has the methods inserted in, so you don't need to worry about JVMMethodProvider. Just drag the class file in the zip to com/javadeobfuscator/deobfuscator/transformers/dasho.

**Comment by apkunpacker** [comment]
Thank you . It worked
