### ISSUE TITLE
Deobf

### ISSUE THREAD

**Issue by TheKlimoT** [java-deobfuscator/deobfuscator#603]
deobf zip. thanks!
[Core-1_12_2.zip](https://github.com/java-deobfuscator/deobfuscator/files/4996838/Core-1_12_2.zip)

**Comment by ThisTestUser** [comment]
Download the latest version of deobfuscator (1.2.1) from the releases page, then use stringer.StringEncryptionTransformer and stringer.HideAccessObfuscationTransformer.
