### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by MeesMaster5000** [java-deobfuscator/deobfuscator#604]
Do you have any way to contact you outside of github, (for example: Discord, Twitter)?

**Comment by ThisTestUser** [comment]
Comment your discord here and I'll add you.

**Comment by apkunpacker** [comment]
@ThisTestUser pleass add me apkunpacker#8132 on discord

**Comment by MeesMaster5000** [comment]
@ThisTestUser null#6736

**Comment by theblackturtle** [comment]
Sorry for re-open this. 
@ThisTestUser can you add me theblackturtle#2578 on Discord. Thanks.
