### ISSUE TITLE
Error on deobfuscation

### ISSUE THREAD

**Issue by LeoGamerG0D** [java-deobfuscator/deobfuscator#606]
Error: [main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - A config file
must be specified

My Config.yml:

input: 1.jar
output: 1-deob.jar
transformers:
   - allatori.StringEncryptionTransformer
   - allatori.string.StringEncryptionTransformer

**Comment by Janmm14** [comment]
use `--config config.yml` at the end of your start command

**Comment by LeoGamerG0D** [comment]
Oh, thanks!
