### ISSUE TITLE
Do  you can?

### ISSUE THREAD

**Issue by LeoGamerG0D** [java-deobfuscator/deobfuscator#607]
Help, deob this for me, plz

https://www.mediafire.com/file/ugbhc7bantab4rg/file

**Comment by ThisTestUser** [comment]
Use stringer.StringEncryptionTransformer, and then stringer.HideAccessTransformer. Be sure to add all the libraries (rt.jar, spigot.jar).

**Comment by LeoGamerG0D** [comment]
how to add libraries?

**Comment by ThisTestUser** [comment]
Use the GUI to run the deobfuscator, and add the jar files to "path".
