### ISSUE TITLE
Anyway can't deobf jar

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#609]
I run allatori.StringEncryptionTransformer 10-15 times to get rid of the string encryption, then I run allatori.FlowObfuscationTransformer and LocalVariableRemover, but nothing deobfuscated, strings are encrypted, methods too...

JAR: https://www.upload.ee/files/12107873/mc.jar.html

**Comment by ThisTestUser** [comment]
Then run the string encryption transformer several more times, until it says that 0 strings were decrypted.

**Comment by Xed0sS** [comment]
I tried, anyway strings and methods still obfed :c

**Comment by ThisTestUser** [comment]
What do you get after running those transformers? Upload the JAR outputted and I'll see what's wrong.

**Comment by Xed0sS** [comment]
Idk, but strings are obfuscated after deobfuscation :\

JAR: https://www.upload.ee/files/12119313/mc_deobf.jar.html

**Comment by ThisTestUser** [comment]
Run allatori.StringEncryptionTransformer one more time and the file is decrypted.

**Comment by Xed0sS** [comment]
Lmao, I did everything as u said, but nothing helped me, the file is still encrypted, transformers not works, deobf too, string decryption returned obfuscated strings.

**Comment by ThisTestUser** [comment]
[mc_deobfDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/5048039/mc_deobfDeob.zip)
Not sure what you mean, but I ran it on mc_deobf.jar and it was fully deobfuscated.

**Comment by Xed0sS** [comment]
Oh shi, I'm stupid, I used old version :(
