### ISSUE TITLE
A bit of help

### ISSUE THREAD

**Issue by Perfect-Lies** [java-deobfuscator/deobfuscator#610]
Hello,

I've recently tried to decompile a minecraft spigot plugin, I'm just intrested into the source code, and its obfuscated.
I managed to to deobfuscate it to some extent. But I still get some weirdly encrypted strings. Could you give me a fev pointers to how to deobfuscate these strings?
*(Sorry if this is a stupid post I'm new to deobfuscating/obfuscating)*

For some more context I'll provide my files

Original jar - http://www.mediafire.com/file/23tg3mt7iqws73m/plugin.jar/file
Deobfuscated jar (not completley) - http://www.mediafire.com/file/upeibm5vffe5hum/plugin-deobf-1.jar/file
Online decompiler - http://www.decompiler.com/jar/a2bca0551d624c368385dd39bed056c9/plugin-deobf-5.jar
Config - https://pastebin.com/AMJ55K2g

*(If I missed anything just tell me and I'll provide it)*

Thanks in advance!

**Comment by ThisTestUser** [comment]
Download the latest deobfuscator.jar and use special.RadonTransformer.

**Comment by Princekiin** [comment]
Im not sure about the obfuscator used, but as you can see all the strings get decrypted by a method with invisible name (\u202e\u2004\u2003\u2004\u2003) present in class **xyz.yooniks.protector.bukkit.listener.normal.TooManyItemsListener$BlockPlacePacketAdapter** .
This string encryption is pretty easy to remove, the method is just reciving a string (the encrypted one) and the key as input.
Java deobfuscator doesnt support this string encryption, but you can try to manually decrypt them or implement this string encryption deobfuscator by yourself. 
String Decryption class: [https://hatebin.com/qvsyzkzepb](url)
