### ISSUE TITLE
deobfuscation // A bit of help

### ISSUE THREAD

**Issue by PbIBa** [java-deobfuscator/deobfuscator#611]
I've recently tried to decompile a minecraft spigot plugin, I'm just intrested into the source code, and its obfuscated. If I give you plugin that will be able to competently remove deobfuscation? Plugin uses **Stringer**.
_(Sorry if this is a stupid post I'm new to deobfuscating/obfuscating)_

**Comment by ThisTestUser** [comment]
Use stringer.StringEncryptionTransformer and stringer.HideAccessObfuscationTransformer. Be sure to add the libraries (spigot.jar).

**Comment by PbIBa** [comment]
> Use stringer.StringEncryptionTransformer and stringer.HideAccessObfuscationTransformer. Be sure to add the libraries (spigot.jar).

How can I add a library that needs to be entered in config.yml?

**Comment by ThisTestUser** [comment]
Use deobfuscator-gui (https://github.com/java-deobfuscator/deobfuscator-gui) and add the libraries.

**Comment by PbIBa** [comment]
> Use deobfuscator-gui (https://github.com/java-deobfuscator/deobfuscator-gui) and add the libraries.


** DO NOT OPEN AN ISSUE ON GITHUB **
Could not locate a class file.
Have you added the necessary files to the -libraries argument?

**Comment by PbIBa** [comment]
https://i.imgur.com/oEKotrO.png

**Comment by ThisTestUser** [comment]
You need to add rt.jar from your java installation directory.

**Comment by PbIBa** [comment]
> You need to add rt.jar from your java installation directory.

in Path? or libraries

**Comment by PbIBa** [comment]
> You need to add rt.jar from your java installation directory.
INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing (**Is this the end?**)

**Comment by Janmm14** [comment]
If the output file exists and its filled, then thats the end.

**Comment by PbIBa** [comment]
Thank!

> If the output file exists and its filled, then thats the end.
