### ISSUE TITLE
Is it possible to deobfuscate this? its giving me errors.

### ISSUE THREAD

**Issue by GreatZardasht** [java-deobfuscator/deobfuscator#612]
https://www.mediafire.com/file/dl6ax4rpw4d33wc/Jigsaw.jar/file
The detect thing in gui version of this says to use normalizer sourcefileclassnormalizer and i think i also used package normalizer, idk
i use it and it says error (filepath) Using COMPUTE_MAXS
It gives me a deobfuscated version but its not fully deobfuscated, i want it to look exactly like what the source code would have looked like
This is the deobfuscated but not fully file https://www.mediafire.com/file/bi5sbzfdcbp7wsw/Jigs1111aw.jar/file
what other deobfuscation methods should i use to get a version that looks exactly or almost excatly like the source code version?

**Comment by ThisTestUser** [comment]
The file only has name obfuscation, so there's nothing the deobfuscator can do.

**Comment by GreatZardasht** [comment]
> The file only has name obfuscation, so there's nothing the deobfuscator can do.

How do i make it so it looks like a source file?

**Comment by ThisTestUser** [comment]
You can use SourceFileClassNormalizer, which brings back the original names of the class files. You can't bring back the method and field names, because they have been removed.
