### ISSUE TITLE
What deobfuscation method deobfuscates stuff like func_179962?

### ISSUE THREAD

**Issue by GreatZardasht** [java-deobfuscator/deobfuscator#616]
What deobfuscation method deobfuscates stuff like func_179962?

**Comment by Janmm14** [comment]
The method renamer of this deobfuscator does that

**Comment by GreatZardasht** [comment]
oh ok

**Comment by psg4078** [comment]
it is an basic minecraft obfuscation juse use MCP to deobfuscate it

**Comment by Enteerman** [comment]
https://github.com/java-deobfuscator/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/minecraft
