### ISSUE TITLE
Please help deobfuscate the jar file.

### ISSUE THREAD

**Issue by SimpeMine** [java-deobfuscator/deobfuscator#617]
I have no idea what this jar file is covered with and how to deobfuscate it.
https://www.upload.ee/files/12164313/1.14.4.jar.html

**Comment by Janmm14** [comment]
looks to me like some custom obfuscation. Seems to not be very poweful, it'd be easy to write a transformer for this. But I won't deobfuscate this. Also looks like the actual minecraft in there is not obfuscated.

**Comment by SimpeMine** [comment]
Please help deobfuscate this.
