### ISSUE TITLE
What would be the best way to deobfuscate this? (to a level that seems or is like the sourcecode)

### ISSUE THREAD

**Issue by GreatZardasht** [java-deobfuscator/deobfuscator#618]
What would be the best way to deobfuscate this? (to a level that seems or is like the sourcecode)
https://mega.nz/file/P6gG3YYY#h-UQ13Nh59vW3F4VuHKYQPaMtefEPvtxuWs_Cz_7lrM
if you need .json file also
https://mega.nz/file/qiI33KiR#6gm9ceOIQKyJ9YEdoJauGTtLvPzj1ht8kAl92Xa-JOo

**Comment by Janmm14** [comment]
That is only name obfuscation. Also the MCP deobfuscation static string field containg a string starting with CL_ is still present.

I think an easy way to debofuscate this is to use https://github.com/octarine-noise/simpledeobf

**Comment by Enteerman** [comment]
You can't recover the original names if the application has been obfuscated.

See https://github.com/java-deobfuscator/deobfuscator#it-didnt-work
