### ISSUE TITLE
After some attempts, still can't desobfuscate that file

### ISSUE THREAD

**Issue by julienh1** [java-deobfuscator/deobfuscator#623]
Hi,  
I try to deofuscate that file : https://www.swisstransfer.com/d/3606574a-0bee-4283-8a29-aebdd62484b0

I  tried to run many tranformers such as :  
*  allatori.StringEncryptionTransformer
 * allatori.FlowObfuscationTransformer
 * allatori.LightFlowObfuscationTransformer
 * stringer.v3_1.StringEncryptionTransformer

The software works but the output jar file remains obfuscated with many classes named 'a', 'b', 'c.a.a.a' and so on.

Could you help me with deobfuscating that file ?  
Thanks !

**Comment by Janmm14** [comment]
Class, method and field names are usually lost forever during obfuscation.

Looking at the provided jar file, it seems to not be obfuscated bejond class, method and field renaming.

As the source file attribute was removed as well, there is no way to get the information back automatically. I think all you can do is use a program like Luyten to manually rename classes, methods and fields based on its containing code.

**Comment by julienh1** [comment]
Ok thank you very much, I will investigate.
Just a question, when you talk about "source file attribute" what do you mean exactly ?

**Comment by Janmm14** [comment]
https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.10

The source file attribute is displayed in java stack traces before the line number.
Some bad obfuscators rename the classes, but forget to edit or remove the SourceFile attribute, therefore the original class name is recoverable.

**Comment by julienh1** [comment]
Ok got it, thanks again !
