### ISSUE TITLE
Any ideas on how to deobfuscate this? me and my friends all get an error ...

### ISSUE THREAD

**Issue by GreatZardasht** [java-deobfuscator/deobfuscator#624]
Any ideas on how to deobfuscate this? me and my friends all get an error saying java.lang.OutOfMemoryError: Java heap space
Its just a minecraft client but wow is it heavily obfuscated
http://www.mediafire.com/file/toq3xf8aigmppzc/1.16-rc1.jar/file
any ideas on how to deobfuscate it?

**Comment by Janmm14** [comment]
Worked for me with -Xmx4G

**Comment by GreatZardasht** [comment]
> Give it more Ram. I've tried it with 4 GB, but it looks like that still wasn't enough, but I think there needs to be some custom transformer written for parts of that obfuscation anyway. However I'm also the deobufscator with a couple edits from me, so 4 GB ram might work for you.

How do i give it 4gb ram? im using the gui version, should i use terminal one instead? if i do use the terminal one, what transformers should i use?

**Comment by Janmm14** [comment]
You can start the gui with more ram via the console. I suggest that you give it 5 or 6 GB for the first couple PeepholeOptimizer runs.

**Comment by GreatZardasht** [comment]
> I suggest that you give it 5 or 6 GB for the first couple PeepholeOptimizer runs. After that, this program probably requires some custom peephole transformers to get rid of more flow obfuscation. Also I think that it needs custom string obfuscation as well.

when you say custom, do you mean as in i have to make my own transformer? if so, how?

**Comment by Janmm14** [comment]
Yes, you'd have to create transformers yourself.

This requires knowledge of java bytecode. You have to look at the bytecode, identify how the string obfuscstion works and then write code to detect it and code to simulate the execution of the string decryption routine. You can look at other transformers to get clues.

The flow obfuscation seems to be very advanced, maybe @ThisTestUser has an idea of how to deobfuscate that.

**Comment by Showdown76py** [comment]
lol you cant unobfuscate sigma sad

**Comment by Janmm14** [comment]
> lol you cant unobfuscate sigma sad

what a useless comment
