### ISSUE TITLE
Deobfuscation superblaubeere27 please

### ISSUE THREAD

**Issue by byaatlas** [java-deobfuscator/deobfuscator#635]
I can deobfuscate this? http://www.mediafire.com/file/qsrw4yilsmxuanp/AtlasLicensePP.jar/file

John.

**Comment by Janmm14** [comment]
This is not just superblaubeere27 obfuscator, its also Stringer 9.1.15

**Comment by byaatlas** [comment]
Thanks, it's possible with deobfuscator?

**Comment by Janmm14** [comment]
Apparantly the file was once obfuscated with Stringe,r but that obfuscation is completely absent already. Only some string obfusction, what you identified as superblaubeere27 is left.

I have a transformer for that already written and I just had to change a number here and there to make it work with your sample, but unfortunaly for you I am not a guy who ignores intellectual property.

I am on here so I can extend my private deobfuscation transformers with some new deobfuscation techniques for fun and for the challenge.

Decrypting the strings of that obfuscator is fairly easy done, just take some simple existing StringEncryptionTransformer and edit it a little to work on a ldc-ldc-invokestatic pattern. More annoying to code is probably the constant propagation from the array of string values to the array access places.

**Comment by febryanasaperdana** [comment]
> Apparantly the file was once obfuscated with Stringer or someone put a sign for stirnger obfuscation in there as a joke, but that obfuscation is completely absent already. Only some string obfusction, what you identified as superblaubeere27 is left.
> 
> I have a transformer for that already written and I just had to change a number here and there to make it work with your sample, but unfortunaly for you I am not a guy who ignores intellectual property.
> 
> I am on here so I can extend my private deobfuscation transformers with some new deobfuscation techniques for fun and for the challenge.
> 
> Decrypting the strings of that obfuscator is fairly easy done, just take some simple existing StringEncryptionTransformer and edit it a little to work on a ldc-ldc-invokestatic pattern. More annoying to code is probably the constant propagation from the array of string values to the array access places.

Great answer, mate. Not ignoring intellectual property means respecting the hard work of the owner.

Looks like there are many request to deobfuscate license file/code, commercial plugins, etc. and from what I see, they're not the appropriate owner of the code. It has surely become more toxic as more and more people opened the issue to ask for "free deobfuscation" for "the code that is not theirs".

**Comment by Enteerman** [comment]
This is not related to this project. Although the program is named "deobfuscator", deobfuscating a specific program that you do not own is illegal, and no one will care to deobfuscate your program. Please close this.
