### ISSUE TITLE
Someone can deobfuscate this code?

### ISSUE THREAD

**Issue by vicen621** [java-deobfuscator/deobfuscator#637]
please, someone help me, i try for a long time and I cant
https://cdn.discordapp.com/attachments/731399068835905598/758203914029105161/DeathNightmares.jar

**Comment by Enteerman** [comment]
No. No one should be obliged to help you, even if you own the program. This should be a place to report issues and bugs that exists in the project, and not the fact that it can't deobfuscate some specific java programs.
