### ISSUE TITLE
Dexguard features

### ISSUE THREAD

**Issue by ikanekb** [java-deobfuscator/deobfuscator#64]
I saw that deobfuscator readme states Dexguard support but I don't see any valid transformer for Dexguard. Is it really supported? or plans to support in future?

Thx

**Comment by samczsun** [comment]
Looking through my notes I see that I've deprecated a DexGuard InvokeDynamicTransformer, but I haven't yet made available the generic InvokeDynamicTransformer yet. This is something that I've been meaning to do for a while but have not had time to clean up and test (many more transformers are also in this state of kinda-broken-kinda-done).

I suppose you could say that it's planned for the future, but technically a branch of the deobfuscator supports it ;)

**Comment by Vinc0682** [comment]
Can you please public these half done transformers? I'd really enjoy to see what genious stuff is comming to my favorite deobfuscator...
