### ISSUE TITLE
Hey I was waiting a long time for superblaubeere27 transformer but it didn't come. I was searching about it but I didn't find. Can u deobfuscate this file for me?

### ISSUE THREAD

**Issue by snuckdev** [java-deobfuscator/deobfuscator#640]
Can u deobfuscate this file for me? I think it is obfuscated with superblaubeere27
[MitoPlugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/5322189/MitoPlugin.zip)

**Comment by snuckdev** [comment]
Transformer added.

**Comment by Janmm14** [comment]
not added. existing transformer got renamed so you can find it
