### ISSUE TITLE
Issues and Documentation

### ISSUE THREAD

**Issue by Enteerman** [java-deobfuscator/deobfuscator#641]
This project has gained a lot of attention (as you can see with the stars and forks), but, the project lacks documentation and collaborators that manages issues(labeling, closing invalids). I opened this issue because if possible, I would like to volunteer to manage the project.

**Comment by ThisTestUser** [comment]
I don't have permission to add new members, so maybe @samczsun could help you with that.

**Comment by samczsun** [comment]
I gave you the triage role! Thanks for your help!

**Comment by febryanasaperdana** [comment]
Would like to cooperate in managing and answering those issues as well.
