### ISSUE TITLE
deobf ?

### ISSUE THREAD

**Issue by ENDMod** [java-deobfuscator/deobfuscator#647]
afther i deobf all there is still some class that is lll.class or l.classs (JOBF)
there is aslo some method would be call like Has this
    private static boolean lambda$saveConfigurationUnsafe$7(final Component component) {
        return component instanceof Frame;
    }
there woull have $7 thingy

**Comment by Janmm14** [comment]
The java compiler introduces methods for lambdas written in code. The decompiler you used is apparantly not lambda-aware and therefore does not change back the "syntactic sugar" of lambdas. Use another decompiler or edit such stuff by yourself.

This deobfuscator specializes on deobfuscating code flow obfuscation and constants in bytecode.

**Comment by ItzSomebody** [comment]
Epic answer from @Janmm14.
