### ISSUE TITLE
Cfg error

### ISSUE THREAD

**Issue by sysysysy242** [java-deobfuscator/deobfuscator#649]
The cfg don't work, how to fix this : 
![image](https://user-images.githubusercontent.com/45331186/96004332-8f999b00-0e3b-11eb-9e1f-5d7f90121f88.png)

**Comment by Janmm14** [comment]
your config does not have the correct syntax. you need ` - ` before names of transformers.

**Comment by sysysysy242** [comment]
![image](https://user-images.githubusercontent.com/45331186/96013129-35053c80-0e45-11eb-8252-655a2830a949.png)

**Comment by sysysysy242** [comment]
Thks
