### ISSUE TITLE
Can't deobf unknown obf

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#652]
I get some error, please deobf this shit

JAR: https://www.upload.ee/files/12409404/divinerpg-client-obf.jar.html

**Comment by Janmm14** [comment]
This is no deobfuscation request forum anymore.

What you can do:

Formulate this as a feature request of the obfuscation method you encountered. Should include a quick analysis of the obfuscation.

In general please provide more information:
- errors that may occur
- failed attempts
- configuration file
- detect output

The issue like it is currently would just get closed.
