### ISSUE TITLE
Superblaubeere transformer not working

### ISSUE THREAD

**Issue by Rattlyy** [java-deobfuscator/deobfuscator#654]
Hey, i tryed deobfuscating with Superblaubeere transformer. It didnt work,

Here's the before and after: http://www.mediafire.com/file/z0irckb7pc0k9hk/files.zip/file

**Comment by Janmm14** [comment]
You are not allowed to publish those files as they contain files copyrighted by mojang.
See #653 

@Enteerman @ItzSomebody 
Please close this issue.

**Comment by snuckdev** [comment]
Lol let' see what's in this zip
