### ISSUE TITLE
Error: java/lang/Exception could not be found while writing w/b/e/B. Using COMPUTE_MAXS

### ISSUE THREAD

**Issue by 6ixDev** [java-deobfuscator/deobfuscator#656]
Hello
So, when I try deobfuscating this .class file which is located in an jar, i get the following error:

`Error: java/lang/Exception could not be found while writing w/b/e/B. Using COMPUTE_MAXS`

.class-file: https://workupload.com/file/w377wEk6hVY

Decompiled .class-file (using Fernflower):
`package w.b.e;

public class B {
    public B() {
        boolean var10000 = true;
        boolean var10001 = true;
        boolean var10002 = true;
        boolean var10003 = true;
        super();
    }

    public static void k() {
        boolean var10000 = true;
        boolean var10001 = true;
        boolean var10002 = true;
        boolean var10003 = true;
        g();
        c();
        l();
        K();
        B();
        ALLATORIxDEMO();
    }
}`

`transformers:
  - allatori.StringEncryptionTransformer
  - allatori.string.StringEncryptionTransformer
  - allatori.LightFlowObfuscationTransformer
  - allatori.FlowObfuscationTransformer`

Command used to run deobfuscator:
java -Xss128M -jar deobfuscator.jar -config config.yml

Hopefully someone knows how I can solve this.
Have a nice day!

Edit: I tried my best to get the codeblocks to work.

**Comment by Enteerman** [comment]
Please include the java runtime library in the config. You must use java 8 to get the rt.jar.

**Comment by Janmm14** [comment]
You can obtian an rt.jar on newer java versions with https://github.com/Storyyeller/jrt-extractor

**Comment by 6ixDev** [comment]
Alright, adding the lines
`libraries:
  - "C:/Program Files/Java/jre1.8.0_211/lib/rt.jar"`
to my config.yml did the trick.
Thanks! 👍
