### ISSUE TITLE
Help me please with deobfuscator from superblauberee27

### ISSUE THREAD

**Issue by fellicienne** [java-deobfuscator/deobfuscator#657]
![image](https://user-images.githubusercontent.com/73531185/97295540-78f23b80-1860-11eb-8d7d-763b4bc61046.png)
I don't quite understand how to do it
![image](https://user-images.githubusercontent.com/73531185/97295654-a5a65300-1860-11eb-9098-c53df04d923e.png)
after starting, I immediately get a decompilation error
I did not add the path and libraries, because I do not know what
how to deobfuscate correctly, please tell me

**Comment by Janmm14** [comment]
You can edit JVMMethodProvider and add that method to MessageDigest$Delegate

**Comment by fellicienne** [comment]
Janmm14 ,can I somehow contact you, for example, via discord?

**Comment by Janmm14** [comment]
I'm sorry. The problem you got there is not because something is missing in JVMMethodProvider, but it actually happened because you did not add rt.jar as path jar

**Comment by konichiwa-ctrc** [comment]
ohh, okey

**Comment by konichiwa-ctrc** [comment]
thanks

**Comment by fellicienne** [comment]
thanks

**Comment by snuckdev** [comment]
> I'm sorry. The problem you got there is not because something is missing in JVMMethodProvider, but it actually happened because you did not add rt.jar as path jar

Lol, so nothing like "Do you have the right of the file"?

**Comment by Janmm14** [comment]
> > I'm sorry. The problem you got there is not because something is missing in JVMMethodProvider, but it actually happened because you did not add rt.jar as path jar
> 
> Lol, so nothing like "Do you have the right of the file"?

He did not share the file. And I did not need the file to give that advise. I just looked at the source code of the deobfuscator and found out what the problem was which lead to that specific stack trace he showed.
