### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Logaut** [java-deobfuscator/deobfuscator#658]
https://prnt.sc/vc3crm

**Comment by Janmm14** [comment]
Those minecraft transformers require mapping files from mod coder pack for example.

**Comment by Logaut** [comment]
yeah but look code
File dir = new File(System.getProperty("user.dir"));
    	File mappings = new File(dir, "mappings");
    	if(!mappings.exists())
    	{
    		System.out.println("[NotchToIntermediaryTransformer] You must put the mappings folder in the same directory as deobfuscator.jar!");
    		return;
    	}
    	
    	File tiny = new File(dir, "mappings.tiny");
    	if(!tiny.exists())
    	{
    		System.out.println("[NotchToIntermediaryTransformer] You must put mappings.tiny in the same folder as deobfuscator.jar!");
    		return;
    	}

**Comment by Janmm14** [comment]
I see - the message does not fit to the folder its looking in

**Comment by ThisTestUser** [comment]
You're supposed to put the mapping files necessary next to deobfuscator.jar.

**Comment by fee1-dead** [comment]
@ThisTestUser it is looking for the file under user.dir, which is the current working directory, even though most of the time the working directory is the same folder that contains the jar, I think it would be best for someone to change the message to match the behavior in a PR.
