### ISSUE TITLE
Problem with ReflectionObfuscation Stringer

### ISSUE THREAD

**Issue by KoopinSmall** [java-deobfuscator/deobfuscator#659]
Also i have a problem with this programm when i try to deobfuscate this it gives me an error with ReflectionObfuscation transformer. 

Error
![Screenshot_8](https://user-images.githubusercontent.com/60297108/97998128-8af94e80-1e0b-11eb-9722-d40646cb5b34.png)

Config
![Screenshot_9](https://user-images.githubusercontent.com/60297108/97998229-a82e1d00-1e0b-11eb-8e06-78257701267a.png)

**Comment by snuckdev** [comment]
lol man ur dumb

**Comment by Janmm14** [comment]
@KoopinSmall You have to provide rt.jar as path in the config as well

```yaml
path:
  - "C:/path/to/rt.jar"
```

**Comment by ItzSomebody** [comment]
@snuckdev: Please abstain making pejorative remarks, thanks.

@KoopinSmall: Feel free to comment if what Janmm14 suggested doesn't work.
