### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by jartester** [java-deobfuscator/deobfuscator#66]
Warning! Output file already exists
Deobfuscation failed. Please open a ticket on GitHub
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:82)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)

**Comment by samczsun** [comment]
This is not an issue with the deobfuscator

**Comment by jartester** [comment]
I need some help then. The program otherwise runs from command line under JAVA VM (in win).

**Comment by Janmm14** [comment]
Its not possible that this java method can't open a jar file while the java runtime can do that, because both use the same method, maybe one library is added wrongly.

**Comment by jartester** [comment]
Janmm14, that's why I think it is a deobfuscator issue. The program consists of many JARs (I recently gathered all of them in one jar and the program runs but this made no difference with the deobfuscator's behaviour) and uses several x64 DLLs...But even without DLLs the program starts its GUI with decrypted strings (of course complaining about missing functionality)...

**Comment by marceldeb** [comment]
i have the same issue, not sure where to look for a solution

**Comment by marceldeb** [comment]
For the people reading this, i found ze solution for ze problem

I made a type in the "path" parameter. This needs to point to the location of rt.jar on your machine. So c/program files/java/bla/lib/rt.jar
