### ISSUE TITLE
Paramorphism not effective

### ISSUE THREAD

**Issue by TheKlimoT** [java-deobfuscator/deobfuscator#662]
[Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/5538675/Plugin.zip) - Decompiling/deobfuscated
[Plugin.jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/5538676/Plugin.jar.zip) - obfuscated

Not effective, all classes broke.

**Comment by TheKlimoT** [comment]
Transformers using:
com.javadeobfuscator.deobfuscator.transformers.special.ParamorphismTransformer
com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer

And turn PARAMORHISM_V2 in src

**Comment by Janmm14** [comment]
I doubt you have the rights to publish that plugin.

Apart from that, the plugin jar file is seems to not be obfuscated with paramorphism, so there is no reason to use that transformer.

**Comment by ItzSomebody** [comment]
So... I did take a quick peek and this does look a lot like a Paramorphism-obfuscated sample (there's some Para-style method indirection); however, I'm with @Janmm14 on this on about being skeptical whether or not you should be posting this in the first place.

Also, would you mind sharing details as to what exactly you mean by "all classes broke"?

**Comment by TheKlimoT** [comment]
I have an assumption that there is something else besides paramorphism, because if you look at the deobfuscated code, it is not readable at all.I want to check this plugin for hacks, because I am wary of holes in my server.

**Comment by TheKlimoT** [comment]
```
public class \x\ implements Listener {
   \a\ \dq\;
   \b\ \du\;

   public _x_/* $FF was: \x\*/() {
      v.\dq\ = \a\.\da\;
      v.\du\ = \b\.\dv\;
   }
```

**Comment by Janmm14** [comment]
Are we actually talking about the same file? I don't see any class named `\x\` or `x` in the jar you provided. All I can see are unobfuscated classes and classes whose names start with `AKYLA_TOP_BLYAT`

**Comment by TheKlimoT** [comment]
This is code from another plugin under paramorphism, the result is the same. Unclear class names.

**Comment by Janmm14** [comment]
Class, method and field name changes are usually irreversible.
