### ISSUE TITLE
Help Deobfuscate pls

### ISSUE THREAD

**Issue by fellicienne** [java-deobfuscator/deobfuscator#664]
tell me,how is it deobf

![image](https://user-images.githubusercontent.com/73531185/99584729-28a56e00-2a07-11eb-822a-ccd6f1e85c8a.png)

**Comment by fee1-dead** [comment]
What's the detect output?

**Comment by fellicienne** [comment]
![image](https://user-images.githubusercontent.com/73531185/99637297-71404400-2a66-11eb-91c2-92fc99169a01.png)

**Comment by fellicienne** [comment]
it gave nothing

**Comment by fee1-dead** [comment]
Sample is likely needed, are you using the latest version?

**Comment by fellicienne** [comment]
i am using the latest version

**Comment by fee1-dead** [comment]
Can you provide a sample?

**Comment by fellicienne** [comment]
ok

**Comment by fee1-dead** [comment]
Do you have legal access to the sample?

**Comment by fellicienne** [comment]
http://www.mediafire.com/file/kt7jwn6l6w6nnou/sample.rar/file

**Comment by fellicienne** [comment]
there is legal access, because the file from the sample is in the public domain

**Comment by fellicienne** [comment]
just want to know how such a cipher can be removed

**Comment by fellicienne** [comment]
have not seen this before

**Comment by 874451** [comment]
missing decryption class and method.

**Comment by fellicienne** [comment]
what?

**Comment by Mysels** [comment]
@fellicienne pls upload Component$Eventkey. class

**Comment by Mysels** [comment]
Try RadonTransformer V1 as well as V2

**Comment by fellicienne** [comment]
okey

**Comment by fee1-dead** [comment]
@fellicienne Did it work?

**Comment by ItzSomebody** [comment]
Since the OP hasn't responded for quite a while now, I'll go ahead and close this.

OP: Feel free to comment if needed.
