### ISSUE TITLE
Zelix Klass Master ReflectionObfuscation Problem

### ISSUE THREAD

**Issue by Get70Ms** [java-deobfuscator/deobfuscator#672]
Can someone help me?

I have done the detection and only zkm was found on that jar.

[Thread-20] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 2715 reflection obfuscation instructions

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: org.objectweb.asm.tree.VarInsnNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:501)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:69)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
try changing order of different zkm obfuscators

**Comment by ThisTestUser** [comment]
Did you use zelix.StringEncryptionTransformer first? You should read the commonerrors (https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md) for Zelix.

**Comment by Get70Ms** [comment]
> Did you use zelix.StringEncryptionTransformer first? You should read the commonerrors (https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md) for Zelix.

Its about a ReflectionTransformer  not the StringEncrypton.

**Comment by Get70Ms** [comment]
> try changing order of different zkm obfuscators

thanks but I already tried.

**Comment by Get70Ms** [comment]
> Then there might be another obfuscator in the file. Is the file you are trying to deobfuscate copyrighted (e.g. not downloadable publicly, or contains Minecraft code)?

its a Minecraft plugin but not a Mojang affiliated code (they didn't made that)

**Comment by ThisTestUser** [comment]
In that case you have to make sure that it is freely downloadable (not a premium plugin). If it is a premium plugin you can decompile the main class with bytecode viewer (Fernflower) and screenshot the code below the line that starts with "static {".

**Comment by Get70Ms** [comment]
that plugin was made like 2 years ago now not anymore in sell (it was like 50$)

> In that case you have to make sure that it is freely downloadable (not a premium plugin). If it is a premium plugin you can decompile the main class with bytecode viewer (Fernflower) and screenshot the code below the line that starts with "static {".

**Comment by ThisTestUser** [comment]
You can decompile the plugin and send a screenshot of the static block then.

**Comment by ThisTestUser** [comment]
Try deobfuscating again with the latest release (https://github.com/java-deobfuscator/deobfuscator/releases/tag/1.5). If nothing got detected that means that this specific obfuscation version is unsupported.

**Comment by fee1-dead** [comment]
> > Did you use zelix.StringEncryptionTransformer first? You should read the commonerrors (https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md) for Zelix.
> 
> Its about a ReflectionTransformer not the StringEncrypton.

You should decrypt the strings first and run other transformers before running reflection transformer. This is because it depends on the string being a literal (`"like this"`) instead of a local variable (`likeThis`) in the bytecode form.

**Comment by ItzSomebody** [comment]
Since there is no jar attached and the OP hasn't responded for quite a while now, I'll go ahead and close.

OP: Feel free to comment if needed.
