### ISSUE TITLE
ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - A config file must be specified

### ISSUE THREAD

**Issue by resh3499** [java-deobfuscator/deobfuscator#676]
hi, i cannot seem to run it. 
`C:\Users\RESHMI\Downloads\deobfuscator-1.5.2\deobfuscator-1.5.2>java -jar deobfuscator.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators

C:\Users\RESHMI\Downloads\deobfuscator-1.5.2\deobfuscator-1.5.2>java -jar deobfuscator.jar
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - A config file must be specified

C:\Users\RESHMI\Downloads\deobfuscator-1.5.2\deobfuscator-1.5.2>`

**Comment by resh3499** [comment]
i tried the GUI. but got this error. 
![Uploading Screenshot (996).png…]()

**Comment by resh3499** [comment]
![Screenshot (995)](https://user-images.githubusercontent.com/73940727/101991952-fed02600-3cea-11eb-89fb-812781ebb3ae.png)
![Screenshot (994)](https://user-images.githubusercontent.com/73940727/101991953-00015300-3ceb-11eb-8f08-39599f0cd71e.png)
![Screenshot (993)](https://user-images.githubusercontent.com/73940727/101991955-01328000-3ceb-11eb-8b69-d9c2a17c3101.png)

**Comment by resh3499** [comment]
![Uploading Screenshot (993).png…]()

**Comment by resh3499** [comment]
![Screenshot (994)](https://user-images.githubusercontent.com/73940727/101992000-45be1b80-3ceb-11eb-8817-7027ff464688.png)

**Comment by resh3499** [comment]
![Screenshot (995)](https://user-images.githubusercontent.com/73940727/101992013-4fe01a00-3ceb-11eb-974b-f6251f90cc23.png)

**Comment by resh3499** [comment]
![Screenshot (996)](https://user-images.githubusercontent.com/73940727/101992026-5c647280-3ceb-11eb-90f9-ca117b7f7026.png)

**Comment by Janmm14** [comment]
Either use java 8 to get the java libraries or use https://github.com/Storyyeller/jrt-extractor to extract java stdlibs from jdk9+

**Comment by ItzSomebody** [comment]
In jdk/jre 9+, I believe you can also just import the jmod archives, though, I've never actually tried doing that myself. If that doesn't work, then what Janmm14 suggested should work.
