### ISSUE TITLE
Obfuscation very difficult

### ISSUE THREAD

**Issue by Nubebuster** [java-deobfuscator/deobfuscator#679]
I am trying to deobfuscate some code but I have no idea which type of obfuscation is left after the transformers I specified below. I'm currently using
- general.peephole.TrapHandlerMerger
 - general.peephole.DeadCodeRemover
 - general.peephole.GotoRearranger
 - general.peephole.RedundantGotoRemover
 - general.peephole.GotoRearranger
 - general.peephole.RedundantGotoRemover
 - smoke.IllegalVariableTransformer
 - smoke.NumberObfuscationTransformer
 - smoke.StringEncryptionTransformer

But stuff like this is not deobfuscated
https://gyazo.com/a2af43c128fea01b508c7f3e527a0b33.png
Detect mode tells me to use com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer but when I use that some methods are no longer decompilable by jd-gui

The current console output is
https://pastebin.com/a2fJE9pj

The code is already deobfuscated by some other person who I dont know but I need to be able to fully recompile it after editing it
[code.zip](https://github.com/java-deobfuscator/deobfuscator/files/5713436/code.zip)

**Comment by Janmm14** [comment]
Solution is to use a proper decompiler and not jd-gui.
Use Bytecodeviewer as gui for a couple good decompilers.

**Comment by Janmm14** [comment]
You might also just want to replace those individual peephole optimizers just with general.peephole.PeepholeOptimizer to run all peehole optimizers.
Might give you better decompilation results.

**Comment by Nubebuster** [comment]
Thanks for the quick reply. ByteCodeViewer is indeed my new best friend!

I've been playing around with the transformers and it has gotten me further. But I am still at 114 errors.

Currently im using these:
 - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
 - normalizer.ClassNormalizer
 - smoke.IllegalVariableTransformer
 - smoke.NumberObfuscationTransformer
 - general.peephole.PeepholeOptimizer
 - special.TryCatchFixer
 - special.FlowObfuscationTransformer
 - special.BisGuardTransformer
 - special.ParamorphismTransformer
 - general.peephole.PeepholeOptimizer`

Procyon is the only decompiler that works well.

I am mostly finding unreachable code which is not removed by transformers and I think it is code that is not meant to be unreachable. Also I am seeing a lot of LabelXXX stuff that I really don't understand. And then there are a lot of type mismatches.

I have been switching and repeating transformers but this is as far as I have gotten. Do you have any suggestions for things I could try?

**Comment by ThisTestUser** [comment]
You don't need to run any transformers at all. The code.zip you provided is already fully deobfuscated, and there isn't anything that java-deobfuscator can remove. If you are getting decompile errors, it is probably caused by bugs in the decompilier. Use Fernflower for decompiling, and try to compare code across different decompiliers to resolve issues.

**Comment by Nubebuster** [comment]
> You don't need to run any transformers at all. The code.zip you provided is already fully deobfuscated, and there isn't anything that java-deobfuscator can remove. If you are getting decompile errors, it is probably caused by bugs in the decompilier. Use Fernflower for decompiling, and try to compare code across different decompiliers to resolve issues.

I have been wasting so much time haha. Yeah I just realized that it's already good. Thanks for the help!
