### ISSUE TITLE
"Transforming complete" but DashoO strings are not decrypted at all...

### ISSUE THREAD

**Issue by jartester** [java-deobfuscator/deobfuscator#68]
Unfortunately the dasho.StringEncryptionTransformer does not decrypt the strings in classes in my case. For example the main class file size itself increases from approx 7KB to over 9KB after transformation but the strings are still encrypted. Is this a bug or am I missing something here? The output jar still runs after this transformation though. Here is a partial output"

Warning! Output file already exists

Reading complete. Loading hierachy

Transforming

Transforming complete. Writing to file

Error: org/apache/commons/dbcp/PoolingDataSource could not be found while writing (....). Using COMPUTE_MAXS

.....

**Comment by samczsun** [comment]
#24 documents the lack of support for higher leveled DashO encryption. While it would be trivial to hardcode a case for the various math operations it's not the best solution that could exist.

I may just do that and put it in a deprecated transformer to stem the bleeding a bit, but in the future I would like some sort of VM which supports arbitrary constant inlining (which I assume is the case here).

In any case, please send a copy of the obfuscated JAR to submit@javadeobfuscator.com with subject "Issue #68" if you are able to, and I will add it to my test cases for DashO

**Comment by jartester** [comment]
Thank you. Already sent.

**Comment by samczsun** [comment]
it's only been a year but at least this is done now :)
