### ISSUE TITLE
Deobfuscation issue

### ISSUE THREAD

**Issue by SatchelMC** [java-deobfuscator/deobfuscator#683]
Hey, I have tried to deobfuscate a .jar file but I don't know what transformers to do. When i try deobfuscate i never get a output.jar

https://www.mediafire.com/file/yhhhlavb9fgtkmh/Skywars.jar/file
That's the file. Can you tell me what transformers I should use?

**Comment by Janmm14** [comment]
why you don't link the original download on spigotmc?
LostSkywars
https://www.spigotmc.org/resources/lostskywars.66219/

**Comment by SatchelMC** [comment]
I am planning on using this as a base then building up with my own code to make it reach what i want it to make

**Comment by ItzSomebody** [comment]
I just took a quick peek and found that the SourceFile attribute is present in each of the classfiles. Something that will help is running the deobfuscator with the `normalizer.SourceFileClassNormalizer` transformer. After this, you'll have no other choice but to deal with the obfuscated method and field names by hand (or you could just reobfuscate the plugin so the names are more legible). Fortunately, using [Recaf](https://github.com/Col-E/Recaf) or [Enigma](https://github.com/FabricMC/Enigma), that shouldn't be too difficult to do.
