### ISSUE TITLE
Error when Deobfuscating

### ISSUE THREAD

**Issue by SatchelMC** [java-deobfuscator/deobfuscator#684]
When i follow all the steps i get my output.jar but whilst the deobfuscator does it's job it gives me this`[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 118 source filenames
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/SecurityException could not be found while writing me/wazup/skywars/WorldEditRollback. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing me/wazup/skywars/Arena. Using COMPUTE_MAXS
Error: java/sql/Connection could not be found while writing me/wazup/skywars/PlayerData. Using COMPUTE_MAXS
Error: java/sql/PreparedStatement could not be found while writing me/wazup/skywars/SkywarsAPI. Using COMPUTE_MAXS
Error: org/bukkit/Location could not be found while writing me/wazup/skywars/Arena$TeamData. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing me/wazup/skywars/Customization. Using COMPUTE_MAXS
Error: java/sql/Connection could not be found while writing me/wazup/skywars/PlayerData$1. Using COMPUTE_MAXS
Error: java/lang/reflect/InvocationTargetException could not be found while writing me/wazup/skywars/Cage. Using COMPUTE_MAXS
Error: java/lang/CharSequence could not be found while writing me/wazup/skywars/Kit. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing me/wazup/skywars/Config. Using COMPUTE_MAXS
Error: org/bukkit/configuration/file/FileConfiguration could not be found while writing me/wazup/skywars/SkywarsListener. Using COMPUTE_MAXS
Error: java/sql/PreparedStatement could not be found while writing me/wazup/skywars/Skywars$4. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing me/wazup/skywars/Skywars. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing me/wazup/skywars/Skywars$14. Using COMPUTE_MAXS
Error: java/util/List could not be found while writing me/wazup/skywars/ItemStackBuilder. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing me/wazup/skywars/Skywars$16. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing me/wazup/skywars/Skywars$18. Using COMPUTE_MAXS
`

**Comment by Janmm14** [comment]
Add
```yaml
path:
 - C:/path/to/rt.jar
```
to your deobfuscator config

**Comment by ItzSomebody** [comment]
Make sure you also add the Spigot API jar to your path.
