### ISSUE TITLE
More Support

### ISSUE THREAD

**Issue by SatchelMC** [java-deobfuscator/deobfuscator#687]
Is there a way to add support for more obfuscators, Such as ProGuard. There are alot of plugins that could be deobfuscated  but can't because we dont have a Proguard deobfuscator. Any way for me or you to add ProGuard support?

**Comment by Janmm14** [comment]
@SatchelMC

Unfortunaly thats not possible:
Everything what ProGuard does (renaming fields, methods, classes, packages) is not reversible. You can get to readable java again by doing manual code analysis and manually renaming the identifiers to be usable again. A tool you can use for that is https://github.com/FabricMC/Enigma

What a java deobfuscator like this one reverses is:

- **string obfuscation**: constant strings are replaced by obfuscators with various method calls with specific parameters which decrypt the string when the program runs and _other obfuscation based on it_ like **usage of reflection, methodhandles and the invokedynamic bytecode instruction** (to which no direct java equivalent bytecode exists) to hide calls to methods and fields. some obfuscators also do similar stuff to number constants.

- the **PeepholeOptimizers** remove _ununsed bytecode_ and _replace complicated bytecode with easier equivalents_. Obfuscators do this as especially older decompilers are easily crashable or easily made to output totally wrong bytecode (example of old decompiler: jd-gui). Still useful with newer decompilers as they are not bug-free as well. Even after applying PeepholeOptimizers nobody should use jd-gui afterwards though.

Recommended decompilers are fernflower, procyon, cfr and krakatau.

**Comment by ItzSomebody** [comment]
Fully agreeing with @Janmm14's response here. Make sure to also read https://github.com/java-deobfuscator/deobfuscator#it-didnt-work if you haven't already. While java-deobfuscator does have normalization transformers for name obfuscation, I have found the ones for field and method normalization to be quite buggy.
