### ISSUE TITLE
My classes are rebuild but Duplicate field Error

### ISSUE THREAD

**Issue by PartikelTTV** [java-deobfuscator/deobfuscator#689]
When i rebuild the Jar i always have the problem that the lines are Dublicated for example:

    public static Bedwars a;
    public Map<String, Arena> a;
    public static Channel a;
    public static Communication a;
    public static Map<Plugin, BedwarsAddon> b;
    public static CommandHandler a;
    public static PlaceholderManager a;
    public static AddonManager a;
    @Deprecated
    public static PluginState a;
    public static WebServiceCommunication a;
    
    static {
        Bedwars.a = null;
        Bedwars.a = null;
        Bedwars.a = null;
        Bedwars.b = new HashMap<Plugin, BedwarsAddon>();
        Bedwars.a = new PlaceholderManager();
    }

as you can see the letters (a and b are always dublicated)

**Comment by Janmm14** [comment]
Use Proguard to rename after deobfuscating. Or use FieldNormalizer transformer at the end.

**Comment by fee1-dead** [comment]
fields are allowed to have the same name but different types.

**Comment by PartikelTTV** [comment]
> Use Proguard to rename after deobfuscating. Or use FieldNormalizer transformer at the end.
> 
> Java bytecode identifies fields by name and type, thats why this is valid bytecode (but not legal source code).

how i rename it in Proguard?
