### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by sethrem** [java-deobfuscator/deobfuscator#69]
Tried decompiling a jar using Zelix and this is what happened.

Warning! Output file already exists
Deobfuscation failed. Please open a ticket on GitHub
java.lang.IllegalArgumentException
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init

> (ClassReader.java:177)
>         at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init
> (ClassReader.java:154)
>         at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init
> (ClassReader.java:431)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
> a:87)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
> in.java:102)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
> ain.java:26)
> Press any key to continue . . .

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
