### ISSUE TITLE
SuperBlaubeere transformer isnt working anymore

### ISSUE THREAD

**Issue by fikawka** [java-deobfuscator/deobfuscator#694]
This transformer is working poorly. When, you choose almost all transformers on this obfuscator, the deobfuscator cant do almost anything. it maybe beats the number obfuscation and something more, but the code absolutely isnt readable. File wents from 15kb to 110kb, using obfuscator, and deobfuscator manages to maybe remove 10kb.
Dont tell me that code like this: https://pastebin.com/y84DKPp6
This is after, superblaubere and illegal signature.

**Comment by ThisTestUser** [comment]
That's probably because you didn't remove the local variables first, which is explained here: https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Superblaubeere.md

**Comment by fikawka** [comment]
Thank you that helped
