### ISSUE TITLE
String decryption failed ZKM 15.0.2

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#698]
I get java.lang.NullPointerException while decrypting strings.
Used zelix.FlowObfuscationTransformer and zelix.string.SimpleStringEncryptionTransformer, few strings are decrypted, but not all...

JAR: https://www.upload.ee/files/12854803/client.jar.html

P.s. zelix.string.StringEncryptionTransformer and zelix.string.EnhancedStringEncryptionTransformer not works.

**Comment by Janmm14** [comment]
You may not upload copyrighted resources. This inlcudes mods which include minecraft source code.
See https://github.com/java-deobfuscator/deobfuscator/issues/653
