### ISSUE TITLE
GotoUnconditionalJumpRemover can run into endless loops

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#70]
My own obfuscator, which uses some dvb's pretty straight forward and also sometimes combines some of the dvb's, accidentally let your GotoUnconditionalJumpRemover run into infinite loops.

Obfuscated bytecode:
https://gist.github.com/Janmm14/33584ec8fa0da47835b690cbb0014730

I don't know whether the code does execute successfully however, its part of minecraft 1.8.9 which I use for testing my obfuscator. Its the `aqe$1` class and I don't know what it actually does, but it actually seems important because it handles a switch in `aqe` on `cq` which is a direction enum.

**Edit:**
Yes, the method is added by my obfuscator to the class, but it gets executed when the class is loaded (clinit)

**Edit 2:**
Whether the method works or not is not invalidating this issue because people could still add such invalid classes in case anyone tries this deobfuscator on his obfuscated work.
GotoRearranger, ContinousGotoRemover, UnconditionalSwitchRemover, NopRemover ran before.
None of them should've changed any bytecode in that method (I added output for that).

**Edit 3:**
Due to me having wrongly modified your unconditional jump remover to abort on too many loops, only one incident was reported and the issue, that the loop would run more than 1000 times is actually happening on many more methods.

**Comment by samczsun** [comment]
GotoUnconditionalJumpRemover just got removed. Hopefully the new iteration isn't vulnerable but in all honesty I don't really have the patience to check. If you find any new vulnerabilities I will try my best to actually respond to them though
