### ISSUE TITLE
Cannot detect what obfuscicator is used

### ISSUE THREAD

**Issue by veso266** [java-deobfuscator/deobfuscator#701]
I have a very old Java applet, that I would like to recreate its leaderboard server (sincer original is long gone): https://filebin.net/7r6xd5qwb2xymupc/aqua_dig_240x320-122597.jar?t=xcqlu864

after I used jd-gui to open the jar file and inspect it I found

the (supposebly http request) class: com.vlm.redstar.client.core.csp but its realy wierd its supposed to be a http client that makes requests, it makes requests to: http://mpgserver2.vivalamobile.com:8000/redstarcsp/ServletMPG?t=csp&c=Test&p=LG&d=01&r=n

but thats the onlything I was able to figure out, so I think this is obfuscacated somehow, but don't know how, the class is supposed to establish http connection and read json or xml, but this thing is fiddling with bytes on http server, so something is realy wrong

I tried to detect obfuscator like this
```yaml
input: aqua_dig_240x320-122597.jar
detect: true
```
```
java -jar deobfuscator.jar --config detect.yml
```

but it didn't detect anything
![slika](https://user-images.githubusercontent.com/6347325/107572221-43454880-6bec-11eb-9ee3-708da3e6dabc.png)

so I realy don't know what kind of obfuscator could this old java MIDLet use

If you can take a look, that would be great, 
Thanks for Anwsering and Best Regards

**Comment by Janmm14** [comment]
The jar you provided contains no hard obfuscation.
Only classes, methods and fields are renamed. This in not reversible.
I suggest that you use a tool like Enigma ( https://www.cuchazinteractive.com/enigma/ ) to rename classes, methods and fields.

In general, please ditch jd-gui. Use a better decompiler. Here are some listed, also with some good guis: https://github.com/java-deobfuscator/deobfuscator/wiki/Deobfuscation

**Comment by veso266** [comment]
Nice, thanks, I didn't know there is anything better then jd-gui as this one mostly decompiled my jar files fine :smile:

although Enigma crashes on my jar file for some reason, I guess I will have to use some brain-power to reverse this file :smile:
