### ISSUE TITLE
How do I add a custom transformer? (Sponge Mixins)

### ISSUE THREAD

**Issue by Sundev79** [java-deobfuscator/deobfuscator#703]
How do I add a custom transformer? (Sponge Mixins)
Hello I'd like to decompile a minecraft mod I created, but the problem is that I lost my source code, I used mixin, but the problem is that I can't decompile it, do you have a track on it ?

**Comment by Janmm14** [comment]
Mixins are not obfuscation.
Just go ahead and decompile the jar.
Here are some good decompilers and decompiler GUIs listed: https://github.com/java-deobfuscator/deobfuscator/wiki/Deobfuscation

You might also want to use Enigma ( https://www.cuchazinteractive.com/enigma/ ) to rename things if needed.

**Comment by ItzSomebody** [comment]
Like @Janmm14 said, mixins are not obfuscation (at least not to my limited knowledge of them). To answer your question about creating a transformer, check [CUSTOMTRANSFORMER.md](https://github.com/java-deobfuscator/deobfuscator/blob/7c7c94f2e7cb8a71b0dbb728190b786a3704d28d/CUSTOMTRANSFORMER.md). It's a little bit outdated, but still applies to the current code base.

**Comment by Sundev79** [comment]
So why are there package classes called obfuscation in the Mixin code?

**Comment by Janmm14** [comment]
@Sundev79 Probably because it deals with the class name, method name and field name obfuscation in minecraft and the partial reobfuscation.

Mixin itself does not add any special obfuscation.
