### ISSUE TITLE
Can´t deobfuscate ALLATORIxDEMO.

### ISSUE THREAD

**Issue by oxygen-team** [java-deobfuscator/deobfuscator#706]
I have tried to deobfuscate this file more than 10 times, and every time it looks the same as the not deobfuscated file. Pls help me or maybe you can deobfuscate it. Thank you very much. 👍

**Comment by Janmm14** [comment]
@ItzSomebody Please remove the uploaded file. He is not allowed to share this, as the file is not obtainable for free.

**Comment by ItzSomebody** [comment]
Removed.

@oxygen-team: I did take a quick look at the file and all I saw was Allatori flow/string encryption. Consider using the flow transformer then the string encrypton transformer.
