### ISSUE TITLE
https://github.com/java-deobfuscator/deobfuscator/issues/181#issue-280790250

### ISSUE THREAD

**Issue by Ahmerdsuleman** [java-deobfuscator/deobfuscator#707]
![Uploading IMG_20210219_162857.jpg…]()

Deobfuscation failed  please open a ticket on GitHub and provide the following error
Java.lang.OutOfMemory:java heap space

**Comment by Janmm14** [comment]
picture not correctly uploaded. try giving it more ram in java startup parameter

**Comment by Ahmerdsuleman** [comment]
> picture not correctly uploaded. try giving it more ram in java startup parameter

Ohk thanks let me try and upload picture so you can see the logs
