### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by alexhackers** [java-deobfuscator/deobfuscator#71]
C:\Users\AlexHackers\Desktop\Allatori\lixao>java -jar deobfuscator.jar -input "B
lastHostingAntiBot.jar" -output "BlastHostingAntiBot_Deob.jar" -transformer alla
tori.StringEncryptionTransformer -path "C:\Program Files (x86)\Java\jre1.8.0_91\
lib\rt.jar" -path "paper.jar"
Deobfuscation failed. Please open a ticket on GitHub
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init
>(ClassReader.java:170)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init
>(ClassReader.java:154)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init
>(ClassReader.java:431)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
