### ISSUE TITLE
Deobfuscator deletes incorrect class entry

### ISSUE THREAD

**Issue by MoonshineBucket** [java-deobfuscator/deobfuscator#712]
When trying to deobfuscate the program, a class disappears that was not created using obfuscation, but obviously existed in the program even before the obfuscation of its code, I was able to determine that this is stringer and allatori, for the very decryption I used the following transformers:
- stringer.StringEncryptionTransformer
- stringer.HideAccessObfuscationTransformer
I also tried to use allatori transformers and inserted them in different positions, before and after the stringer, the result was exactly the same.
- allatori.FlowObfuscationTransformer
- allatori.LightFlowObfuscationTransformer
Below I will provide the program with which I actually had problems.

[obfuscated.zip](https://github.com/java-deobfuscator/deobfuscator/files/6055142/obfuscated.zip)

**Comment by ThisTestUser** [comment]
You should be now able to configure the stringer.StringEncryptionTransformer to not remove all decryption classes, which should fix your issue.
