### ISSUE TITLE
Failure to apply Minecraft mappings

### ISSUE THREAD

**Issue by OptimusZeGaming** [java-deobfuscator/deobfuscator#713]
Hello,

I discovered this tool very recently, I made several attempts but I have a small problem I can disobfuscate the mods without any problem but the problem is that the procedures and functions are always locked.

Can you help me?

To better understand, I'll put if attached an example of an item.
`soda = (new ItemSoda(0, 0.0F, false)).func_77655_b("soda").func_111206_d("thirst:soda").func_77637_a(CreativeTabs.field_78038_k);`

Thanks in advance for your help.

**Comment by ItzSomebody** [comment]
What do you mean by "the functions are always locked"?  Regarding the snippet of code you posted, I don't see anything obfuscated -- in fact, whatever was used to generate those method/field names is probably far more legible and easy to work with than what the obfuscated names were before.

**Comment by OptimusZeGaming** [comment]
What I mean is, I'm not supposed to have func_111206_d and field_78038_k (including for others for example for func_77637_a it's supposed to be setCreativeTab for example.

**Comment by DJCoolDev** [comment]
This is caused by minecraft obfuscation. This deobfusctor doesn't support remapping minecraft projects. 
Try using https://github.com/bspkrs/MCPMappingViewer to view the mappings and remapp.

**Comment by Janmm14** [comment]
> 
> 
> This is caused by minecraft obfuscation. This deobfusctor doesn't support remapping minecraft projects.
> Try using https://github.com/bspkrs/MCPMappingViewer to view the mappings and remapp.

Actually it does: https://github.com/java-deobfuscator/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/minecraft

However I can't tell you how to use those, since I'm not into client modding.

**Comment by ItzSomebody** [comment]
@OptimusZeGaming Is this still a persisting issue?
