### ISSUE TITLE
Correct way to deobfuscate the following examples

### ISSUE THREAD

**Issue by brownbananas95** [java-deobfuscator/deobfuscator#714]
I have a generic jar file that is not obfuscated very much, but enough to not be decompiled directly. 

Most of the code deobfuscates successfully with CFR, but I am trying to get it as clean as possible. 
 
What are the transformers (and which order) I should run for a generic .jar to resolve Enums, recover source filenames and resolve inner classes?
 
 ---
 
 For the following example:
 ```java
 @Override
    public void mousePressed(MouseEvent mouseEvent) {
        this.this$0.nameInput.setEditable(false);
        this.this$0.nameInput.setText(this.val$autoScript.getName());
        this.this$0.updateNameActions(false);
        this.this$0.requestFocusInWindow();
    }
```
 
Is there any way to get rid of, or resolve inner classes such as: `this.this$0...`? [Reference](https://stackoverflow.com/questions/27145010/whats-the-meaning-of-this-this0)

I am also getting the following Enum(?) problems quite frequently:
```java
            switch (playerName.hashCode()) {
                case -115237430: {  <--------------------- How to resolve these enums correctly?
                    if (!playerName.equals("BREAKIFTRUE")) break;
                    index = 0;
                    break;
                }
```

---

Currently I am using the following configuration:
```
input: input.jar
output: output.jar
path:
  - rt.jar
  - client-1.6.33-SNAPSHOT-shaded.jar
libraries:
  - rt.jar
  - client-1.6.33-SNAPSHOT-shaded.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.CleanupTransformer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.ClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.EnumNormalizer
```

**Comment by ItzSomebody** [comment]
There is no obfuscation present in either of the code snippets you posted -- that's simply how Java is compiled to its classfile format.  The inner class stuff should be able to be handled by pretty much any decompiler that comes to mind (including CFR, there should be an option for it).  If that doesn't work for some reason, then you could try adding the class to the `InnerClasses` attribute manually by hand but at that point and then decompiling but at that point, I think it would be more worth your time to just work with the decompiled result as is.  What you posted is pretty legible and definitely easy to work with (even if it is slightly annoying).  The deobfuscator doesn't support resolving inner classes so this project isn't going to be much help.

The thing with the switch is how Java compiles a string case to bytecode -- there's nothing to deobfuscate.  I believe CFR has an option to sugar switch cases (as does procyon, certain fernflower forks, etc.).

**Comment by Janmm14** [comment]
the if inside the switch case shows you the original string switch value
