### ISSUE TITLE
help me !!!!

### ISSUE THREAD

**Issue by oxygen-team** [java-deobfuscator/deobfuscator#718]
I keep getting this errors:

```
[Thread-16] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-16] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-16] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-16] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-16] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/String could not be found while writing k/r/k/m/i. Using COMPUTE_MAXS
Error: net/minecraft/inventory/ContainerChest could not be found while writing k/r/k/A. Using COMPUTE_MAXS
Error: net/minecraft/inventory/ContainerChest could not be found while writing k/r/k/m/x. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing k/r/k/m/G. Using COMPUTE_MAXS
Error: java/lang/InterruptedException could not be found while writing k/r/k/G. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing k/r/k/m/e. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing k/r/k/k/f. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing k/k/r/J. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing k/r/k/k/A. Using COMPUTE_MAXS
Error: net/minecraft/client/gui/GuiScreen could not be found while writing k/k/k/r/M. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing k/k/k/e/M. Using COMPUTE_MAXS
```
I want to deobfuscate a labymod addon with allatorixdemo.
Does anyone know what path I should use, or what I am doing wrong. 

This is my Input:
https://smartbot-studios.de/SmartTradeBot_Beta.php

Maybe you can deobfuscate it for me, if you know, how it works. Tank you verry much!!

**Comment by fee1-dead** [comment]
add rt.jar and minecraft jar to path. I can't open the input jar.

**Comment by Janmm14** [comment]
@ItzSomebody Please remove the uploaded zip. Opening it with notepad shows that he did not learn from #706 and he still distributes s(ch)mart t(e)ra(i)de bo(owio)t. (lets not let google find this)

**Comment by oxygen-team** [comment]
Sorry I have removed it.

**Comment by oxygen-team** [comment]
But this is not private.

**Comment by oxygen-team** [comment]
@fee1-dead because it is a labymod addon

**Comment by oxygen-team** [comment]
@fee1-dead where can i download (find) minecraft.jar or rt.jar

**Comment by fee1-dead** [comment]
rt.jar can be found in a java installation. At lib/rt.jar. If you are using java9+, use https://github.com/Storyyeller/jrt-extractor

**Comment by oxygen-team** [comment]
@fee1-dead and where can i find minecraft jar ?

**Comment by ItzSomebody** [comment]
> @fee1-dead and where can i find minecraft jar ?

That's something you should be able to find yourself.  It's in the minecraft directory under the user directory.
