### ISSUE TITLE
How can I see, when the deobfuscator is finished?

### ISSUE THREAD

**Issue by oxygen-team** [java-deobfuscator/deobfuscator#720]
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.FlowObfuscationTransformer
[Allatori] [FlowObfuscationTransformer] Starting
[Allatori] [FlowObfuscationTransformer] Fixed 1837 instructions
[Allatori] [FlowObfuscationTransformer] Done
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing

**Comment by oxygen-team** [comment]
It has been in reading for 20min, but there is nothing happening.

**Comment by Janmm14** [comment]
the "writing" output is the last one the deobfuscator does. after that, look at the output jar file. although not much will have changed if you are using a good, modern decompiler, as flow obfuscation is often already handled by good, modern decompilers.
