### ISSUE TITLE
My deobfuscated file looks pretty much the same after deobfuscating.

### ISSUE THREAD

**Issue by oxygen-team** [java-deobfuscator/deobfuscator#721]
I used this transformers:
![image](https://user-images.githubusercontent.com/65194572/111914743-9922d100-8a73-11eb-9b1c-409666cae916.png)
Console:
![image](https://user-images.githubusercontent.com/65194572/111914773-bfe10780-8a73-11eb-99c7-5f3545de1390.png)

Before:
![image](https://user-images.githubusercontent.com/65194572/111914962-704f0b80-8a74-11eb-8b0b-61c5272b01e5.png)

After:
![image](https://user-images.githubusercontent.com/65194572/111915004-92488e00-8a74-11eb-8199-ac75fb03f0bf.png)

PLS HELP

**Comment by Janmm14** [comment]
I have a feeling that you used fernflower for decompilation. Either add general.peephole.PeepholeOptimizer at the end or try another decompiler (krakatau, cfr or procyon aka luyten).

I suggest that you try it also without allatori.string.StringEncryptionTransformer (maybe add it multiple times) or that you remove allatori.FlowObfuscationTransformer

**Comment by ItzSomebody** [comment]
For reasons beyond me, it looks like whoever obfuscated that use Allatori string encryption multiple times.  What Janmm14 suggested should work.
