### ISSUE TITLE
Deobfuscator exit without ouput

### ISSUE THREAD

**Issue by damien-devpy** [java-deobfuscator/deobfuscator#729]
Hello there,

I'm trying to deobfuscate some java code, unfortunately deobfuscator exit without giving (detecting ?) any obfuscators : 

```python
damien@PC:~/dev/some_folder$ sudo java -jar deobfuscator.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
damien@PC:~/dev/some_folder$
```

However, the code really seems obfuscate, you can take a look :

```java
class c.c.a.h extends android.graphics.drawable.Drawable {
  static c.c.a.h$a r;
  static {};
  static float c(float, float, boolean);
  static float d(float, float, boolean);
  public void draw(android.graphics.Canvas);
  android.content.res.ColorStateList f();
  float g();
  public int getOpacity();
  public boolean getPadding(android.graphics.Rect);
  void h(android.graphics.Rect);
  float i();
  public boolean isStateful();
  float j();
  float k();
  float l();
  void m(boolean);
  void o(android.content.res.ColorStateList);
  protected void onBoundsChange(android.graphics.Rect);
  protected boolean onStateChange(int[]);
  void p(float);
  void q(float);
  void r(float);
  public void setAlpha(int);
  public void setColorFilter(android.graphics.ColorFilter);
}
```

Moreover, i run find, javap and grep overs all class files looking for some keywords that i know they has to be present (such as api endpoints or hmac reference), and didn't found anything. (Telling me the code is indeed obfuscate)

Thank you for your help, best regards :)

**Comment by ItzSomebody** [comment]
In the case of Android apps, you might have more luck with [simplify](https://github.com/CalebFenton/simplify) since that is made specifically for Android apps.  [JEB](https://www.pnfsoftware.com/) is also pretty helpful.

> Moreover, i run find, javap and grep overs all class files looking for some keywords that i know they has to be present (such as api endpoints or hmac reference), and didn't found anything. (Telling me the code is indeed obfuscate)

If you ran into something like `javap -c <blah> | grep -i <ref>` and nothing showed up, it is very well possible that obfuscation is hindering you; however, the output you pasted only shows that some of the class/method/field names were changed -- something that doesn't actually hide most of the API references.  We would need a slightly more conclusive way (as in, more information about the bytecode of whatever you are working with) to be able to tell what other obfuscation happens to be present.

**Comment by damien-devpy** [comment]
Thanks for the quick answer, i'm currently running simplify!

> If you ran into something like javap -c <blah> | grep -i <ref> and nothing showed up

That's pretty close that something that i ran, you can find below another snippet of code that might be more explicit regarding the obfuscation:

```java
final class com.google.android.gms.measurement.internal.fa extends javax.net.ssl.SSLSocket {
  com.google.android.gms.measurement.internal.fa(com.google.android.gms.measurement.internal.ga, javax.net.ssl.SSLSocket);
  public final void addHandshakeCompletedListener(javax.net.ssl.HandshakeCompletedListener);
  public final void bind(java.net.SocketAddress) throws java.io.IOException;
  public final void close() throws java.io.IOException;
  public final void connect(java.net.SocketAddress) throws java.io.IOException;
  public final void connect(java.net.SocketAddress, int) throws java.io.IOException;
  public final boolean equals(java.lang.Object);
  public final java.nio.channels.SocketChannel getChannel();
  public final boolean getEnableSessionCreation();
  public final java.lang.String[] getEnabledCipherSuites();
  public final java.lang.String[] getEnabledProtocols();
  public final java.net.InetAddress getInetAddress();

  [...]

public interface com.google.android.gms.measurement.internal.o3 extends android.os.IInterface {
  public abstract byte[] C0(com.google.android.gms.measurement.internal.s, java.lang.String) throws android.os.RemoteException;
  public abstract void D0(com.google.android.gms.measurement.internal.s, com.google.android.gms.measurement.internal.ja) throws android.os.RemoteException;
  public abstract java.util.List<com.google.android.gms.measurement.internal.z9> H(java.lang.String, java.lang.String, java.lang.String, boolean) throws android.os.RemoteException;
  public abstract void N0(android.os.Bundle, com.google.android.gms.measurement.internal.ja) throws android.os.RemoteException;
  public abstract java.lang.String Q(com.google.android.gms.measurement.internal.ja) throws android.os.RemoteException;
  public abstract void Q0(com.google.android.gms.measurement.internal.z9, com.google.android.gms.measurement.internal.ja) throws android.os.RemoteException;
  public abstract void X(long, java.lang.String, java.lang.String, java.lang.String) throws android.os.RemoteException;
  public abstract void Z0(com.google.android.gms.measurement.internal.s, java.lang.String, java.lang.String) throws android.os.RemoteException
```

I've exposed api endpoints of an android app and I'd like to make a simple desktop app using endpoints and my credentials. I mostly need access to the java code to understand how hmac and others random headers are compute.

**Comment by Janmm14** [comment]
It looks like you are in need of a java decompiler and not a java deobfuscator.

Try [Helios Decompiler](https://ci.samczsun.com/job/helios-decompiler/job/Standalone%20App/) or [BytecodeViewer](https://github.com/Konloch/bytecode-viewer), both are GUIs for various java decompilers.
They both support: Krakatau (requires pypy installation), Fernflower, CFR and Procyon (aka Luyten)

**Comment by damien-devpy** [comment]
Thanks @Janmm14, that was it. Now the code look like obfuscated (class and method renamed) but i have clear readable string and error message. I think there's nothing i can do more. Thanks @ItzSomebody and @Janmm14

**Comment by Janmm14** [comment]
> Thanks @Janmm14, that was it. Now the code look like obfuscated (class and method renamed) but i have clear readable string and error message. I think there's nothing i can do more. Thanks @ItzSomebody and @Janmm14

Class and method renaming is usually not reversible.
