### ISSUE TITLE
What type of obfuscate is this?

### ISSUE THREAD

**Issue by zombiepuppet** [java-deobfuscator/deobfuscator#733]
I see a variable name like ``OO000O000000OOOO0OO00O0O0000`` or ``0OO000O0O00O0OOO00OOOOOOO000``, is there any transformer to decrypt this type of string?

The jar that I'm obtained has classname like above, and it has been transformed into character such as ``aa`` ``bv``, but some of the variables inside that class still remain ``OO000O000000OOOO0OO00O0O0000``

Transformers that I use:

```
- allatori.FlowObfuscationTransformer
- allatori.LightFlowObfuscationTransformer
- allatori.StringEncryptionTransformer
- allatori.string.StringEncryptionTransformer
- normalizer.SourceFileClassNormalizer
```

Here is [the image](https://ibb.co/Cn3VGKC) of what inside the jar originally

Thank you.

**Comment by Janmm14** [comment]
Try general.removers.LocalVariableRemover

It removes the names of local variables.
Would've been better if you showed what remained o0oO-named afterwards.

**Comment by zombiepuppet** [comment]
> 
> 
> Try to add `general.removers.LocalVariableRemover`, it removes the names of local variables.
> Would've been better if you showed what remained o0oO-named afterward.

Hi, thanks for the reply and sorry for the late reply.

I added ``general.removers.LocalVariableRemover`` to the transformer list and the variable still remained ``o0o0o...``.

In fact, there are lots of variables that have a name like ``ALLATORIxDEMO``, is this should be ignored because I added more string transformation, and it still the same.

Here is [the image](https://i.imgur.com/MkV5Wu4.png) of what remained ```o0o0o...``, I can send the jar privately if you want to take a look, is it allowed to send it here though?

Appreciated it.

**Comment by Janmm14** [comment]
Those are java identifiers. They're not in-program strings and cannot be reverted to their original.

Use proguard on the result jar or normalizer.FieldNormalizer and normalizer.MethodNormalizer to rename fields and methods to easier readable and distinguishable names.
