### ISSUE TITLE
GenericFutureListener error

### ISSUE THREAD

**Issue by alaaemad15** [java-deobfuscator/deobfuscator#74]
This is the error I'm getting: https://gyazo.com/61a60f22929173d81faf1c535fcff286
The command I'm using is: java -jar -input "input.jar" -output "output.jar" -path "path/to/my/rt" -transformer "allatori.StringEncryptionTransformer"

**Comment by Janmm14** [comment]
From the log:
> Have you added the necessary files to your `-path` argument?

Tip: You can specify multiple `-path` arguments.

If it complains about a missing netty class, you should add it to your `-path` arguments.

**Comment by alaaemad15** [comment]
Where is it located?

**Comment by alaaemad15** [comment]
I have solved this by collecting the apis needed by the jar and putting them all in a folder, then adding it to the path.
