### ISSUE TITLE
NPE DictionaryMethodProvider.java

### ISSUE THREAD

**Issue by gsquaredxc** [java-deobfuscator/deobfuscator#749]
It seems as though DictionaryMethodProvider.java calls .orElseGet(null) in two locations, which may be a misunderstanding of how https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#orElseGet-java.util.function.Supplier- works.

I believe .orElseGet(()->null) may work as intended.

**Comment by ItzSomebody** [comment]
I'm not sure how I have never noticed this before, but I do agree that this is probably incorrect usage.  `.orElse(null)` or `.orElseGet(() -> null)` is probably what was intended here.
