### ISSUE TITLE
Stringer uses new protection

### ISSUE THREAD

**Issue by GraxCode** [java-deobfuscator/deobfuscator#75]
Everything is working fine on stringer, but string deobfuscation not.
`      StackTraceElement[] var1 = Thread.currentThread().getStackTrace();
      int var26 = (SharedSecrets.getJavaLangAccess().getConstantPool(Class.forName(var1[2].getClassName())).getSize() + var1[2].getClassName() + var1[2].getMethodName() + SharedSecrets.getJavaLangAccess().getConstantPool(Class.forName(var1[3].getClassName())).getSize()).hashCode();
      int[] var2 = (int[])((int[])R[6]);
      int var3 = var26 ^ var2[0];
      int var4 = var26 ^ var2[1];
      int var5 = var26 ^ var2[2];
      int var28 = var26 ^ var2[3];
`

stringer checks for the previous method, which is obviously not working with "invoke0".

**Comment by Eyremba** [comment]
Yes, Stringer has changed some things in their String-Obfuscation. Like Zelix, they changed some things too.

**Comment by samczsun** [comment]
Doesn't look any different than what they were doing before.

**Comment by Janmm14** [comment]
@GraxCode The deobfuscation does not execute that method directly, but goes step-by-step through each opcode and emulates execution, giving the wrong and spoofed stacktrace when asked for. Its basically similar to Allatori's string obfuscation, it also checks the previous method as far as I know.

**Comment by PASAf** [comment]
Is there way to fix it?

**Comment by ItzSomebody** [comment]
yeah, make your own

**Comment by FFY00** [comment]
Try again with the latest version.

**Comment by PASAf** [comment]
@FFY00 Same result for me.
```
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 1873 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Decrypted 627 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 0 decryption classes
[Stringer] [StringEncryptionTransformer] Done
```

**Comment by ThisTestUser** [comment]
It looks like string encryption with this new protection still gives invalid strings. The old version of Stringer that doesn't have the getConstantPool() (it uses the java thread to get the stacktrace) is decrypted, however.

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
