### ISSUE TITLE
Dasho string deobfuscator does not deobfuscate all strings. (about 35% of them are left)

### ISSUE THREAD

**Issue by yushiroamada** [java-deobfuscator/deobfuscator#754]
Steps I used to deobfuscate this program:

First
  - com.javadeobfuscator.deobfuscator.transformers.dasho.FlowObfuscationTransformer
Second
  - com.javadeobfuscator.deobfuscator.transformers.dasho.StringEncryptionTransformer

What the remaining obfuscated strings look like.

         String var2 = 1.insert("4-&", 19 + 126 + 19 + 126) + var0;
         SecretKeySpec var3 = new SecretKeySpec(var2.getBytes(), 1.insert("\u001f\u0012\u0003", 9 + 53 + 9 + 53));
         Cipher var4 = Cipher.getInstance(1.insert("ID\t", 651 / 103));
         return 1.insert("`~q}og", 5 + 13 + 13 + 5);

Is there anything I can do to fix this? I would be happy to do a pull request and contribute if some information can be provided on this. Thank you.
![Screen Shot 2021-05-09 at 11 09 52 PM](https://user-images.githubusercontent.com/60025195/117601191-ae36ea80-b11b-11eb-863e-bb5be0573eea.png)

**Comment by ThisTestUser** [comment]
Can you try runnning dasho.FakeExceptionTransformer (along with flowobf) before running the stringencryptiontransformer?

**Comment by yushiroamada** [comment]
> Can you try runnning dasho.FakeExceptionTransformer (along with flowobf) before running the stringencryptiontransformer?

Works. Thanks! Sorry for poor enligh.
