### ISSUE TITLE
Heavily Processed jna rat

### ISSUE THREAD

**Issue by BackupAccou** [java-deobfuscator/deobfuscator#761]
[pack.zip](https://github.com/java-deobfuscator/deobfuscator/files/6510276/pack.zip)

**Comment by BackupAccou** [comment]
No Copyright

**Comment by Janmm14** [comment]
and?

**Comment by BackupAccou** [comment]
need some helps to decrypt it

**Comment by Janmm14** [comment]
We prefer more effort from issue creators.
What does the detect feature say? What have you tried?

This is no deobfuscation service, but an issue / feature request tracker.

**Comment by BackupAccou** [comment]
my fault. I will try to solve it myself. Thanks @Janmm14
