### ISSUE TITLE
Decompiling with Allatori

### ISSUE THREAD

**Issue by MrWouterNL** [java-deobfuscator/deobfuscator#77]
Hi! Well, i tried decompiling the following .jar: https://www.spigotmc.org/resources/minetopia-custom-build.29794/

My error is: https://hastebin.com/ciqigoracu.vbs

Could you help! Thanks in advance :)

**Comment by Janmm14** [comment]
Try adding `Xss128M` before `-jar` in your command. This is a known issue.
