### ISSUE TITLE
Deobfuscation

### ISSUE THREAD

**Issue by GoldWolfs** [java-deobfuscator/deobfuscator#775]
Hello, can you please tell me if you can de-buffer this mod?
[Click](https://drive.google.com/file/d/1f6EBngDbm9Pcdj5xoNldlWb43JFJ8PL7/view)

**Comment by Janmm14** [comment]
The issues of this project are **not** _deobfuscation-as-a-service_.

You clearly didn't even try to use java-deobfuscator.

If you encounter issues during deobfuscation, we are happy to help.

**Comment by Janmm14** [comment]
Tutorial
https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started
