### ISSUE TITLE
Deobfuscation problem, macOS.

### ISSUE THREAD

**Issue by Jakubk15** [java-deobfuscator/deobfuscator#778]
Hello,
I tried to deobfuscate a file, with GUI, but it failed to find path, so I tried to do it via command line.
Config (detect.yml):
```
input: target.jar
detect: true
```
My JAR file to deobfuscate is in the same folder as deobfuscator.jar and deobfuscator-gui.jar, and configuration file (detect.yml).

I didn't specify transformers, because I'm not familiar with reverse engineering.

So, when I launched `deobfuscator-gui.jar`, I got an error:

https://imgur.com/a/bg5qAhX

I typed in path: `~/Desktop/deobf/deobfuscator.jar`, as mentioned in displayed error.

When I did it in deobfuscator.jar, in command line (Terminal in macOS):

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators

```

But the file is still obfuscated.

In README.md there is a mention about `config.yml`, but I need to specify transformers, which I don't know.

**Comment by Janmm14** [comment]
When detect is checked, there will never be an output file.
This looks like it did not find any obfuscation automatically. This means that either only renaming of java identifiers happenend (not reversible) or that an obfuscation was used which this project doesn't have a detector or transformer for yet.

**Comment by Janmm14** [comment]
Additionally the deobfuscator-gui is a replacement for config.yml

**Comment by Jakubk15** [comment]
I bet the obfuscator used is Caemium. Where I can found transformers list? Also I know it is possible to deobfuscate it, but I don't know with default transformers. My friend deobfuscated it with custom one.

**Comment by Janmm14** [comment]
There is no transformer for Caesium in this project.
I made one in private but I am hesitant to release it as I don't want to play cat&mouse that fast.

**Comment by Jakubk15** [comment]
Ok. I understand. What about GUI version of Java Deobfuscator? What can I do to fix the invalid path error? All Java files have full disk access in System Preferences. Also if I would like to make a custom transformer, do I need to know assembler programming language, or how?

**Comment by Janmm14** [comment]
You'd need to know java bytecode language. It is far away from (x86) assembly.
I've wrote some tips in #738
