### ISSUE TITLE
Is it possbile to rename the Classes if i have the original Minecraft unobfusctatet Classes.

### ISSUE THREAD

**Issue by LavaMensch** [java-deobfuscator/deobfuscator#78]
Hi i Decrypt a Hack Client and now my Question...

quiet now i am using this
.withTransformer(Normalizer.CLASS_NORMALIZER)
	            .withTransformer(Normalizer.FIELD_NORMALIZER)
	            .withTransformer(Normalizer.METHOD_NORMALIZER)
	            .withTransformer(Normalizer.PACKAGE_NORMALIZER)
, but this code writes the Classes to Class 1 Class 2 ect...

I have the original unobfuscted Minecraft 1.10 with this Minecraft version the Hack Client is built. Is it possible to get the Classes which are named Class1 ect to the name which they are original in the game named? Like Class1 i find out is orignial the EntityPlayerSP Class so can i unname them Automaticly?

I hope you understand my question, which is written in bad english sry

**Comment by Janmm14** [comment]
It would be possible, but you would have to create your own transformers which choose a better name and create some little algorithm that checks whih classes fit together.

**Comment by LavaMensch** [comment]
okay thanks quiet now it isn't possible to do this? With the Deobfuscator?

**Comment by Janmm14** [comment]
@LavaMensch
Dude. If I say you need to create your own transformer, it implies its not possible without doing so.

**Comment by FireMasterK** [comment]
Made something like this and depends on the "Source File" I will publish it in a few days

**Comment by Janmm14** [comment]
SourceFile attributes are often erased or replaced.

**Comment by FireMasterK** [comment]
I do know about that but i don't think proguard removes them.

**Comment by Janmm14** [comment]
Proguard has an option to set sourcefileattribute to a constant or to keep it, by default its removed.

**Comment by FireMasterK** [comment]
https://ibb.co/fVfB6a
