### ISSUE TITLE
NullPointer HideAccess

### ISSUE THREAD

**Issue by TheKlimoT** [java-deobfuscator/deobfuscator#790]
https://paste.helpch.at/qegobiroqi.rb

Hi! I want to check for a hack plugin, but when HideAccessTransformer, NullPointerException crashes.

java -jar deobfuscator.jar -input F:\commands\universaleffectss2.jar -output F:\commands\universaleffectss3.jar -transformer stringer.StringEncryption -transformer stringer.HideAccessObfuscation -path "C:\Program Files\Java\jre1.8.0_291\lib\rt.jar" -path "C:\Program Files\Java\jre1.8.0_291\lib\jce.jar" -libraries "C:\Program Files\Java\jre1.8.0_291\lib\rt.jar" -libraries F:\commands\Vault(2).jar -libraries F:\commands\craftbukkit-1.16.3.jar

**Comment by TheKlimoT** [comment]
[universaleffects.zip](https://github.com/java-deobfuscator/deobfuscator/files/6772294/universaleffects.zip)
No copyrights are imposed on this plugin!

**Comment by Janmm14** [comment]
Looks liek the same error I got while attempting to deobf #785

**Comment by ThisTestUser** [comment]
The issue is from 3 encrypted calls that are unresolved for some reason. The latest patch gives the option to skip failed calls, which "fixes" this issue (right click the transformer in the GUI to select this option). Also, you can run allatori.FlowObfuscation after this to make the code cleaner.
