### ISSUE TITLE
Any suggestion for transformer?

### ISSUE THREAD

**Issue by Ian0526** [java-deobfuscator/deobfuscator#794]
Hello,

I've been able to successfully get an output; however, the class that I am specifically looking to deobfuscate is still gibberish. I've successfully added the paths, I've attempted to try a few different transformers (and of course the suggested output of the detection) but I haven't had any luck.

This is my detection output:
`[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleSourceFileAttribute: Some obfuscators don't remove the SourceFile attribute by default. This information can be recovered, and is very useful
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found possible SourceFile attribute on de/tr7zw/nbtinjector/javassist/DirClassPath: ClassPoolTail.java
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - (Choose one transformer. If there are multiple, it's recommended to try the transformer listed first)
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer`

Jar generation output:
`[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - I was unable to back up the previous output JAR
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 0 encrypted strings
[Stringer] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 849 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.EnumNormalizer
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing`

I'm aware that the StringEncryptionTransformer is finding zero strings, but I'm not sure what other transformer I should attempt. My background knowledge in encryption/decryption is very little. The class name is obfuscated as well as the methods, but I really don't care about the names and just want to see what the code does. Fairly certain it has a malicious aspect to it since the remote server that runs it had some files go magically missing as well as other unfortunate things.

My config is:

input: plugin.jar
output: deobfuscated.jar
path:
  - "C:\\Program Files\\Java\\jre1.8.0_281\\lib\\rt.jar"
  - "C:\\Users\\Ian05\\OneDrive\\Desktop\\Deob\\Vault.jar"
  - "C:\\Users\\Ian05\\OneDrive\\Desktop\\Deob\\spigot-1.16.4.jar"
  - "C:\\Users\\Ian05\\OneDrive\\Desktop\\Deob\\jdi.jar"
transformers:
  - stringer.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.EnumNormalizer
 
The formatting is off for the config since the hyphens are there, but it's in the appropriate format

**Comment by Janmm14** [comment]
Use a code block to show your config formatted as code. Place three ` at start and another 3 afterwards.
You obviously have to share the input jar file, even if a faggot hacked you, and not a single decompiled class file.

While you'Re at it, please ditch JD-Gui - its old and lots of bugs obfuscators use to show wrong or no code at all.
Use [Recaf](https://www.coley.software/Recaf/) or [ByteCodeViewer](https://github.com/Konloch/bytecode-viewer/releases/tag/v2.10.13) as GUI for the somewhat modern decompilers CFR, Procyon, Fernflower and Krakatau (Krakatau requires pypy2 installation)
