### ISSUE TITLE
How can I deobfuscate this?

### ISSUE THREAD

**Issue by puremesh** [java-deobfuscator/deobfuscator#798]
So basically, theres this code but its written in some sort of language and I dont know how to deobfuscate it. Could anyone help?
![image](https://user-images.githubusercontent.com/76163142/127192763-3e81bf79-11f0-4092-883f-8bf3f004d134.png)
You can't copy it either, help would be appreciated. Thanks.

**Comment by Janmm14** [comment]
Did you do this: https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started
What were results from the detect feature?

**Comment by rawget69420** [comment]
> Did you do this: https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started
> What were results from the detect feature?

The detect feature didn't detect anything.

**Comment by Python-22** [comment]
If you could provide the jar that might help, check this first #653 
If you know what you are doing you can also take a look at https://github.com/java-deobfuscator/deobfuscator/blob/master/CUSTOMTRANSFORMER.md to make your own transformer

**Comment by noom1337** [comment]
> So basically, theres this code but its written in some sort of language and I dont know how to deobfuscate it. Could anyone help?
> ![image](https://user-images.githubusercontent.com/76163142/127192763-3e81bf79-11f0-4092-883f-8bf3f004d134.png)
> You can't copy it either, help would be appreciated. Thanks.

looks like binscure, just write ur own transformer for it

**Comment by ItzSomebody** [comment]
Closing due to lack of response.  Feel free to ping if needed.
