### ISSUE TITLE
I have a question, where to create this whole config file and detect because I have a problem with provoking it; o

### ISSUE THREAD

**Issue by nvtliczeek** [java-deobfuscator/deobfuscator#801]
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - A config file must be specified

**Comment by ItzSomebody** [comment]
Doesn't matter where you put on your filesystem as long as you provide the path to it via arguments. e.g. `java -jar deobfuscator.jar --config config.yml` would search for the config in the working directory.
