### ISSUE TITLE
Trying to improve user experience

### ISSUE THREAD

**Issue by antoniovazquezblanco** [java-deobfuscator/deobfuscator#804]
I have recently discovered this utility and I have been trying to learn how to properly use it. I have found the documentation very useful but not very standardly organized which has made this a little bit more complex than expected.

I would like to know if you are interested in reviewing a PR with the following possible changes:
1. Using more standard input output for the command line argument parsing. Logger is very useful for a lib but in my opinion is not that user friendly in general. Maybe using HelpFormatter among standard input output for error parsing can reduce code and improve experience. This leads me to the next idea.
2. Would you like to split deobfuscator into "deobfuscator-cli" and "deobfuscator" in the same way as it has been done in "deobfuscator-gui"? This may help with external integration, issue separation between interface and core code, better user experience without increasing the core complexity among others.

Thank you

**Comment by Janmm14** [comment]
Currently the CLI only has one argument - the config file

I think splitting into a separate cli project would confuse people more than helping.

**Comment by antoniovazquezblanco** [comment]
Ok. Thank you!
