### ISSUE TITLE
SuperblaubeereTransformer | Using COMPUTE_MAXS

### ISSUE THREAD

**Issue by brokedevs** [java-deobfuscator/deobfuscator#807]
Receiving "Could not write file .. directory .. using compute max"
Already added rt.jar to my path

![imagem](https://user-images.githubusercontent.com/40664843/128505614-89d6cf5c-8792-4dd7-93e1-5f1b8f3951a1.png)
![imagem](https://user-images.githubusercontent.com/40664843/128505673-ba5841ae-85bc-4c1e-a589-5bf07766eda4.png)

**Comment by ThisTestUser** [comment]
The path should be "C:\Program Files\Java\jdk1.8.0_301\bin\rt.jar" instead. Also these errors can be ignored anyways.
