### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by ProJo4K** [java-deobfuscator/deobfuscator#81]
The download link https://ci.samczsun.com/job/Deobfuscator/ doesn't work? Where can i get your deobfuscator?

**Comment by Janmm14** [comment]
https://ci.janmm14.de/view/External%20plugins/job/public~external~deobfuscator/

**Comment by maxben14** [comment]
I can't download with this url link. Please, give me link on download *.jar file.

**Comment by samczsun** [comment]
Closing because the CI is now active
