### ISSUE TITLE
[QUESTION] ZKM DES Cipher

### ISSUE THREAD

**Issue by jiggey1** [java-deobfuscator/deobfuscator#818]
Is there any public way to deobfuscate ZKM DES Cipher? Is there any more work being put into it?

I want to know since I have many jar files which use ZKM and its frustrating not being able to deobf them. Thanks!

-jig

**Comment by Janmm14** [comment]
This tool has deobfuscation tranaformers for ZKM.

Please use the [detect feature](https://github.com/java-deobfuscator/deobfuscator#quick-start) so the program can tell you whether the ZKM obfuscation you got is supported by the obfuscator.

As a last note, we do not classify different ZKm obfiscation by cipher usage. I bet every ZKM string obfuscation of the last 6 years uses some sort of DES cipher.

**Comment by jiggey1** [comment]
Oh okay. well thanks for the insight. I know that newer versions of ZKM are super hard to crack, so cant blame the guys who crack it and keep it private. Thanks for the reply :D
