### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GGuPP1234567890** [java-deobfuscator/deobfuscator#826]
Pls ,can u help me? I dont understand this error

```
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occurred while parsing the configuration file
com.fasterxml.jackson.databind.exc.MismatchedInputException: Ca
nnot construct instance of `com.javadeobfuscator.deobfuscator.c
onfig.Configuration` (although at least one Creator exists): no
 String-argument constructor/factory method to deserialize from
 String value ('inputv inut.jar detect')
 at [Source: (File); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputEx
ception.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContex
t.reportInputMismatch(DeserializationContext.java:1329)
        at com.fasterxml.jackson.databind.DeserializationContex
t.handleMissingInstantiator(DeserializationContext.java:1031)
        at com.fasterxml.jackson.databind.deser.ValueInstantiat
or._createFromStringFallbacks(ValueInstantiator.java:370)
        at com.fasterxml.jackson.databind.deser.std.StdValueIns
tantiator.createFromString(StdValueInstantiator.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserialize
rBase.deserializeFromString(BeanDeserializerBase.java:1351)
        at com.fasterxml.jackson.databind.deser.BeanDeserialize
r._deserializeOther(BeanDeserializer.java:170)
        at com.fasterxml.jackson.databind.deser.BeanDeserialize
r.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.ObjectMapper._readMap
AndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValu
e(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.r
un(DeobfuscatorMain.java:66)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.m
ain(DeobfuscatorMain.java:36)
root@localhost:~#
```

**Comment by I2rys** [comment]
> Pls ,can u help me? I dont understand this error
> 
> [main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occurred while parsing the configuration file com.fasterxml.jackson.databind.exc.MismatchedInputException: Ca nnot construct instance of `com.javadeobfuscator.deobfuscator.c onfig.Configuration` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('inputv inut.jar detect') at [Source: (File); line: 1, column: 1] at com.fasterxml.jackson.databind.exc.MismatchedInputEx ception.from(MismatchedInputException.java:63) at com.fasterxml.jackson.databind.DeserializationContex t.reportInputMismatch(DeserializationContext.java:1329) at com.fasterxml.jackson.databind.DeserializationContex t.handleMissingInstantiator(DeserializationContext.java:1031) at com.fasterxml.jackson.databind.deser.ValueInstantiat or._createFromStringFallbacks(ValueInstantiator.java:370) at com.fasterxml.jackson.databind.deser.std.StdValueIns tantiator.createFromString(StdValueInstantiator.java:314) at com.fasterxml.jackson.databind.deser.BeanDeserialize rBase.deserializeFromString(BeanDeserializerBase.java:1351) at com.fasterxml.jackson.databind.deser.BeanDeserialize r._deserializeOther(BeanDeserializer.java:170) at com.fasterxml.jackson.databind.deser.BeanDeserialize r.deserialize(BeanDeserializer.java:161) at com.fasterxml.jackson.databind.ObjectMapper._readMap AndClose(ObjectMapper.java:4001) at com.fasterxml.jackson.databind.ObjectMapper.readValu e(ObjectMapper.java:2890) at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.r un(DeobfuscatorMain.java:66) at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.m ain(DeobfuscatorMain.java:36) root@localhost:~#

Download the compiled version of deobfuscator then follow the steps to make detect.yml, config.yml & use them correctly.

**Comment by ItzSomebody** [comment]
Any update on this @2d2dsite?

**Comment by I2rys** [comment]
> Any update on this @2d2dsite?

No update.
