### ISSUE TITLE
Failed to deobfusce Skid client

### ISSUE THREAD

**Issue by Elikill58** [java-deobfuscator/deobfuscator#833]
I'm trying to de-obfuscate Skid client (can't upload jar - Mojang Copyright).

When I ask for detectionthis is the output:
```
Recommend transformers:
(Choose one transformer. If there are multiple, it's recommended to try the transformer listed first)
   com.javadeobfuscator.deobfuscator.transformers.smoke.NumberObfuscationTransformer
All detectors have been run. If you do not see anything listed, check if your file only contains name obfuscation.
Do note that some obfuscators do not have detectors.
```

So, I made the config as asked in readme, and when it was generating jar, I get lot of warn like that:
```
Error: java/lang/Object could not be found while writing ?/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\<ommitted char>\/\/\/\/\/\/\/\/\/CK. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing ?/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\<ommitted char>\/\/\/\/\/\/\/\/\/DG. Using COMPUTE_MAXS
```
(There is 1060 times `/\` for each error line, and there is 375 lines with 1060 times this error)

Also, after checking other class, names are always un-readable:
![image](https://user-images.githubusercontent.com/17381066/137914552-6364cfe9-5a19-4b42-9e58-5fa4d836ad4a.png)
![image](https://user-images.githubusercontent.com/17381066/137914590-d2289797-cc52-4760-b418-9c9b8aba6040.png)

Do you need something more ?

**Comment by Janmm14** [comment]
The path is defined inside your config.yml file.

[Wiki - Getting started](https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started)
