### ISSUE TITLE
How to refactor variables in custom transformer

### ISSUE THREAD

**Issue by Gopro336** [java-deobfuscator/deobfuscator#837]
I am making a de-obfuscation transformer as described in #835 and I was successful in making it rename all the things I wanted to, except it only renamed them and did not refactor the fields/methods. All references to these fields/methods contain their old names. How would I make a transformer that does what I want?

[VariableMethodRenamer.java.zip](https://github.com/java-deobfuscator/deobfuscator/files/7403463/VariableMethodRenamer.java.zip)

**Comment by Janmm14** [comment]
You see, when I say to check out the normalizers, I have a reason for that ;)
Because the normalizers already do rename all the references as well as the fields.
I'm not sure how well they handle field/method inheritance tho.
