### ISSUE TITLE
Question: how to exclude certain classes from deobfuscation

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#839]
Is it possible to exclude certain classes from deobfuscation? If so how? I was unable to find any documentation on this. Additionally, what is a -path file for the method normalizer? What is that file supposed to have in it?

**Comment by Gopro336** [comment]
I have the rt.jar and my libraries added, and other transformers work fine, but when I use the MethodRenamer transformer it gives me this: 
```
** DO NOT OPEN AN ISSUE ON GITHUB **
Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: com/google/common/io/LineProcessor
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:487)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:569)
```
is It looking for some sort of list of names to rename to?
