### ISSUE TITLE
Ignore packages while deobbing

### ISSUE THREAD

**Issue by PureCS** [java-deobfuscator/deobfuscator#84]
It is somewhat common for JARs to be packaged with both application and library code, e.g.
```
app.jar/google-gson/...    
app.jar/my-app/...
```

Is there a way to ignore certain packages while deobbing?

**Comment by Janmm14** [comment]
Split it yourself maybe into two jars.

**Comment by samczsun** [comment]
Not sure why this wasn't closed automatically...
