### ISSUE TITLE
Full names of all transformers

### ISSUE THREAD

**Issue by AcaiBerii** [java-deobfuscator/deobfuscator#844]
Hey, I'm trying to use this transformer to deobfuscate a Minecraft mod made with Binscure.  
The name "BinscureTransformer" listed in my configuration file is giving me errors.  
Can I have the names of all transformers?

Thanks.

**Comment by Janmm14** [comment]
You need to use fully qualified class name of the transformer
BUT you can leave out `com.javadeobfuscator.deobfuscator.transformers.` at the start

**Comment by Gopro336** [comment]
transformers.BinscureTransformer 
works

**Comment by AcaiBerii** [comment]
> You need to use fully qualified class name of the transformer BUT you can leave out `com.javadeobfuscator.deobfuscator.transformers.` at the start

Thank you


> transformers.BinscureTransformer works

Actually for me it was special.BinscureTransformer
