### ISSUE TITLE
Help please?

### ISSUE THREAD

**Issue by JohhoA** [java-deobfuscator/deobfuscator#848]
hello, so, i used the special.SuperblaubeereTransformer and it removed most of the obfuscation, expept these: 
![image](https://user-images.githubusercontent.com/66090923/142685722-9e1ce8f1-16a0-4a96-b1b3-d30ebf56f4ed.png)
any way to remove them?

**Comment by Janmm14** [comment]
Try `general.removers.LocalVariableRemover` after superblaubeere

**Comment by JohhoA** [comment]
> Try `general.removers.LocalVariableRemover` after superblaubeere

thanks so much dude
