### ISSUE TITLE
Which version of rt.jar?

### ISSUE THREAD

**Issue by Duskfall** [java-deobfuscator/deobfuscator#849]
I would like to ask you how I can extract the rt.jar file from lets say Zulu builds or specifically for adoptopenjdk builds.
I have used another rt.jar from JRE 8 but I still gets erros for java/http which was introduced with Java 11 as I read.
Thanks!

**Comment by Janmm14** [comment]
I'm not sure, but I think this tool can create a rt jar: https://github.com/Storyyeller/jrt-extractor

**Comment by Janmm14** [comment]
**Please close the issue if it is solved!**
