### ISSUE TITLE
Is there guide?

### ISSUE THREAD

**Issue by PASAf** [java-deobfuscator/deobfuscator#85]
I'm sorry for posting this in issues. I'm wondering is there some recommendations on which order of transformers to use? Is SyntheticBridgeTransformer preferred to run before some obfuscator-specific transformers? And is there a way to detect which obfuscator is used?

**Comment by Janmm14** [comment]
@PASAf
SyntheticBridgeTransformer does not interact with any other transformer and can be run anywhere in the deobfuscation process.
I would suggest to take a look at the source code you see (at best do it with krakatau decompiler) and you should be able to know which obfuscations were used (string obf, reflection or invokedynamic). If you see invokedynamic calls, go for Stringer obfuscation. If you see some methods being named ALLATORI_DEMO, the used obfuscator is clear too. Else you have to try out which works. Also the order of the applied transformers can change the result from not working to good.

**Comment by PASAf** [comment]
@Janmm14 AFAIK Krakatau does not support invokedynamic and Java 8. I could be wrong. But I just realized that my problem is not related to transformer ordering. It's about string decryption, java-deobfuscator deobfuscate only 30% on strings, and I don't have enough experience with Java to fix that, unfortunately.

**Comment by samczsun** [comment]
This issue is rather stale, so I'm going to close it to clean up the overall list of issues. Please open a new issue if you still need help
