### ISSUE TITLE
SuperblaubeereTransformer Issue

### ISSUE THREAD

**Issue by SpaceBurn** [java-deobfuscator/deobfuscator#850]
Hello all,

I have been given permission to take over development of a custom Minecraft client. However the original dev has lost the SRC. I know what tool they used to obfuscate the jar file (SuperblaubeereTransformer) but when I try to run it through the obfuscator I keep getting this error. Is this normal or am I doing something wrong.

Thanks for all the help and have a great day.

Console Log:

> [Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer
[Special] [SuperblaubeereTransformer] Starting
[Special] [SuperblaubeereTransformer] Removed 169712 number obfuscation instructions
[Special] [SuperblaubeereTransformer] Inlined 111220 numbers
[Special] [SuperblaubeereTransformer] Unpooled 17075 strings
[Special] [SuperblaubeereTransformer] Inlined 33121 if statements
[Special] [SuperblaubeereTransformer] Removed 0 invokedynamics
[Special] [SuperblaubeereTransformer] Done
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/io/IOException could not be found while writing net/minecraft/client/gui/GuiMainMenu. Using COMPUTE_MAXS
Error: java/net/Inet6Address could not be found while writing io/netty/util/NetUtil. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing io/netty/util/internal/PlatformDependent0. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/client/stream/BroadcastController$1. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/gen/layer/GenLayer. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/command/CommandShowSeed. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing io/netty/channel/sctp/nio/NioSctpChannel. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/client/resources/model/ModelBakery. Using COMPUTE_MAXS
Error: java/util/IdentityHashMap could not be found while writing optifine/NaturalProperties. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/monster/EntitySpider. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing net/minecraft/client/gui/stream/GuiStreamUnavailable. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/util/concurrent/DefaultPromise. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/item/ItemEditableBook. Using COMPUTE_MAXS
Error: java/lang/OutOfMemoryError could not be found while writing net/minecraft/crash/CrashReport. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/world/gen/ChunkProviderFlat. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/renderer/texture/TextureManager. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/util/CombatTracker. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/block/BlockDoor. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing me/jacobtread1/isync/impl/modules/render/ClickGui. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/client/renderer/texture/TextureAtlasSprite$1. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing optifine/HttpPipelineReceiver. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing optifine/Config. Using COMPUTE_MAXS
Error: java/util/IdentityHashMap could not be found while writing optifine/ConnectedTextures. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/util/internal/chmv8/ConcurrentHashMapV8. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/chunk/storage/AnvilSaveConverter. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing io/netty/handler/codec/http/multipart/DefaultHttpDataFactory. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/util/internal/logging/InternalLoggerFactory. Using COMPUTE_MAXS
Error: java/lang/Runnable could not be found while writing io/netty/channel/AbstractChannelHandlerContext. Using COMPUTE_MAXS
Error: java/net/SocketAddress could not be found while writing io/netty/channel/udt/nio/NioUdtByteConnectorChannel. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing net/minecraft/command/PlayerSelector. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/item/ItemPotion. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing optifine/ChunkUtils. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/buffer/ByteBufUtil. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing io/netty/channel/group/DefaultChannelGroupFuture$1. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/biome/BiomeGenTaiga. Using COMPUTE_MAXS
Error: java/util/HashMap could not be found while writing net/minecraft/scoreboard/Scoreboard. Using COMPUTE_MAXS
Error: java/util/HashSet could not be found while writing net/minecraft/entity/ai/attributes/ModifiableAttributeInstance. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/command/server/CommandTeleport. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/biome/BiomeGenBase. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/client/gui/spectator/categories/TeleportToTeam$TeamSelectionObject. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing me/jacobtread1/isync/impl/screens/GuiOutdatedVersion. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing net/minecraft/client/stream/TwitchStream$1. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing io/netty/handler/ssl/SslHandler$2. Using COMPUTE_MAXS
Error: java/net/ConnectException could not be found while writing io/netty/channel/epoll/EpollSocketChannel$EpollSocketUnsafe. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing optifine/HttpPipelineConnection. Using COMPUTE_MAXS
Error: java/lang/RuntimeException could not be found while writing net/minecraft/client/resources/LanguageManager. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing io/netty/util/Version. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/passive/EntityHorse. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/biome/BiomeGenForest. Using COMPUTE_MAXS
Error: java/net/ConnectException could not be found while writing io/netty/channel/oio/AbstractOioChannel$DefaultOioUnsafe. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/client/renderer/texture/TextureAtlasSprite. Using COMPUTE_MAXS
Error: java/util/IdentityHashMap could not be found while writing io/netty/channel/DefaultChannelConfig. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/block/BlockChest. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/server/network/NetHandlerLoginServer. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/shader/ShaderManager. Using COMPUTE_MAXS
Error: java/io/FileNotFoundException could not be found while writing net/minecraft/server/management/PlayerProfileCache. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/world/storage/SaveHandler. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/gen/structure/MapGenScatteredFeature$Start. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/passive/EntityRabbit. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/tileentity/MobSpawnerBaseLogic. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/util/Cartesian$Product. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing io/netty/handler/codec/http/QueryStringDecoder. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/resources/ResourcePackRepository$Entry. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/entity/ai/EntityAIPlay. Using COMPUTE_MAXS
Error: java/util/LinkedList could not be found while writing io/netty/handler/traffic/GlobalTrafficShapingHandler. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/bootstrap/AbstractBootstrap. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing net/minecraft/entity/EntityTracker. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/util/IChatComponent$Serializer. Using COMPUTE_MAXS
Error: java/net/SocketTimeoutException could not be found while writing io/netty/channel/socket/oio/OioServerSocketChannel. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing io/netty/buffer/CompositeByteBuf. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing me/jacobtread1/isync/impl/screens/impl/ImportFrame. Using COMPUTE_MAXS
Error: java/lang/Double could not be found while writing me/jacobtread1/isync/impl/modules/render/hud/TabGui. Using COMPUTE_MAXS
Error: com/google/gson/JsonParseException could not be found while writing net/minecraft/tileentity/TileEntitySign. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/WorldProvider. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/command/CommandHandler. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing net/minecraft/client/gui/GuiChat. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/block/BlockSapling. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/handler/codec/spdy/SpdyHttpEncoder. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/world/gen/structure/MapGenStructureIO. Using COMPUTE_MAXS
Error: java/util/Set could not be found while writing net/minecraft/client/renderer/RenderGlobal. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing io/netty/channel/epoll/EpollDatagramChannel$EpollDatagramChannelUnsafe. Using COMPUTE_MAXS
Error: java/util/Map$Entry could not be found while writing io/netty/util/internal/chmv8/ConcurrentHashMapV8$ReduceEntriesTask. Using COMPUTE_MAXS
Error: java/io/FileNotFoundException could not be found while writing optifine/CustomItems. Using COMPUTE_MAXS
Error: com/mojang/authlib/exceptions/AuthenticationUnavailableException could not be found while writing net/minecraft/server/network/NetHandlerLoginServer$2. Using COMPUTE_MAXS
Error: javax/net/ssl/SSLSession could not be found while writing io/netty/handler/ssl/OpenSslEngine. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing net/minecraft/client/renderer/EntityRenderer. Using COMPUTE_MAXS
Error: java/lang/Boolean could not be found while writing optifine/ConnectedParser. Using COMPUTE_MAXS
Error: com/google/gson/JsonObject could not be found while writing optifine/PlayerItemParser. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/network/NetHandlerPlayServer. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/block/BlockDoublePlant. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/command/CommandStats. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing io/netty/handler/ssl/JettyNpnSslEngine. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing optifine/NbtTagValue. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/server/management/ServerConfigurationManager. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/network/NetHandlerPlayClient. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing io/netty/channel/socket/nio/NioDatagramChannel. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/channel/nio/AbstractNioByteChannel. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/world/storage/MapStorage. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing io/netty/handler/codec/spdy/SpdyHttpDecoder. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/gen/layer/GenLayerZoom. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing optifine/CrashReporter. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing io/netty/handler/ssl/OpenSslServerContext. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/buffer/UnpooledByteBufAllocator. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing shadersmod/client/ShadersTex. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/gen/structure/StructureVillagePieces. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/NpcMerchant. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/entity/AbstractClientPlayer. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/command/CommandTitle. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/util/internal/TypeParameterMatcher. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing io/netty/channel/nio/NioEventLoop. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing net/minecraft/client/gui/GuiScreenResourcePacks. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/util/internal/MpscLinkedQueue. Using COMPUTE_MAXS
Error: java/io/InputStream could not be found while writing net/minecraft/client/resources/FallbackResourceManager. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/gui/GuiOptionsRowList. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing shadersmod/client/BlockAliases. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/Teleporter. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing io/netty/util/internal/PlatformDependent. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing net/minecraft/util/StringTranslate. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/world/chunk/storage/AnvilChunkLoader. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/handler/codec/spdy/SpdyFrameCodec. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing io/netty/util/internal/Cleaner0. Using COMPUTE_MAXS
Error: java/net/SocketAddress could not be found while writing io/netty/channel/local/LocalChannel$LocalUnsafe. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/util/internal/chmv8/ForkJoinPool. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/block/BlockFlowerPot. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/handler/codec/http/HttpObjectAggregator. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/renderer/tileentity/TileEntityChestRenderer. Using COMPUTE_MAXS
Error: com/google/gson/JsonParseException could not be found while writing net/minecraft/client/resources/ResourcePackListEntryDefault. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing io/netty/channel/sctp/oio/OioSctpServerChannel. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing shadersmod/client/Shaders. Using COMPUTE_MAXS
Error: java/lang/InterruptedException could not be found while writing net/minecraft/util/Util. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/command/CommandBase. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/EntityTrackerEntry. Using COMPUTE_MAXS
Error: java/net/SocketAddress could not be found while writing io/netty/channel/udt/nio/NioUdtMessageConnectorChannel. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing optifine/VersionCheckThread. Using COMPUTE_MAXS
Error: java/net/ConnectException could not be found while writing io/netty/channel/nio/AbstractNioChannel$AbstractNioUnsafe. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing io/netty/util/internal/logging/MessageFormatter. Using COMPUTE_MAXS
Error: java/lang/Runnable could not be found while writing io/netty/handler/traffic/AbstractTrafficShapingHandler. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing optifine/Reflector. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/monster/EntityZombie. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/block/state/BlockState$StateImplementation. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/client/multiplayer/ServerList. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/entity/EntityList. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing io/netty/handler/codec/http/multipart/HttpPostRequestDecoder. Using COMPUTE_MAXS
Error: java/util/List could not be found while writing net/minecraft/command/CommandSpreadPlayers. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/buffer/AbstractByteBufAllocator. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/util/ChatComponentTranslation. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/item/ItemHangingEntity. Using COMPUTE_MAXS
Error: java/lang/ClassNotFoundException could not be found while writing io/netty/handler/ssl/SslHandler. Using COMPUTE_MAXS
Error: java/lang/IllegalAccessException could not be found while writing me/jacobtread1/isync/api/event/Event. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/nbt/NBTTagList. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing io/netty/channel/epoll/Epoll. Using COMPUTE_MAXS
Error: java/io/FileNotFoundException could not be found while writing optifine/FontUtils. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/realms/RealmsBridge. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/gen/structure/StructureNetherBridgePieces. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/tileentity/TileEntity. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/command/server/CommandScoreboard. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/buffer/PooledByteBufAllocator. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/ai/EntityAIControlledByPlayer. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing shadersmod/client/ShaderPackParser. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/model/ModelGuardian. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/biome/BiomeGenSavanna. Using COMPUTE_MAXS
Error: com/mojang/authlib/GameProfile could not be found while writing net/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing net/minecraft/command/CommandDebug. Using COMPUTE_MAXS
Error: java/util/IdentityHashMap could not be found while writing io/netty/util/internal/InternalThreadLocalMap. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing shadersmod/client/GuiShaders. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/gui/GuiPageButtonList. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/handler/codec/marshalling/CompatibleMarshallingDecoder. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing net/minecraft/command/CommandReplaceItem. Using COMPUTE_MAXS
Error: javax/crypto/BadPaddingException could not be found while writing net/minecraft/util/CryptManager. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/player/EntityPlayerMP. Using COMPUTE_MAXS
Error: java/nio/channels/ClosedChannelException could not be found while writing io/netty/handler/stream/ChunkedWriteHandler. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/client/gui/GuiScreen. Using COMPUTE_MAXS
Error: com/google/common/collect/HashMultimap could not be found while writing net/minecraft/item/ItemStack. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing optifine/CustomSky. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing optifine/CustomColormap. Using COMPUTE_MAXS
Error: java/lang/NullPointerException could not be found while writing io/netty/util/internal/chmv8/ForkJoinTask. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/gen/structure/StructureStrongholdPieces. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/tileentity/TileEntityHopper. Using COMPUTE_MAXS
Error: com/google/common/collect/HashBiMap could not be found while writing net/minecraft/network/EnumConnectionState. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/entity/player/EntityPlayer. Using COMPUTE_MAXS
Error: java/lang/RuntimeException could not be found while writing net/minecraft/client/Minecraft. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/world/biome/BiomeGenJungle. Using COMPUTE_MAXS
Error: java/util/List could not be found while writing io/netty/util/internal/RecyclableArrayList. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/command/CommandKill. Using COMPUTE_MAXS
Error: java/io/FileNotFoundException could not be found while writing optifine/TextureAnimations. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing net/minecraft/client/multiplayer/WorldClient. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing net/minecraft/client/settings/GameSettings. Using COMPUTE_MAXS
Error: java/lang/RuntimeException could not be found while writing net/minecraft/client/audio/SoundHandler. Using COMPUTE_MAXS
Error: java/io/FileNotFoundException could not be found while writing optifine/CustomColors. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing io/netty/channel/epoll/EpollSocketChannel. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing io/netty/channel/sctp/oio/OioSctpChannel. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing io/netty/channel/sctp/nio/NioSctpServerChannel. Using COMPUTE_MAXS

Sample:
[Download](https://www.mediafire.com/file/0j3rf2fu5x8x6t8/iSync.jar/file)

Edit: I would like to also mention I am using the GUI and whenever I try to deobfuscate the client I get the same result as above before it just gets stuck there.

**Comment by Janmm14** [comment]
You need to add rt.jar from the java installation to the path.

If you need java 9+ rt.jar use https://github.com/Storyyeller/jrt-extractor

**Comment by Janmm14** [comment]
**Please close the issue if it is solved!**
