### ISSUE TITLE
Help me because i can't decompile this (radon)

### ISSUE THREAD

**Issue by Haru1ca** [java-deobfuscator/deobfuscator#882]
this Is a Radon obfuscation sample, can someone decompile it? thx.
https://www.mediafire.com/file/uglt4ii7pczx8xr/Lowkeyv2.jar.zip/file

**Comment by Janmm14** [comment]
There are two transformers for radon. What error comes up during usage?

**Comment by Haru1ca** [comment]
> There are two transformers for radon. What error comes up during usage?

special.RadonTransformer
and
general.peephole.DeadCodeRemover

**Comment by Haru1ca** [comment]
> There are two transformers for radon. What error comes up during usage?

V2 is also unuseful
it also shows could not parse *.class (is it a class file)
and detect is disabled

**Comment by Janmm14** [comment]
@Haru1ca

Its sad that you don't post the errors of the program.
This is not deobfuscation-as-a-service! I tried to convey this message earlier in a more gentle way.

While errors pop up it seem that there are numerous classes readable, strings and numbers getting successfully deobfuscated.

Radon can add trash classes, so the errors might just come from those trash classes.
