### ISSUE TITLE
Superblaubeere Transformer - Not decrypting Strings

### ISSUE THREAD

**Issue by Dani-error** [java-deobfuscator/deobfuscator#887]
I tried to use the transformer of Superblaubeere obfuscator with my own plugin rCaptcha [https://github.com/Dani-error/rCaptcha](https://github.com/Dani-error/rCaptcha), so I obfuscated the plugin with String Encryption (with AES) and when I tried to deobfuscate, nothing happens, no errors, nothing... The string arrays keep there...

I tried adding the GotoRearranger and DeadCodeRemover and nothing...

I added a message to the if to check if the method insntructions matches, and nope it didn't (the message appears every time I try to deobfuscate):

```java
                if (!STRING_ENCRYPT_MATCHER.matchImmediately(refMethod.instructions.iterator())) {
                    System.out.println("[SuperblaubbeereTransformer] Class "+classNode.name+" not match");
                    continue;
                }
```

(I can't upload the plugin because the file format its not supported)

**Comment by Janmm14** [comment]
Rename .jar to .zip and upload will be just fine.

**Comment by Dani-error** [comment]
[rCaptcha-1.0.0-RELEASE-obf.zip](https://github.com/java-deobfuscator/deobfuscator/files/8259726/rCaptcha-1.0.0-RELEASE-obf.zip)

**Comment by Dani-error** [comment]
@Janmm14 It works! Thanks 😄

**Comment by Dani-error** [comment]
I suggest to change the "lIlIlI" variables to the variable class name (feature for the SuperblaubeereTransformer)

Before:
```java
public String lIlIlI;
```

After:
```java
public String string;
```

**Comment by Janmm14** [comment]
> I suggest to change the "lIlIlI" variables to the variable class name (feature for the SuperblaubeereTransformer)
> 
> Before:
> 
> ```java
> public String lIlIlI;
> ```
> 
> After:
> 
> ```java
> public String string;
> ```

Add LocalVariableRemover as last transformer, change decompiler setting to not recover variable names or use another decompiler.
At least in your plugin there is no field renamed, there are only annoying entries in the local variable table which can be simply removed with said transformer.

If you speak about other plugins where field name obfuscation is applied, use normalizer.FieldNormalizer to rename all fields to field_1 field_2 field_3 etc.

**Comment by Dani-error** [comment]
Thanks!
