### ISSUE TITLE
Provide a transformer which recovers class names from SourceFile attributes.

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#9]
Not always useful, but I've sawn a failed obfuscated project I wanted to control and its a bit annoying if there are many classes you have to manually create rename rules.

It might not fit to this project.

**Comment by Storyyeller** [comment]
You should probably do a sanity check on the values first. I've seen code where the SourceFile attribute is present but set to "SourceFile". It may also be set to the obfuscated name.

**Comment by Janmm14** [comment]
Yeah, but in that particular case the SourceFile attributes are correct (not obfuscated and seem to fit to the obfuscated code) and only the class names are obfuscated.

**Comment by Janmm14** [comment]
Not really neccessary, as basically all obfuscators rename/change/remove that. This request was based on one jar which wasn't properly obfuscated, but its not neccessary actually.
