### ISSUE TITLE
Can u add method's argument normalizer?

### ISSUE THREAD

**Issue by QwertyYtPL** [java-deobfuscator/deobfuscator#901]
Method's argument normalizer will be helpful if u can add it

**Comment by QwertyYtPL** [comment]
or just argument normalizer

**Comment by QwertyYtPL** [comment]
because class's constructor also have arguments

**Comment by Janmm14** [comment]
You mean LocalVariableNameRemover?
https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/general/removers/LocalVariableRemover.java

**Comment by QwertyYtPL** [comment]
no, i don't want to delete local variables

**Comment by QwertyYtPL** [comment]
wait i will give example

**Comment by QwertyYtPL** [comment]
and of course it should rename references to args too

**Comment by Janmm14** [comment]
> no, i don't want to delete local variables

it does not delete local variables despite its name.
what it does is removing the name associations of local variable positions. this will make every decompiler (without an option of ignoring the local variable name table) to invent variable names.

local variables are referenced by number, not by name.

**Comment by QwertyYtPL** [comment]
hmm ok, so should I just use LocalVariableNameRemover??

**Comment by Janmm14** [comment]
yes (although its called different)
