### ISSUE TITLE
java.lang.IllegalArgumentException: entry name too long

### ISSUE THREAD

**Issue by momonunu** [java-deobfuscator/deobfuscator#903]
I tried using only com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer. on a file then this error came up.

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 26 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/Exception could not be found while writing JsonUtils. Using COMPUTE_MAXS





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException: entry name too long
	at java.util.zip.ZipEntry.<init>(ZipEntry.java:103)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:460)
	at java.util.HashMap$Values.forEach(HashMap.java:983)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:456)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
```

i think it may have something to do with this:

<img width="633" alt="Screenshot 2022-05-17 at 07 09 54" src="https://user-images.githubusercontent.com/47526369/168733637-f48f6751-6af4-4cc2-83d4-5cce02305296.png">

or this:

<img width="1095" alt="Screenshot 2022-05-17 at 07 10 30" src="https://user-images.githubusercontent.com/47526369/168733706-f36542a7-7850-436e-a370-431501f3ca56.png">

**Comment by Janmm14** [comment]
Are you sure that the SourceFile attribute of the classes is original? It might also be that it got changed to rubbish or that its used as a key in the deobfuscation procress.

**Comment by momonunu** [comment]
I tried deleting this nested folder, but it didnt work after that because some classes could not be found.

**Comment by Janmm14** [comment]
The SourceClassFileTransformer is a simple class renamer, it won't help you see the source unobfuscated.

**Comment by ItzSomebody** [comment]
Closing due to lack of response from OP.
