### ISSUE TITLE
java.lang.ClassCastException: org.objectweb.asm.tree.VarInsnNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode

### ISSUE THREAD

**Issue by steelswing** [java-deobfuscator/deobfuscator#905]
![image](https://user-images.githubusercontent.com/53971838/170549197-b441dede-80e1-44e0-b262-a88a5c1de8ef.png)

**Comment by Janmm14** [comment]
happens when you dont do zelix stringencryptiontransformer before
