### ISSUE TITLE
com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer broken!

### ISSUE THREAD

**Issue by jabask3dd3r** [java-deobfuscator/deobfuscator#920]
![image](https://user-images.githubusercontent.com/108399009/179910262-e1716b4e-8b29-429d-bd0d-0e37bfb56b97.png)

com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer broken!
file sample -> [deleted]

fix plz

**Comment by Janmm14** [comment]
@samczsun @ItzSomebody Please remove the link to the sample. It does not follow #653 (minecraft included)

**Comment by ItzSomebody** [comment]
Thanks for checking Jan.

@jabask3dd3r: Please make sure to read the issue Jan linked.

As for the actual issue itself, it might be worth adding an explicit check for file extensions, to be honest.
