### ISSUE TITLE
Download a Deobfuscator.

### ISSUE THREAD

**Issue by HP888** [java-deobfuscator/deobfuscator#93]
Hi, can send me JavaDeobfuscator.jar on mediafire or zippyshare no ci.samczsun.com

Thanks.

**Comment by FFY00** [comment]
[deobfuscator-1.0.0.zip](https://github.com/java-deobfuscator/deobfuscator/files/968738/deobfuscator-1.0.0.zip)

**Comment by Janmm14** [comment]
compile it yourself xd

**Comment by HP888** [comment]
Thank you!

**Comment by FFY00** [comment]
np, you can close the issue now
