### ISSUE TITLE
Error working out transformer

### ISSUE THREAD

**Issue by Cairn23** [java-deobfuscator/deobfuscator#943]
I have used the instructions on how to use this.
I have carried out the 1st phase with the detect file.it
 says its loading the classpath, input and then dectecting known obfuscators.
 the application then terminates. What and where am I expecting to see things, I thought it may write out the required transformer, but nothing.

How do you determine the input for the second phase with the config file
I did attemp to create a config.yaml file with just the input and output files names and run that as per the instructions but an error message stated "A config file must be specified"

I am using v1.5.2 due to the current issue with the latest version

**Comment by Janmm14** [comment]
You could use the release from this random fork until my PR is merged: https://github.com/suckma420/deobfuscator/releases/tag/latest

**Comment by Janmm14** [comment]
Alternatively using the GUI might b a solution as well, as the GUI is not using jackson/yaml
