### ISSUE TITLE
Work for APK?

### ISSUE THREAD

**Issue by jaspergould** [java-deobfuscator/deobfuscator#95]
!? Android, classes.dex

**Comment by jaspergould** [comment]
etc

**Comment by CunningLogic** [comment]
Convert dex to jar with enjarify or dex2jar and try it?

**Comment by jaspergould** [comment]
@CunningLogic for .apk?

**Comment by FFY00** [comment]
@jaspergould you need to extract the classes.dex file from the apk first

**Comment by samczsun** [comment]
For future reference, and I'll update the README on this too, I hear [Simplify](https://github.com/CalebFenton/simplify) works great.

**Comment by jaspergould** [comment]
@samczsun srsly? work for DexGuard and ProGuard?

**Comment by Janmm14** [comment]
@jaspergould You should be more precise if you want to have dedicated transformers to dexguard.
Proguard can't be reversed.
