### ISSUE TITLE
Native invocation

### ISSUE THREAD

**Issue by SlushKo** [java-deobfuscator/deobfuscator#962]
in some way. i successfully found the decrypt function for the encrypted string. but it was an native method that used JNI to load the native file. i can just invoke the native method to deobfuscate the string encryption. so how to invoke the native method at runtime

**Comment by Janmm14** [comment]
Not supported

**Comment by Janmm14** [comment]
Don't crack it or learn to decompile native code. Might be that the native code is obfuscated with some native obfuscator. In that caseyou'll be out of luck if you're no expert.

**Comment by SlushKo** [comment]
im not gonna decomplie native code. i just wanna invoke the registered native method. anyway i already resolve this problem by load the jar file as a library to my program and load the dll file with the same way to the original jar file. and invoke the native method and i already deobfuscated the jar file

**Comment by Janmm14** [comment]
I do not suggest such a thing, because that is no longer emulating xode in a safe space - what this deobfuscator does for java bytecode.
