### ISSUE TITLE
Can somebody deobfuscate plugin?

### ISSUE THREAD

**Issue by Urek00** [java-deobfuscator/deobfuscator#97]
Hello, i have plugin obfuscated by Allatori. He's code is so ugly i want to get normal plugin, and edit them. Can somebody deobfuscate this plugin cuz im stupid ;p? 

[DMcore.zip](https://github.com/java-deobfuscator/deobfuscator/files/1048560/DMcore.zip)

**Comment by Janmm14** [comment]
the plugin was obfucate with bad alltori settings.
a simple usage of allatori's string deobfuscator should make the code to something nearly like the original code.

**Comment by Urek00** [comment]
You can't do this? ;c

**Comment by Janmm14** [comment]
I am able to do that easily, but I won't do it because I think normally people who are to bad to use this deobfuscator should not even try to modify anything, they can usually not make it better

**Comment by Urek00** [comment]
Pls janmm do this. ;c

**Comment by samczsun** [comment]
This is really not necessary
