### ISSUE TITLE
Allow normalizing classes and rename all references in IgnoredClasses

### ISSUE THREAD

**Issue by uniformization** [java-deobfuscator/deobfuscator#976]
I propose an option users can chose to rename all references to the normalized class name for IgnoredClasses too. For example, I have a JAR file that is partially obfuscated and deobfuscated, I want to normalize all the obfuscated names without interfering the already-deobfuscated names.

**Comment by uniformization** [comment]
The same also applies for MethodNormalizer, FieldNormalizer and EnumTransformer.

**Comment by Janmm14** [comment]
i'd suggest using proguard

**Comment by uniformization** [comment]
> i'd suggest using proguard

that works, should i close this issue?
