### ISSUE TITLE
deobfuscator error

### ISSUE THREAD

**Issue by Urek00** [java-deobfuscator/deobfuscator#98]
I use this Command : "java -jar deobfuscator-1.0.0.jar -input easymaxCore.jar -output easymaxCore-deobf.jar -transformer allatori.StringEncryptionTransformer -path C:\Program Files (x86)\Java\jre1.8.0_72\lib\rt.jar"
But i get a error on a screen.
![screenshot 2017-06-02 21-47-32](https://cloud.githubusercontent.com/assets/29150699/26742211/1a47a07c-47dd-11e7-8982-3d8c235b7fb2.jpg)

**Comment by FFY00** [comment]
Run "dir" in that directory and post the output.

**Comment by Urek00** [comment]
Still same.

**Comment by Janmm14** [comment]
Stop asking the same things. kthx

The error says that there is no file called `deobfuscator-1.0.0.jar` in the directory `C:\Users\Kamik`

**Comment by Urek00** [comment]
it is called deobfuscator-1.0.0.jar

**Comment by Urek00** [comment]
Everything was good but when i start server i got this error:  http://screenshot.sh/mLayi35UXo7YH

**Comment by FFY00** [comment]
Looks like the deobfuscator isn't updated to that version of Allatori. There's we can do.

**Comment by Urek00** [comment]
I got it, i changed spiggot version.

**Comment by Janmm14** [comment]
Error output when deobfuscating with allatori does not neccessarily mean the deobfuscation was no success.

**Comment by Urek00** [comment]
But it is success, cuz i got it.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
