### ISSUE TITLE
Error to deobfuscate Allatori

### ISSUE THREAD

**Issue by filipeq2604** [java-deobfuscator/deobfuscator#99]
I tried to deobfuscate a jar file but no sucess.
The result was a invalid java code.

```
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
```
See the full log output:
[log.txt](https://github.com/java-deobfuscator/deobfuscator/files/1059443/log.txt)

I used this command:
`java -Xss128M -jar deobfuscator-1.0.0.jar -input SAS_3_0b86_windows.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_121\lib/rt.jar"
`
I tried this also:
`java -jar deobfuscator-1.0.0.jar -input SAS_3_0b86_windows.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_121\lib/rt.jar"`

The input jar:
https://mega.nz/#!qY4FwBAI!yT-trjp0SUkhLogcWtSXSPQoxxxBleiC8fBdyRHqMBM

**Comment by Urek00** [comment]
This plugin not have plugin.yml.

Use -path "Location to PaperSpiggot"
And Use -path "C:\Program Files\Java\jre1.8.0_121\lib\rt.jar"

**Comment by Janmm14** [comment]
>This plugin not have plugin.yml.
>
>Use -path "Location to PaperSpiggot"
>And Use -path "C:\Program Files\Java\jre1.8.0_121\lib\rt.jar"
>
>What is main class?
>
>_written by @Urek00_
Maybe you forgot that this program is not only thought for deobfuscating minecraft server plugins, but suited for any java program.

Did you checked the output jar for not-deobfuscated strings? Errors like these can occurr in other circumstances too.

**Comment by filipeq2604** [comment]
@Urek00 
I changed -path to "C:\Program Files\Java\jre1.8.0_121\lib\rt.jar" but the output.ar (and log msgs) was the same.
What you mean with 

> Use -path "Location to PaperSpiggot"
I have no idea what is papegspiggot. I search on Google but no luck.

**Comment by filipeq2604** [comment]
@Janmm14 
All strings still obfuscated. Nothings works yet.

**Comment by netindev** [comment]
Mano, essa versão do deobfuscator ainda não foi atualizada para suportar as novas versões do Allatori, entretanto, as strings ainda vão continuar a não ser desofuscatadas até que uma nova versão arrume este erro.

**Comment by filipeq2604** [comment]
Obrigado @netindev . Mas e o código fonte é possível deobfuscar?

**Comment by netindev** [comment]
Sim, é possível.

**Comment by filipeq2604** [comment]
Alguma sugestao pq nao funciona? Ou como fazer?

**Comment by netindev** [comment]
É como eu te falei desde o início, até não sair uma nova versão, você não vai conseguir ver as strings desofuscadas, se você quiser apenas descompilar, use o Krakatau, depois desofusque manualmente.

**Comment by FFY00** [comment]
@filipeq2604 basta isolar o metodo(s) de deofuscacao e rodar numa VM...

Aqui esta um VM que pode utilizar: https://github.com/drxaos/jvmvm

**Comment by c001man** [comment]
I've posted a fix for the latest version of allatori.
https://github.com/c001man/deobfuscator

**Comment by filipeq2604** [comment]
@c001man The link [https://github.com/c001man/deobfuscator](https://github.com/c001man/deobfuscator) is broken.
Where I can get the latest build?

**Comment by netindev** [comment]
@filipeq2604
Baixa essa: https://github.com/ThisTestUser/deobfuscator
E se quiser usar um GUI, você precisa buildar esse projeto e depois executar esse: https://github.com/ThisTestUser/deobfuscator-gui

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
