### ISSUE TITLE
Allatori remove package

### ISSUE THREAD

**Issue by Midaco-YT** [java-deobfuscator/deobfuscator#997]
Hello, I have a question, allatori renames classes and deletes packages. Is it possible to retrieve packages and their names?

**Comment by Janmm14** [comment]
no

**Comment by Midaco-YT** [comment]
okay, Also I believe that allatori create classes with not much at the interrieur. how to find the original class number?

**Comment by ItzSomebody** [comment]
> how to find the original class number?

This may or may not be possible. Check the SourceFileClassNormalizer like Jan suggested. If that doesn't work, then unfortunately nothing else can really be done.
